force-app/main/default/objects/Sales_Representative__c/Sales_Representative__c.object-meta.xml
<CustomObject>
    <label>Sales Representative</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sales Representative Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Representative__c/fields/Commision__c.field-meta.xml
<CustomField>
    <fullName>Commision__c</fullName>
    <label>Commision</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Engineer Split</relationshipLabel>
    <relationshipName>SalesRepresentatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepresentatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesEngineerSplitTriggerHandler.cls
/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 04-23-2024
 * @last modified by  : Nilesh Badrakiya
**/
public with sharing class SalesEngineerSplitTriggerHandler{
    
    public static Map<String,Id> mapOfficeNameSalesRepId = new Map<String,Id>{
        'Midwest Machinery STL' => '00561000000gZ3T',
        'Midwest Machinery KC'=> '00561000000gZ6I',
        'Midwest Machinery OK'=>'00561000000gZ68',
        'Engineered Products'=> '00561000000gZ6D'
    };
    
    public static void createSalesRepEntry(String oppId, String oppOffice){
        
        Sales_Representative__c newSalesRep = new Sales_Representative__c();
        newSalesRep.Commision__c = 100;
        newSalesRep.Opportunity__c = oppId;
        newSalesRep.Sales_Rep__c = mapOfficeNameSalesRepId.get(oppOffice);
        insert newSalesRep;
    
    }
    
    public static void updateSalesRepEntry(String oppId, String oppOffice){
        
        List<Sales_Representative__c> lstSalesRep = [Select Id,Sales_Rep__c From Sales_Representative__c
                                                    WHERE Id IN :mapOfficeNameSalesRepId.values()
                                                    AND Opportunity__c =: oppId];
                                                    
        if(!lstSalesRep.isEmpty()){
            lstSalesRep[0].Sales_Rep__c = mapOfficeNameSalesRepId.get(oppOffice);
            update lstSalesRep[0];
        }
        else{
            createSalesRepEntry(oppId, oppOffice);
        }
    }
    
}