force-app/main/default/objects/Sales_Representative__c/Sales_Representative__c.object-meta.xml
<CustomObject>
    <label>Sales Representative</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sales Representative Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Representative__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <formula>TEXT(Sales_Rep__r.Office_Location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Office Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Engineer Split</relationshipLabel>
    <relationshipName>SalesRepresentatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepresentatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saint Louis</fullName>
            </value>
            <value>
                <fullName>Oklahoma</fullName>
            </value>
            <value>
                <fullName>Kansas City</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/STLDashboardTest.cls
/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 02-05-2024
 * @last modified by  : Nilesh Badrakiya
**/
@isTest
private class STLDashboardTest{
    
    static testMethod void testSTLDashboard() {
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
         User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, Office_Location__c = 'Saint Louis',
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduserSTLDB@testorg.com');
        
        //insert u; 
        
        Test.StartTest();
         Id equipmentRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Equipment - Plan/Spec').getRecordTypeId();
        // create opportunity
        Opportunity objOpportunity = new Opportunity(closeDate = Date.today(),
                                                    Name = 'Test Opportunity',
                                                    stageName = 'TARGET/NEGOTIATING',
                                                    recordTypeId = equipmentRecordTypeId);
        
        insert objOpportunity;
        
        
        // create sales rep
        Sales_Representative__c rep = new Sales_Representative__c();
        rep.Opportunity__c = objOpportunity.Id;
        rep.Sales_Rep__c = UserInfo.getUserId();
        insert rep;   
        
        
        STLDashboard objSTLDashboard = new STLDashboard();
        Test.StopTest();
    }

}