force-app/main/default/objects/Sales_Representative__c/Sales_Representative__c.object-meta.xml
<CustomObject>
    <label>Sales Representative</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sales Representative Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Representative__c/fields/Commision__c.field-meta.xml
<CustomField>
    <fullName>Commision__c</fullName>
    <label>Commision</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Engineer Split</relationshipLabel>
    <relationshipName>SalesRepresentatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepresentatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddEditSalesEngineerSplitController.cls
public with sharing class AddEditSalesEngineerSplitController{
    
    public Id opportunityId{get;set;}
    public List<Sales_Representative__c> lstSalesRep{get;set;}
    
    public String hidSalesRepId{get;set;}
    public Integer hidRowIndex{get;set;}
    
    public AddEditSalesEngineerSplitController(){
        
        opportunityId = Apexpages.currentPage().getParameters().get('oppId');
        
        lstSalesRep = [Select Id, Sales_Rep__c,Commision__c
                        FROM Sales_Representative__c
                        WHERE Opportunity__c =: opportunityId];
                        
        
    }
    
    public void addSalesEngineer(){
        lstSalesRep.add(new Sales_Representative__c(Opportunity__c = opportunityId));
    }
    
    public void deleteSalesEnginner(){
        if(hidSalesRepId != null && hidSalesRepId != ''){
            delete [Select Id From Sales_Representative__c WHERE Id =:hidSalesRepId];
        }
        lstSalesRep.remove(hidRowIndex - 1);
    }
    
    public PageReference redirectBackToOpportunity(){
        PageReference pr = new PageReference('/'+opportunityId);
        pr.setRedirect(true);
        return pr;
    }
    
    public PageReference Save(){
        upsert lstSalesRep;
        
        return redirectBackToOpportunity();
    }
    
}