force-app/main/default/objects/ActivityGoalPoints__c/ActivityGoalPoints__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Activity Goal Points</label>
</CustomObject>

force-app/main/default/objects/ActivityGoalPoints__c/fields/Point__c.field-meta.xml
<CustomField>
    <fullName>Point__c</fullName>
    <label>Point</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogACall__c/LogACall__c.object-meta.xml
<CustomObject>
    <label>Log A Call</label>
    <nameField>
        <displayFormat>Call-{00000}</displayFormat>
        <label>Log A Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogACall__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LogCalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>IF(OR(ISPICKVAL(Type_of_Call__c, &apos;Client Office Visit&apos;), 
ISPICKVAL(Type_of_Call__c, &apos;Site Visit (Project Related)&apos;)), 5, 
IF(OR(ISPICKVAL(Type_of_Call__c, &apos;Entertain (Hpy Hr, Glf, Gms)&apos;),
ISPICKVAL(Type_of_Call__c, &apos;End User Visit&apos;), 
ISPICKVAL(Type_of_Call__c, &apos;Meal&apos;)), 10, 
IF(ISPICKVAL(Type_of_Call__c, &apos;Factory Visit (Travel)&apos;), 30, 
IF(OR(ISPICKVAL(Type_of_Call__c, &apos;Factory Visit (Local)&apos;), 
ISPICKVAL(Type_of_Call__c, &apos;Training (L-N-L, Seminar)&apos;)), 20, 10))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Type_of_Call__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Call__c</fullName>
    <label>Type of Call</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client Office Visit</fullName>
            </value>
            <value>
                <fullName>End User Visit</fullName>
            </value>
            <value>
                <fullName>Entertain (Hpy Hr, Glf, Gms)</fullName>
            </value>
            <value>
                <fullName>Expense Only</fullName>
            </value>
            <value>
                <fullName>Factory Visit (Travel)</fullName>
            </value>
            <value>
                <fullName>Industry Event (Ashrae etc.)</fullName>
            </value>
            <value>
                <fullName>Meal</fullName>
            </value>
            <value>
                <fullName>Site Visit (Project Related)</fullName>
            </value>
            <value>
                <fullName>Training (L-N-L, Seminar)</fullName>
            </value>
            <value>
                <fullName>Factory Visit (Local)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/SalesActivityGoal__c.object-meta.xml
<CustomObject>
    <label>Sales Activity Goal</label>
    <nameField>
        <displayFormat>SG-{00000}</displayFormat>
        <label>Sales Activity Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Activity Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesActivityGoal__c/fields/ClientOfficeVisit__c.field-meta.xml
<CustomField>
    <fullName>ClientOfficeVisit__c</fullName>
    <label>Client Office Visit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/EndUserVisit__c.field-meta.xml
<CustomField>
    <fullName>EndUserVisit__c</fullName>
    <label>End User Visit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Entertainment__c.field-meta.xml
<CustomField>
    <fullName>Entertainment__c</fullName>
    <label>Entertainment (Golf, Games, Etc.)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/FactoryVisitLocal__c.field-meta.xml
<CustomField>
    <fullName>FactoryVisitLocal__c</fullName>
    <label>Factory Visit (Local)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/FactoryVisitTravel__c.field-meta.xml
<CustomField>
    <fullName>FactoryVisitTravel__c</fullName>
    <label>Factory Visit (Travel)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/HappyHour__c.field-meta.xml
<CustomField>
    <fullName>HappyHour__c</fullName>
    <label>Happy Hour - Cocktails</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Master_Report__c.field-meta.xml
<CustomField>
    <fullName>Master_Report__c</fullName>
    <label>Master Report?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Midwest Machinery</fullName>
            </value>
            <value>
                <fullName>Saint Louis</fullName>
            </value>
            <value>
                <fullName>Oklahoma</fullName>
            </value>
            <value>
                <fullName>Kansas City</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Meal__c.field-meta.xml
<CustomField>
    <fullName>Meal__c</fullName>
    <label>Meal</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/SalesRep__c.field-meta.xml
<CustomField>
    <fullName>SalesRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Activity_Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/SiteVisit__c.field-meta.xml
<CustomField>
    <fullName>SiteVisit__c</fullName>
    <label>Site Visit (Project Related)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <label>Training (L-N-N, Seminar)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/has_house_Account_Access__c.field-meta.xml
<CustomField>
    <fullName>has_house_Account_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <label>has house Account Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Is_Director__c.field-meta.xml
<CustomField>
    <fullName>Is_Director__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Director?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Is_Manager__c.field-meta.xml
<CustomField>
    <fullName>Is_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Manager?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saint Louis</fullName>
            </value>
            <value>
                <fullName>Oklahoma</fullName>
            </value>
            <value>
                <fullName>Kansas City</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesActivityCtrl.cls
/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 01-24-2024
 * @last modified by  : Nilesh Badrakiya
**/
public with sharing class SalesActivityCtrl {
    public static final String ACTIVITY_CLIENTOFFICE_VISIT = 'Client Office Visit';
    public static final String ACTIVITY_ENDUSER_VISIT = 'End User Visit';
    public static final String ACTIVITY_ENTERTAINMENT = 'Entertain (Hpy Hr, Glf, Gms)';
    public static final String ACTIVITY_FACTORY_VISIT_LOCAL = 'Factory Visit (Local)';
    public static final String ACTIVITY_FACTORY_VISIT_TRAVEL = 'Factory Visit (Travel)';
    public static final String ACTIVITY_HAPPY_HOUR = 'Industry Event (Ashrae etc.)';
    public static final String ACTIVITY_Meal = 'Meal';
    public static final String ACTIVITY_SITE_VISIT = 'Site Visit (Project Related)';
    public static final String ACTIVITY_TRAININ = 'Training (L-N-L, Seminar)';
    public static final String SAINT_LOUIS = 'Saint Louis';
    public static final String OKLAHOMA = 'Oklahoma';
    public static final String KANSAS_CITY = 'Kansas City';
    public static final String DENVER = 'Denver';
    public static final String MIDWEST_INDUSTRIAL_BUILDERS = 'Midwest Industrial Builders';

    public static Map<String, Integer> activityTypeCount = new Map<String, Integer>();
    public static Map<String, Integer> activityTypeCountLast1Month = new Map<String, Integer>();
    public static Map<String, Integer> activityTypeCountLast3Month = new Map<String, Integer>();
    public static Map<String, Integer> activityTypeCountLast6Month = new Map<String, Integer>();
    public static Map<String, Integer> activityTypeCountLast12Month = new Map<String, Integer>(); 

    public class applicationException extends Exception {}

    public SalesActivityCtrl() {

    }

    public static List<User> getAllSalesRep(){
        
        Set<String> setOfficeLocation = new Set<String>();
        setOfficeLocation.add(SAINT_LOUIS);
        setOfficeLocation.add(OKLAHOMA);
        setOfficeLocation.add(KANSAS_CITY);
        setOfficeLocation.add(DENVER);
        setOfficeLocation.add(MIDWEST_INDUSTRIAL_BUILDERS);
        
        List<User> lstUsers = [Select Id,Name,Office_Location__c,IsActive  From User 
                                WHERE Office_Location__c IN :setOfficeLocation
                                AND IsActive = true
                                ORDER BY Office_Location__c ASC];
        return lstUsers;
        
    } 

    public static List<User> getHouseUserDetails(){
        
        Set<Id> setHouseUserId = new Set<Id>();
        setHouseUserId.add('00561000000gZ6D');
        setHouseUserId.add('00561000000gZ6I');
        setHouseUserId.add('00561000000gZ68');
        setHouseUserId.add('00561000000gZ3T');
        
        List<User> lstHouseUser = [Select Id,Name 
                                    From User
                                    WHERE Id IN: setHouseUserId];
                            
        
        return lstHouseUser;
    }

    public static List<User> getUsersByLocations(String officeLocation){
        List<User> lstUsers = [Select Id,Name From User 
                                WHERE Office_Location__c = :officeLocation
                                ORDER BY Name ASC];
        return lstUsers;
    }

    @AuraEnabled(cacheable=true)
    public Static Map<String, String> buildUserHierarchy(Id salesRep){
        
        Map<String,String> userDetails = new Map<String, String>();
        String secondLevel = '____';
        String thirdLevel = '________';
        
        List<SelectOption> lstHierarchyUsers = new List<SelectOption>();
        
        User currentUser = [SELECT Id,
                                    Name,
                                    Is_Manager__c, 
                                    Is_Director__c, 
                                    Office_Location__c,
                                    has_house_Account_Access__c 
                            FROM  User
                            WHERE Id = :salesRep];
        
        if(currentUser.Is_Manager__c == false && currentUser.Is_Director__c == false){
            userDetails.put(currentUser.Id, currentUser.Name);
            lstHierarchyUsers.add(new SelectOption(currentUser.Id,currentUser.Name));    
        }else if(currentUser.Is_Director__c){
            userDetails.put('Midwest Machinery','Master Report');
            lstHierarchyUsers.add(new SelectOption('Midwest Machinery','Master Report'));         
            
            List<User> lstUsers = getAllSalesRep();
            String currentOfficeLocation = '';
            
            for(User u : lstUsers){
                if(u.Office_Location__c != currentOfficeLocation){
                    currentOfficeLocation = u.Office_Location__c;
                    userDetails.put(u.Office_Location__c, secondLevel + u.Office_Location__c);
                    userDetails.put(u.Id, thirdLevel + u.Name);

                    lstHierarchyUsers.add(new SelectOption(u.Office_Location__c,secondLevel + u.Office_Location__c)); 
                    lstHierarchyUsers.add(new SelectOption(u.Id,thirdLevel + u.Name));  
                }else{
                    userDetails.put(u.Id, thirdLevel + u.Name);
                    lstHierarchyUsers.add(new SelectOption(u.Id,thirdLevel + u.Name));   
                }
            }
        }else if(currentUser.Is_Manager__c){
            userDetails.put(currentUser.Office_Location__c, currentUser.Office_Location__c);

            lstHierarchyUsers.add(new SelectOption(currentUser.Office_Location__c,currentUser.Office_Location__c));   
            
            List<User> lstUsers = getUsersByLocations(currentUser.Office_Location__c);
            
            for(User u : lstUsers){
                userDetails.put(u.Id, secondLevel + u.Name);

                lstHierarchyUsers.add(new SelectOption(u.Id,secondLevel + u.Name));
            }
        }
        if(currentUser.has_house_Account_Access__c){
            List<User> lstUsers = getHouseUserDetails();
            
            for(User u : lstUsers){
                userDetails.put(u.Id,secondLevel + u.Name);

                lstHierarchyUsers.add(new SelectOption(u.Id,secondLevel + u.Name));
            }
            
        }
        
        return userDetails;
    }

    @AuraEnabled(cacheable=true)
    public static List<salesActivityResponse> buildSalesActivityWrapper(String salesRep){
        system.debug('buildSalesActivityWrapper: '+salesRep);
        List<salesActivityResponse> responseWrapperList = new List<salesActivityResponse>();
        List<LogACall__c> activitiesOfSalesRep = new List<LogACall__c>();
        Map<String, Decimal> goalsForEachActivity = new Map<String, Decimal>(); 
        DateTime lastYearDate = system.now().addMonths(-12);
        // in dashoboard for particular user like brian, Bob log call
        if (salesRep == 'Midwest Machinery') {
            activitiesOfSalesRep = [SELECT Id,
                                            Assigned_To__c,
                                            Type_of_Call__c,
                                            CreatedDate,
                                            Event_Date__c
                                    FROM LogACall__c
                                    WHERE (Assigned_To__r.Office_Location__c =:SAINT_LOUIS
                                           OR Assigned_To__r.Office_Location__c =:OKLAHOMA
                                           OR Assigned_To__r.Office_Location__c =:KANSAS_CITY
                                           OR Assigned_To__r.Office_Location__c =:DENVER
                                           OR Assigned_To__r.Office_Location__c =:MIDWEST_INDUSTRIAL_BUILDERS)
                                    AND CreatedDate >= :lastYearDate];

         System.debug('selected sales rep is midwest' +activitiesOfSalesRep);   

        } else if (salesRep == SAINT_LOUIS 
                    || salesRep == OKLAHOMA 
                    || salesRep == KANSAS_CITY 
                    || salesRep == DENVER
                    || salesRep == MIDWEST_INDUSTRIAL_BUILDERS) {
            
         activitiesOfSalesRep = [SELECT Id,
                                        Assigned_To__c,
                                        Type_of_Call__c,
                                        CreatedDate,
                                        Event_Date__c
                                FROM LogACall__c
                                WHERE Assigned_To__r.Office_Location__c =:salesRep
                                 AND CreatedDate >= :lastYearDate];

         System.debug('selected sales rep else if  saint louis part' +activitiesOfSalesRep);                                                             
        } else {
            activitiesOfSalesRep = [SELECT Id,
                                    Assigned_To__c,
                                    Type_of_Call__c,
                                    CreatedDate,
                                    Event_Date__c
                                FROM LogACall__c
                                WHERE Assigned_To__c =:salesRep
                                AND CreatedDate >= :lastYearDate];  
        }             
        system.debug('activitiesOf salesRep' + activitiesOfSalesRep );                  
        constructActivityContMaps(activitiesOfSalesRep);
        system.debug('activity type count' + activityTypeCount);
        SalesActivityGoal__c activity = new SalesActivityGoal__c();
        try {
            // in dashoboard for particular user like brian, Bob sales Activity
            if(salesRep.startsWith('005')){
                activity  = [SELECT Id,Name,
                                ClientOfficeVisit__c,
                                EndUserVisit__c,
                                Entertainment__c,
                                FactoryVisitLocal__c,
                                FactoryVisitTravel__c,
                                HappyHour__c,
                                Meal__c,
                                SalesRep__c,
                                SiteVisit__c,
                                Training__c,
                                Year__c
                            FROM SalesActivityGoal__c
                            WHERE SalesRep__c = :salesRep
                            AND Year__c = :String.valueOf(system.now().year())
                            LIMIT 1];
            }else{
                //master report ex:- Saint Louis for sales Activity in dashboard
                activity  = [SELECT Id,Name,
                                ClientOfficeVisit__c,
                                EndUserVisit__c,
                                Entertainment__c,
                                FactoryVisitLocal__c,
                                FactoryVisitTravel__c,
                                HappyHour__c,
                                Meal__c,
                                SalesRep__c,
                                SiteVisit__c,
                                Training__c,
                                Year__c
                            FROM SalesActivityGoal__c
                            WHERE Master_Report__c = :salesRep  //  SalesRep__c = :salesRep
                            AND Year__c = :String.valueOf(system.now().year())
                            LIMIT 1];
            }
                
                system.debug('Sales activity' +activity);
        } catch(Exception e) {
            throw new applicationException('sales activity goals are not set for selected user: ' + salesRep);
        }

        goalsForEachActivity.put(ACTIVITY_CLIENTOFFICE_VISIT, activity.ClientOfficeVisit__c);
        goalsForEachActivity.put(ACTIVITY_ENDUSER_VISIT, activity.EndUserVisit__c);
        goalsForEachActivity.put(ACTIVITY_ENTERTAINMENT, activity.Entertainment__c);
        goalsForEachActivity.put(ACTIVITY_FACTORY_VISIT_LOCAL, activity.FactoryVisitLocal__c);
        goalsForEachActivity.put(ACTIVITY_FACTORY_VISIT_TRAVEL, activity.FactoryVisitTravel__c);
        goalsForEachActivity.put(ACTIVITY_HAPPY_HOUR, activity.HappyHour__c);
        goalsForEachActivity.put(ACTIVITY_Meal, activity.Meal__c);
        goalsForEachActivity.put(ACTIVITY_SITE_VISIT, activity.SiteVisit__c);
        goalsForEachActivity.put(ACTIVITY_TRAININ, activity.Training__c);
        salesActivityResponse totalLine = new salesActivityResponse();
        totalLine.activityName = 'Sales Activity Score';
        for (String activityType : goalsForEachActivity.keySet()) {
    
            decimal totalGoal = goalsForEachActivity.containsKey(activityType) ? goalsForEachActivity.get(activityType) : 0;
            
            salesActivityResponse resp = new salesActivityResponse();
            resp.activityGoal = Integer.valueOf(totalGoal);
            totalLine.activityGoal += resp.activityGoal;

            resp.activityName = activityType;
            //.round(System.RoundingMode.DOWN));
            resp.ytdGoal = (Integer.valueOf(System.today().dayOfYear()) * totalGoal) / 365;
            resp.ytdGoal = resp.ytdGoal.setScale(1);
            totalLine.ytdGoal += resp.ytdGoal;
            
            //resp.ytdGoal = resp.ytdGoal.round(System.RoundingMode.DOWN);
            system.debug('resp.ytdGoal='+resp.ytdGoal);
            if (activityTypeCount.containsKey(activityType) && activityTypeCount.get(activityType) > 0) {
                resp.ytdActual = activityTypeCount.get(activityType);
                totalLine.ytdActual += resp.ytdActual;
                if (activityType == ACTIVITY_ENTERTAINMENT) {
                    resp.points = ActivityGoalPoints__c.getValues( 'Entertain (Hpy Hr, Glf, Gms)').Point__c * resp.ytdActual;
                } else {
                    system.debug('activity type: '+ activityType);
                    system.debug('resp.ytdActual: '+ resp.ytdActual);
                    system.debug('Point__c: '+ ActivityGoalPoints__c.getValues(activityType).Point__c);

                    resp.points = ActivityGoalPoints__c.getValues(activityType).Point__c * resp.ytdActual;
                }
                totalLine.points +=  resp.points;
                
                if(resp.ytdActual > 0 && resp.ytdGoal > 0) {
                    //Decimal.valueOf(String.valueOf(resp.ytdActual));
                    resp.PercentageOfYtdGoal = resp.ytdActual / resp.ytdGoal;
                    resp.PercentageOfYtdGoal = resp.PercentageOfYtdGoal.setScale(2);
                    totalLine.PercentageOfYtdGoal += resp.PercentageOfYtdGoal;
                } else {
                    resp.PercentageOfYtdGoal = 0;
                }
                
                resp.lastOneMotnh = activityTypeCountLast1Month.containsKey(activityType) ? activityTypeCountLast1Month.get(activityType) : 0;
                totalLine.lastOneMotnh += resp.lastOneMotnh;
                
                resp.lastThreeMotnh = activityTypeCountLast3Month.containsKey(activityType) ? activityTypeCountLast3Month.get(activityType) : 0;
                totalLine.lastThreeMotnh += resp.lastThreeMotnh;

                resp.lastSixMotnh = activityTypeCountLast6Month.containsKey(activityType) ? activityTypeCountLast6Month.get(activityType) : 0;
                totalLine.lastSixMotnh += resp.lastSixMotnh;

                resp.lastTwelveMonth = activityTypeCountLast12Month.containsKey(activityType) ? activityTypeCountLast12Month.get(activityType) : 0;
                totalLine.lastTwelveMonth += resp.lastTwelveMonth;
            }
            responseWrapperList.add(resp);
        }
        responseWrapperList.add(totalLine);
        return responseWrapperList;

    }

    public static void constructActivityContMaps(List<LogACall__c> activities) {

        for(LogACall__c activity : activities) {
            if (activity.Event_Date__c.Year() == System.now().year()) {
                if (!activityTypeCount.containsKey(activity.Type_of_Call__c)) {
                    activityTypeCount.put(activity.Type_of_Call__c, 1);
                } else {
                    activityTypeCount.put(activity.Type_of_Call__c, 
                                    activityTypeCount.get(activity.Type_of_Call__c) + 1);
                }

            }

            // activities for last month
            if(activity.Event_Date__c < system.now() 
                && activity.Event_Date__c > system.now().addMonths(-1)) {

                    if(activityTypeCountLast1Month.containsKey(activity.Type_of_Call__c)) {
                        
                        activityTypeCountLast1Month.put(activity.Type_of_Call__c, 
                            activityTypeCountLast1Month.get(activity.Type_of_Call__c) + 1);
                    } else {
                        activityTypeCountLast1Month.put(activity.Type_of_Call__c, 1);
                    }

            }

            // activities for last 3 month
            if(activity.Event_Date__c < system.now() 
                && activity.Event_Date__c > system.now().addMonths(-3)) {
        
                if(activityTypeCountLast3Month.containsKey(activity.Type_of_Call__c)) {
                    
                    activityTypeCountLast3Month.put(activity.Type_of_Call__c, 
                        activityTypeCountLast3Month.get(activity.Type_of_Call__c) + 1);
                } else {
                    activityTypeCountLast3Month.put(activity.Type_of_Call__c, 1);
                }
        
            }
            // activities for last 6 month
            if(activity.Event_Date__c < system.now() 
                && activity.Event_Date__c > system.now().addMonths(-6)) {
        
                if(activityTypeCountLast6Month.containsKey(activity.Type_of_Call__c)) {
                    
                    activityTypeCountLast6Month.put(activity.Type_of_Call__c, 
                        activityTypeCountLast6Month.get(activity.Type_of_Call__c) + 1);
                } else {
                    activityTypeCountLast6Month.put(activity.Type_of_Call__c, 1);
                }
        
            }
            // activities for last 12 month
            if(activity.Event_Date__c < system.now() 
                && activity.Event_Date__c > system.now().addMonths(-12)) {
        
                if(activityTypeCountLast12Month.containsKey(activity.Type_of_Call__c)) {
                    
                    activityTypeCountLast12Month.put(activity.Type_of_Call__c, 
                        activityTypeCountLast12Month.get(activity.Type_of_Call__c) + 1);
                } else {
                    activityTypeCountLast12Month.put(activity.Type_of_Call__c, 1);
                }
        
            }

        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<SalesRep> getRankings() {

        List<SalesRep> lstSalesRepNames = new List<SalesRep>();

        for (AggregateResult result : [SELECT Assigned_To__r.Name, SUM(Points__c) totalPoints 
                                        FROM LogACall__c 
                                        WHERE CreatedDate = THIS_YEAR
                                        AND Assigned_To__c != NULL
                                        AND Type_of_Call__c != 'Expense Only'
                                        GROUP BY Assigned_To__r.Name 
                                        ORDER BY SUM(Points__c) DESC 
                                        LIMIT 5]) {
            System.debug('###-111--'+result);
            System.debug('###--222-'+JSON.serializePretty(result));   
            lstSalesRepNames.add(new SalesRep((String)result.get('Name')));
        }

        return lstSalesRepNames;
    }
    public class salesActivityResponse{
        @AuraEnabled
        public String activityName{get;set;}
        @AuraEnabled
        public Integer activityGoal{get;set;}
        @AuraEnabled
        public Decimal ytdGoal{get;set;}
        @AuraEnabled
        public Decimal ytdActual{get;set;}
        @AuraEnabled
        public Decimal PercentageOfYtdGoal{get;set;}
        @AuraEnabled
        public Decimal lastOneMotnh{get;set;}
        @AuraEnabled
        public Decimal lastThreeMotnh{get;set;}
        @AuraEnabled
        public Decimal lastSixMotnh{get;set;}
        @AuraEnabled
        public Decimal lastTwelveMonth {get;set;}
        @AuraEnabled
        public Decimal points {get;set;}
        
        public salesActivityResponse(){
            //salesActivitySO = new SalesActivityGoal__c();
            activityGoal = 0;
            activityName = '';
            PercentageOfYtdGoal = 0;
            ytdGoal = 0;
            lastOneMotnh = 0;
            lastTwelveMonth = 0;
            lastSixMotnh = 0;
            lastThreeMotnh = 0;
            ytdActual = 0;
            points = 0;
            
        }
        
    }

    public with sharing class SalesRep {
        @AuraEnabled public String SalesRepName {get;set;}

        public SalesRep(String salesRepName) {
            this.SalesRepName = salesRepName;
        }
    }
}