force-app/main/default/objects/ActivityGoalPoints__c/ActivityGoalPoints__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Activity Goal Points</label>
</CustomObject>

force-app/main/default/objects/ActivityGoalPoints__c/fields/Point__c.field-meta.xml
<CustomField>
    <fullName>Point__c</fullName>
    <label>Point</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogACall__c/LogACall__c.object-meta.xml
<CustomObject>
    <label>Log A Call</label>
    <nameField>
        <displayFormat>Call-{00000}</displayFormat>
        <label>Log A Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogACall__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LogCalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Type_of_Call__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Call__c</fullName>
    <label>Type of Call</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client Office Visit</fullName>
            </value>
            <value>
                <fullName>End User Visit</fullName>
            </value>
            <value>
                <fullName>Entertain (Hpy Hr, Glf, Gms)</fullName>
            </value>
            <value>
                <fullName>Expense Only</fullName>
            </value>
            <value>
                <fullName>Factory Visit (Travel)</fullName>
            </value>
            <value>
                <fullName>Industry Event (Ashrae etc.)</fullName>
            </value>
            <value>
                <fullName>Meal</fullName>
            </value>
            <value>
                <fullName>Site Visit (Project Related)</fullName>
            </value>
            <value>
                <fullName>Training (L-N-L, Seminar)</fullName>
            </value>
            <value>
                <fullName>Factory Visit (Local)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/SalesActivityGoal__c.object-meta.xml
<CustomObject>
    <label>Sales Activity Goal</label>
    <nameField>
        <displayFormat>SG-{00000}</displayFormat>
        <label>Sales Activity Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Activity Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesActivityGoal__c/fields/ClientOfficeVisit__c.field-meta.xml
<CustomField>
    <fullName>ClientOfficeVisit__c</fullName>
    <label>Client Office Visit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/EndUserVisit__c.field-meta.xml
<CustomField>
    <fullName>EndUserVisit__c</fullName>
    <label>End User Visit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Entertainment__c.field-meta.xml
<CustomField>
    <fullName>Entertainment__c</fullName>
    <label>Entertainment (Golf, Games, Etc.)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/FactoryVisitLocal__c.field-meta.xml
<CustomField>
    <fullName>FactoryVisitLocal__c</fullName>
    <label>Factory Visit (Local)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/FactoryVisitTravel__c.field-meta.xml
<CustomField>
    <fullName>FactoryVisitTravel__c</fullName>
    <label>Factory Visit (Travel)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/HappyHour__c.field-meta.xml
<CustomField>
    <fullName>HappyHour__c</fullName>
    <label>Happy Hour - Cocktails</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Meal__c.field-meta.xml
<CustomField>
    <fullName>Meal__c</fullName>
    <label>Meal</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/SalesRep__c.field-meta.xml
<CustomField>
    <fullName>SalesRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Activity_Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/SiteVisit__c.field-meta.xml
<CustomField>
    <fullName>SiteVisit__c</fullName>
    <label>Site Visit (Project Related)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <label>Training (L-N-N, Seminar)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/has_house_Account_Access__c.field-meta.xml
<CustomField>
    <fullName>has_house_Account_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <label>has house Account Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Is_Director__c.field-meta.xml
<CustomField>
    <fullName>Is_Director__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Director?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Is_Manager__c.field-meta.xml
<CustomField>
    <fullName>Is_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Manager?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saint Louis</fullName>
            </value>
            <value>
                <fullName>Oklahoma</fullName>
            </value>
            <value>
                <fullName>Kansas City</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesActivityCtrlTest.cls
@isTest
public with sharing class SalesActivityCtrlTest 
{
    
    @testSetup static void setup() 
    {
        //create a SalesActivityGoal
        SalesActivityGoal__c chartTotlaListTest = new  SalesActivityGoal__c();
        //chartTotlaListTest.Name = 'Test SalesActivity Goal';
        chartTotlaListTest.ClientOfficeVisit__c = 15;
        chartTotlaListTest.EndUserVisit__c = 12;
        chartTotlaListTest.Entertainment__c = 10;
        chartTotlaListTest.FactoryVisitLocal__c = 16;
        chartTotlaListTest.FactoryVisitTravel__c = 18;
        chartTotlaListTest.HappyHour__c = 22; 
        chartTotlaListTest.Meal__c = 25;
        chartTotlaListTest.SiteVisit__c = 23;
        chartTotlaListTest.Training__c = 14;
        chartTotlaListTest.SalesRep__c = UserInfo.getUserId();
        chartTotlaListTest.Year__c = String.valueof(system.now().year());      

        insert chartTotlaListTest;
        System.debug('SalesActvityGoal new salesgoal : '+chartTotlaListTest);

        final String ACTIVITY_CLIENTOFFICE_VISIT = 'Client Office Visit';
        final String ACTIVITY_ENDUSER_VISIT = 'End User Visit';
        final String ACTIVITY_ENTERTAINMENT = 'Entertain (Hpy Hr, Glf, Gms)';
        final String ACTIVITY_HAPPY_HOUR = 'Industry Event (Ashrae etc.)';
        final String ACTIVITY_Meal = 'Meal';
        List<String> typeOfCalls = new List<String>{ACTIVITY_CLIENTOFFICE_VISIT, ACTIVITY_ENDUSER_VISIT, ACTIVITY_ENTERTAINMENT, ACTIVITY_HAPPY_HOUR, ACTIVITY_Meal};

        // create a logACall for SalesActivityGoal
        List<LogACall__c> listofLogACalls = new List<LogACall__c>();
        for (Integer i=0; i<20; i++){

            LogACall__c  testLogcall = new LogACall__c();
            testLogcall.Type_of_Call__c = typeOfCalls[Math.mod(i,5)];
            testLogcall.Assigned_To__c = UserInfo.getUserId();
            testLogcall.CreatedDate = system.now().addMonths(-(Math.mod(i,10)));
            testLogcall.Event_Date__c = system.now().addMonths(-(Math.mod(i,10))).date();
            listofLogACalls.add(testLogcall);

            System.debug('Type of call: '+testLogcall.Type_of_Call__c);
            System.debug('CreateDate: '+testLogcall.CreatedDate);
            System.debug('EventDate: '+testLogcall.CreatedDate);

        }
        // Batch query inserting 20 records at a time of logACall
        insert listofLogACalls;

        //create a ActivityGoalPoints/ points
        ActivityGoalPoints__c clientOfficeGoalPoint = new ActivityGoalPoints__c();
        clientOfficeGoalPoint.Name = ACTIVITY_CLIENTOFFICE_VISIT ;
        clientOfficeGoalPoint.Point__c = 1;
        insert clientOfficeGoalPoint;

        ActivityGoalPoints__c entertainmentGoalPoint = new ActivityGoalPoints__c();
        entertainmentGoalPoint.Name = ACTIVITY_ENTERTAINMENT ;
        entertainmentGoalPoint.Point__c = 3;
        insert entertainmentGoalPoint;

        ActivityGoalPoints__c endUserVisitGoalPoint = new ActivityGoalPoints__c();
        endUserVisitGoalPoint.Name = ACTIVITY_ENDUSER_VISIT ;
        endUserVisitGoalPoint.Point__c = 1;
        insert endUserVisitGoalPoint;

        ActivityGoalPoints__c happyHourGoalPoints = new ActivityGoalPoints__c();
        happyHourGoalPoints.Name = ACTIVITY_HAPPY_HOUR ;
        happyHourGoalPoints.Point__c = 2;
        insert happyHourGoalPoints;

        ActivityGoalPoints__c mealGoalPoints = new ActivityGoalPoints__c();
        mealGoalPoints.Name = ACTIVITY_Meal ;
        mealGoalPoints.Point__c = 2;
        insert mealGoalPoints;
                  
        
    } 
    

    @isTest static void testSalesActivity()
    {
        SalesActivityCtrl.buildSalesActivityWrapper(UserInfo.getUserId());
    }

    @isTest static void testGetRankings()
    {
        SalesActivityCtrl.getRankings();
    }
    @isTest static void getAllSalesRep()
    {
        SalesActivityCtrl SalesActivityTest = new SalesActivityCtrl();
        // because of query not working in setup method
        Profile p = [select id from profile where name='Standard User']; 
        UserRole ur = [select Id from UserRole LIMIT 1];

        User userlst = new User(alias = 'standt', email='standarduser@kwutang.demo', 
                                emailencodingkey='UTF-8', lastname='Testing1', firstname='Testing', 
                                languagelocalekey='en_US', 
                                localesidkey='en_US',
                                timezonesidkey='America/Los_Angeles', 
                                ProfileId = p.Id,
                                UserRoleId= ur.Id,
                                Office_Location__c = 'Saint Louis',
                                username='standarduser@kwutang.demo1');   
        insert userlst;

        system.debug('new user added:'  +userlst);
        userlst.Is_Manager__c = false;
        userlst.Is_Director__c= false;
        userlst.has_house_Account_Access__c= false;
        update userlst;

        SalesActivityCtrl.getAllSalesRep();
        SalesActivityCtrl.getHouseUserDetails();
        SalesActivityCtrl.getUsersByLocations(userlst.Office_Location__c);
        SalesActivityCtrl.buildUserHierarchy(UserInfo.getUserId());
    }

}