force-app/main/default/objects/ActivityGoalPoints__c/ActivityGoalPoints__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Activity Goal Points</label>
</CustomObject>

force-app/main/default/objects/ActivityGoalPoints__c/fields/Point__c.field-meta.xml
<CustomField>
    <fullName>Point__c</fullName>
    <label>Point</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogACall__c/LogACall__c.object-meta.xml
<CustomObject>
    <label>Log A Call</label>
    <nameField>
        <displayFormat>Call-{00000}</displayFormat>
        <label>Log A Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogACall__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LogCalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Type_of_Call__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Call__c</fullName>
    <label>Type of Call</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client Office Visit</fullName>
            </value>
            <value>
                <fullName>End User Visit</fullName>
            </value>
            <value>
                <fullName>Entertain (Hpy Hr, Glf, Gms)</fullName>
            </value>
            <value>
                <fullName>Expense Only</fullName>
            </value>
            <value>
                <fullName>Factory Visit (Travel)</fullName>
            </value>
            <value>
                <fullName>Industry Event (Ashrae etc.)</fullName>
            </value>
            <value>
                <fullName>Meal</fullName>
            </value>
            <value>
                <fullName>Site Visit (Project Related)</fullName>
            </value>
            <value>
                <fullName>Training (L-N-L, Seminar)</fullName>
            </value>
            <value>
                <fullName>Factory Visit (Local)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <inlineHelpText>Which Midwest Group office is this for?</inlineHelpText>
    <label>Midwest Group Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Midwest Machinery STL</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery KC</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery OK</fullName>
            </value>
            <value>
                <fullName>Engineered Products</fullName>
            </value>
            <value>
                <fullName>MaRRS</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
            <value>
                <fullName>Spark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/Sales_Rep_Goal__c.object-meta.xml
<CustomObject>
    <label>Sales Rep Goal</label>
    <nameField>
        <displayFormat>Goal - {00000}</displayFormat>
        <label>Sales Rep Goals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Direct_Sales_Goal__c.field-meta.xml
<CustomField>
    <fullName>Direct_Sales_Goal__c</fullName>
    <label>Direct Sales Goal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Direct_Sales_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Direct_Sales_Percentage__c</fullName>
    <description>in %</description>
    <inlineHelpText>in %</inlineHelpText>
    <label>Direct Sales Margin %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Margin_Goal__c.field-meta.xml
<CustomField>
    <fullName>Margin_Goal__c</fullName>
    <label>Margin Goal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Master_Report__c.field-meta.xml
<CustomField>
    <fullName>Master_Report__c</fullName>
    <label>Master Report?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Midwest Machinery</fullName>
            </value>
            <value>
                <fullName>Saint Louis</fullName>
            </value>
            <value>
                <fullName>Oklahoma</fullName>
            </value>
            <value>
                <fullName>Kansas City</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Resell_Sales_Goal__c.field-meta.xml
<CustomField>
    <fullName>Resell_Sales_Goal__c</fullName>
    <label>Resell Sales Goal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Revenue_Goal__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Goal__c</fullName>
    <label>Revenue Goal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Sales_Margin_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Sales_Margin_Percentage__c</fullName>
    <inlineHelpText>In %</inlineHelpText>
    <label>Sales Margin %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/Sales_Representative__c.object-meta.xml
<CustomObject>
    <label>Sales Representative</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sales Representative Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Representative__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepresentatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/SalesActivityGoal__c.object-meta.xml
<CustomObject>
    <label>Sales Activity Goal</label>
    <nameField>
        <displayFormat>SG-{00000}</displayFormat>
        <label>Sales Activity Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Activity Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesActivityGoal__c/fields/ClientOfficeVisit__c.field-meta.xml
<CustomField>
    <fullName>ClientOfficeVisit__c</fullName>
    <label>Client Office Visit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/EndUserVisit__c.field-meta.xml
<CustomField>
    <fullName>EndUserVisit__c</fullName>
    <label>End User Visit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Entertainment__c.field-meta.xml
<CustomField>
    <fullName>Entertainment__c</fullName>
    <label>Entertainment (Golf, Games, Etc.)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/FactoryVisitLocal__c.field-meta.xml
<CustomField>
    <fullName>FactoryVisitLocal__c</fullName>
    <label>Factory Visit (Local)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/FactoryVisitTravel__c.field-meta.xml
<CustomField>
    <fullName>FactoryVisitTravel__c</fullName>
    <label>Factory Visit (Travel)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/HappyHour__c.field-meta.xml
<CustomField>
    <fullName>HappyHour__c</fullName>
    <label>Happy Hour - Cocktails</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Master_Report__c.field-meta.xml
<CustomField>
    <fullName>Master_Report__c</fullName>
    <label>Master Report?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Midwest Machinery</fullName>
            </value>
            <value>
                <fullName>Saint Louis</fullName>
            </value>
            <value>
                <fullName>Oklahoma</fullName>
            </value>
            <value>
                <fullName>Kansas City</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Meal__c.field-meta.xml
<CustomField>
    <fullName>Meal__c</fullName>
    <label>Meal</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/SalesRep__c.field-meta.xml
<CustomField>
    <fullName>SalesRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Activity_Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/SiteVisit__c.field-meta.xml
<CustomField>
    <fullName>SiteVisit__c</fullName>
    <label>Site Visit (Project Related)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <label>Training (L-N-N, Seminar)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GoalChartControllerTest.cls
@isTest
public with sharing class GoalChartControllerTest 
{

    @testSetup static void setup() {
        // point__c calculation
        final String ACTIVITY_CLIENTOFFICE_VISIT = 'Client Office Visit';
        final String ACTIVITY_ENDUSER_VISIT = 'End User Visit';
        final String ACTIVITY_ENTERTAINMENT = 'Entertainment (Golf, Games)';
        final String ACTIVITY_HAPPY_HOUR = 'Happy Hour - Cocktails';
        final String ACTIVITY_Meal = 'Meal';

        ActivityGoalPoints__c clientOfficeGoalPoint = new ActivityGoalPoints__c();
        clientOfficeGoalPoint.Name = ACTIVITY_CLIENTOFFICE_VISIT ;
        clientOfficeGoalPoint.Point__c = 1;
        insert clientOfficeGoalPoint;

        ActivityGoalPoints__c entertainmentGoalPoint = new ActivityGoalPoints__c();
        entertainmentGoalPoint.Name = ACTIVITY_ENTERTAINMENT ;
        entertainmentGoalPoint.Point__c = 3;
        insert entertainmentGoalPoint;

        ActivityGoalPoints__c endUserVisitGoalPoint = new ActivityGoalPoints__c();
        endUserVisitGoalPoint.Name = ACTIVITY_ENDUSER_VISIT ;
        endUserVisitGoalPoint.Point__c = 1;
        insert endUserVisitGoalPoint;

        ActivityGoalPoints__c happyHourGoalPoints = new ActivityGoalPoints__c();
        happyHourGoalPoints.Name = ACTIVITY_HAPPY_HOUR ;
        happyHourGoalPoints.Point__c = 2;
        insert happyHourGoalPoints;

        ActivityGoalPoints__c mealGoalPoints = new ActivityGoalPoints__c();
        mealGoalPoints.Name = ACTIVITY_Meal ;
        mealGoalPoints.Point__c = 2;
        insert mealGoalPoints;

        //Create common test data in setup method 
        //ActivityChartNumbers --> gauge chart
        SalesActivityGoal__c chartTotlaListTest = new  SalesActivityGoal__c();
        //chartTotlaListTest.Name = 'Test Goal';
        chartTotlaListTest.ClientOfficeVisit__c = 15;
        chartTotlaListTest.EndUserVisit__c = 12;
        chartTotlaListTest.Entertainment__c = 10;
        chartTotlaListTest.FactoryVisitLocal__c = 16;
        chartTotlaListTest.FactoryVisitTravel__c = 18;
        chartTotlaListTest.HappyHour__c = 22; 
        chartTotlaListTest.Meal__c = 25;
        chartTotlaListTest.SiteVisit__c = 23;
        chartTotlaListTest.Training__c = 14;
        // chartTotlaListTest.SalesRep__c = UserInfo.getUserId();
        chartTotlaListTest.Year__c = String.valueof(system.now().year());
        chartTotlaListTest.Master_Report__c = 'Saint Louis';

        insert chartTotlaListTest;
        System.debug('Sales activity goal inserted: '+chartTotlaListTest);

        // create a logACall for SalesActivityGoal
    
        LogACall__c  testLogcall = new LogACall__c();
        testLogcall.Type_of_Call__c = 'Meal';
        testLogcall.Assigned_To__c = UserInfo.getUserId();
        testLogcall.CreatedDate = system.now().addMonths(-1);
        testLogcall.Event_Date__c = Date.today();
        insert testLogcall;
        System.debug('LogAcall inserted: '+testLogcall);

        //MarginGoalChartNumbers--> gauge chart
        Sales_Rep_Goal__c  testsrGoal  = new Sales_Rep_Goal__c();
        testsrGoal.Margin_Goal__c = 1500000;
        testsrGoal.Revenue_Goal__c = 40000000;
        testsrGoal.Direct_Sales_Goal__c = 26000;
        testsrGoal.Resell_Sales_Goal__c = 20000;
        testsrGoal.Direct_Sales_Percentage__c = 20;
        testsrGoal.Sales_Margin_Percentage__c = 20;
        testsrGoal.Year__c = String.valueof(system.now().year());
        testsrGoal.Sales_Rep__c = UserInfo.getUserId();
        insert testsrGoal;
        System.debug('Sales rep goal inserted: '+testsrGoal);

       
       Account acctobj = new Account();
        acctobj.Name = 'Testing GoalChart';
        acctobj.AcctSeed__Accounting_Type__c = 'Customer';
        insert acctobj;
        System.debug('Account Inserted: '+acctobj);
        

        // calculate booked value
        Opportunity testobjOppo = new Opportunity();
        testobjOppo.Name = 'Test goals';
        testobjOppo.AccountId = acctobj.Id;
        testobjOppo.closeDate = Date.today();
        testobjOppo.StageName = 'Closed Won';
        testobjOppo.Project_Manager__c = UserInfo.getUserId();
        testobjOppo.Office__c = 'Midwest Machinery STL';
        insert testobjOppo;
        System.debug('Opportunity Inserted: '+testobjOppo);

        //getRevenueGoalChartNumbers--> gauge chart
        Sales_Representative__c testsalesEggSplits = new Sales_Representative__c(); // for this you need to create quote
        testsalesEggSplits.Commision__c = 100;
        testsalesEggSplits.Sales_Rep__c = UserInfo.getUserId(); 
        testsalesEggSplits.Opportunity__c = testobjOppo.Id;
        insert testsalesEggSplits;
        System.debug('Sales Representative Inserted: '+testsalesEggSplits);


    }
    
    @isTest static void loadMarginGoalData()
    {
        GoalChartController goalchart = new GoalChartController();
        //for office level and master report
        goalchart.loadMarginGoalData();
        goalchart.selectedUserId = 'Saint Louis';
        goalchart.loadMarginGoalData();
        goalchart.selectedUserId = 'Midwest Machinery';
        goalchart.loadMarginGoalData();


    }
    @isTest static void loadRevGoalChart()
    {
        GoalChartController goalchart = new GoalChartController();
        goalchart.loadRevGoalChart(); 
        goalchart.selectedUserId = 'Midwest Machinery';
        goalchart.loadRevGoalChart(); 
        goalchart.selectedUserId = 'Saint Louis';
        goalchart.loadRevGoalChart();
    }
    @isTest static void loadActivityGoalChart()
    {
        GoalChartController goalchart = new GoalChartController();
        goalchart.loadActivityGoalChart();
        goalchart.selectedUserId = 'Midwest Machinery';
        goalchart.loadActivityGoalChart();  
        goalchart.selectedUserId = 'Saint Louis';
        goalchart.loadActivityGoalChart();  
    }
    @isTest static void fetchSalesRepGoals()
    {
        GoalChartController goalchart = new GoalChartController();
        goalchart.fetchSalesRepGoals();  
    }
}