force-app/main/default/objects/Quote/fields/QuoteDocumentVersion__c.field-meta.xml
<CustomField>
    <fullName>QuoteDocumentVersion__c</fullName>
    <description>Version of quote document as pdf</description>
    <label>Quote Document Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ScopeDocumentVersion__c.field-meta.xml
<CustomField>
    <fullName>ScopeDocumentVersion__c</fullName>
    <description>Scope Document Latest Version Number</description>
    <label>Scope Document Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/SubmittalDocumentVersion__c.field-meta.xml
<CustomField>
    <fullName>SubmittalDocumentVersion__c</fullName>
    <description>Submittal Document Latest Version</description>
    <label>Submittal Document Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SharePointError__c/SharePointError__c.object-meta.xml
<CustomObject>
    <label>SharePoint Error</label>
    <nameField>
        <displayFormat>Error-{0000}</displayFormat>
        <label>SharePoint Folder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SharePoint Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SharePointError__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <label>Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SharePointError__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>SharePoint Errors</relationshipLabel>
    <relationshipName>SharePoint_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SharePointError__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Folder</fullName>
            </value>
            <value>
                <fullName>Quote File</fullName>
            </value>
            <value>
                <fullName>Scope File</fullName>
            </value>
            <value>
                <fullName>Submittal File</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateAttachmentInSharePoint.cls
global class CreateAttachmentInSharePoint {
     @future(callout=true)
     Public static void createFile(String folder,String file, Blob body,String docType, Id quoteId)
     {    
          HttpResponse response = new HttpResponse ();
          if (!Test.isRunningTest()) {
              SharePointRestServiceCallOut.authenticateSharePoint();
              response = SharePointRestServiceCallOut.createFile(folder,file,body);
              system.debug('CreateAttachmentInSharePoint response'+response);
              
          } else { 
              response.setBody('test message');
              response.setStatus('not found');
              response.setStatusCode(400);
          
          }    
          
        if (Test.isrunningtest() || response.getStatusCode() != 200) {
            Quote quoteSO = [SELECT Id, Name FROM Quote WHERE Id = :quoteId];
            String errorType;
            if (docType == 'Quote') {
                system.debug('create Quote failed');
                errorType = 'Quote File';
                Quote quoteToUpdate = [SELECT Id,QuoteDocumentVersion__c FROM Quote WHERE Id =: quoteId];
                Integer versionNumber = quoteToUpdate.QuoteDocumentVersion__c != null ? Integer.valueOf(quoteToUpdate.QuoteDocumentVersion__c) : 0;
                
                if (versionNumber > 0) {
                    versionNumber--;
                    quoteToUpdate.QuoteDocumentVersion__c = versionNumber;
                    update quoteToUpdate;
                }
            }
            
            if (docType == 'Scope') {
                system.debug('create Scope failed');
                errorType = 'Scope File';
                Quote quoteToUpdate = [SELECT Id,ScopeDocumentVersion__c FROM Quote WHERE Id =: quoteId];
                Integer versionNumber = quoteToUpdate.ScopeDocumentVersion__c != null ? Integer.valueOf(quoteToUpdate.ScopeDocumentVersion__c) : 0;
                
                if (versionNumber > 0) {
                    versionNumber--;
                    quoteToUpdate.ScopeDocumentVersion__c = versionNumber;
                    update quoteToUpdate;
                }
            }
            
            if (docType == 'Submittal') {
                system.debug('create Quote failed');
                errorType = 'Submittal File';

                Quote quoteToUpdate = [SELECT Id,SubmittalDocumentVersion__c FROM Quote WHERE Id =: quoteId];
                Integer versionNumber = quoteToUpdate.SubmittalDocumentVersion__c != null ? Integer.valueOf(quoteToUpdate.SubmittalDocumentVersion__c) : 0;
                
                if (versionNumber > 0 && quoteToUpdate != null) {
                    versionNumber--;
                    quoteToUpdate.SubmittalDocumentVersion__c = versionNumber;
                    update quoteToUpdate;
                }
            }

            // create error object
            SharePointError__c error = new SharePointError__c(
                Quote__c = quoteId,
                Error__c = 'File creation for quote is failed for '+ quoteSO.Name + 'reason is:'+ response.getBody() + '  path:'+folder,
                Status_Code__c = response.getStatusCode() +' Status:' + response.getStatus(),
                Type__c = errorType
            );
            insert error;
        }
     }
}