force-app/main/default/objects/LogACall__c/LogACall__c.object-meta.xml
<CustomObject>
    <label>Log A Call</label>
    <nameField>
        <displayFormat>Call-{00000}</displayFormat>
        <label>Log A Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogACall__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>LogCalls</relationshipLabel>
    <relationshipName>LogCalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Active_Financial_Quote__c.field-meta.xml
<CustomField>
    <fullName>Active_Financial_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Financial Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunities (Active Financial Quote)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MarginBooked__c.field-meta.xml
<CustomField>
    <fullName>MarginBooked__c</fullName>
    <description>From project financials tab MARGIN-(TOTAL)
TOTAL
And Even it is used for calculating (Total Margin (booked )) for Sales Result-DB</description>
    <formula>IF(ISBLANK(Active_Financial_Quote__r.Commissions_and_Rebates__c  ) ,0 , Active_Financial_Quote__r.Commissions_and_Rebates__c  ) + 
IF(ISBLANK( Active_Financial_Quote__r.Total_Buy_Resell_Margin__c ) ,0 , Active_Financial_Quote__r.Total_Buy_Resell_Margin__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Active_Financial_Quote__r.Commissions_and_Rebates__c  +   Active_Financial_Quote__r.Total_Buy_Resell_Margin__c</inlineHelpText>
    <label>MARGIN-TOTAL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalSalesBooked__c.field-meta.xml
<CustomField>
    <fullName>TotalSalesBooked__c</fullName>
    <description>From project financials tab SALES(TOTAL BOOKINGS)
TOTAL BOOKINGS
And Even it is used for calculating (Total Sales (Booked) ) for Sales Result-DB</description>
    <formula>IF(ISBLANK(Active_Financial_Quote__r.Total_Direct_Sell_Price__c), 0, Active_Financial_Quote__r.Total_Direct_Sell_Price__c) +  
IF(ISBLANK( Active_Financial_Quote__r.Total_Buy_Resell_Price__c ), 0, Active_Financial_Quote__r.Total_Buy_Resell_Price__c)</formula>
    <inlineHelpText>Active_Financial_Quote__r.Total_Direct_Sell_Price__c  + Active_Financial_Quote__r.Total_Buy_Resell_Price__c</inlineHelpText>
    <label>SALES-TOTAL BOOKINGS</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Active_Financial_Quote__c.field-meta.xml
<CustomField>
    <fullName>Active_Financial_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Financial Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/RemoveFromSalesResult__c.field-meta.xml
<CustomField>
    <fullName>RemoveFromSalesResult__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked data will be not consider for salesResult calculation</description>
    <label>Remove From SalesResult</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/Sales_Rep_Goal__c.object-meta.xml
<CustomObject>
    <label>Sales Rep Goal</label>
    <nameField>
        <displayFormat>Goal - {00000}</displayFormat>
        <label>Sales Rep Goals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Direct_Sales_Goal__c.field-meta.xml
<CustomField>
    <fullName>Direct_Sales_Goal__c</fullName>
    <label>Direct Sales Goal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Direct_Sales_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Direct_Sales_Percentage__c</fullName>
    <description>in %</description>
    <inlineHelpText>in %</inlineHelpText>
    <label>Direct Sales Margin %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Resell_Sales_Goal__c.field-meta.xml
<CustomField>
    <fullName>Resell_Sales_Goal__c</fullName>
    <label>Resell Sales Goal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Sales_Margin_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Sales_Margin_Percentage__c</fullName>
    <inlineHelpText>In %</inlineHelpText>
    <label>Sales Margin %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/Sales_Representative__c.object-meta.xml
<CustomObject>
    <label>Sales Representative</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sales Representative Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Representative__c/fields/MarginBooked__c.field-meta.xml
<CustomField>
    <fullName>MarginBooked__c</fullName>
    <description>The above formula is calculated from project Financials tab --&gt; Margin 
And we&apos;re using this formula field in Sales Result dashboard  for--&gt; Total Margin (Booked)
&amp; Total Margin is calculated in Opportunity field MarginBooked__c  &amp; only (* )multiply by split is done hear.</description>
    <formula>Opportunity__r.MarginBooked__c   *  Commision__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margin Booked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <formula>TEXT(Sales_Rep__r.Office_Location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Office Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Engineer Split</relationshipLabel>
    <relationshipName>SalesRepresentatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepresentatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/TotalSalesBooked__c.field-meta.xml
<CustomField>
    <fullName>TotalSalesBooked__c</fullName>
    <description>The above formula is calculated from project Financials tab --&gt; REVENUE
And we&apos;re using this formula field in Sales Result dashboard for--&gt; TotalSalesBooked
&amp; TotalSalesBooked is calculated in Opportunity field TotalSalesBooked__c &amp; only (* )multiply by split is done hear.</description>
    <formula>IF( ISNULL( Opportunity__r.TotalSalesBooked__c ) , 0 , Opportunity__r.TotalSalesBooked__c ) *  IF( ISNULL( Commision__c ) , 0 , Commision__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Sales Booked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/SalesActivityGoal__c.object-meta.xml
<CustomObject>
    <label>Sales Activity Goal</label>
    <nameField>
        <displayFormat>SG-{00000}</displayFormat>
        <label>Sales Activity Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Activity Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesActivityGoal__c/fields/SalesRep__c.field-meta.xml
<CustomField>
    <fullName>SalesRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Activity_Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>ClientOfficeVisit__c + EndUserVisit__c + Entertainment__c + FactoryVisitLocal__c + FactoryVisitTravel__c + HappyHour__c + Meal__c + SiteVisit__c + Training__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesActivityGoal__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saint Louis</fullName>
            </value>
            <value>
                <fullName>Oklahoma</fullName>
            </value>
            <value>
                <fullName>Kansas City</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GoalChartController.cls
/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 01-24-2024
 * @last modified by  : Nilesh Badrakiya
**/
public with sharing class GoalChartController {
    public chartResponse activityChart {get;set;}
    public chartResponse marginChart {get;set;}
    public chartResponse revenueChart {get;set;}
    public Boolean isError{get;set;}
    public static Sales_Rep_Goal__c srGoal;
    public String selectedUserId {get;set;}
    public String selectedUserName {get;set;}
    public static final String SAINT_LOUIS = 'Saint Louis';
    public static final String OKLAHOMA = 'Oklahoma';
    public static final String KANSAS_CITY = 'Kansas City';
    public static final String DENVER = 'Denver';
    public static final String MIDWEST_INDUSTRIAL_BUILDERS = 'Midwest Industrial Builders';
    
    public GoalChartController() {
        
        //srGoal = new Sales_Rep_Goal__c();
        selectedUserId = UserInfo.getUserId();
        
    }

    public void loadMarginGoalData () {
        chartResponse resp = new chartResponse();
        marginChart = new chartResponse();
        isError = false;
        ApexPages.getMessages().clear();
        fetchSalesRepGoals();
        system.debug('srGoal==>>'+srGoal);
        List<AggregateResult> lstMarginGoal;
        if (srGoal != null) {

            // to calulate MarginGoal Gauge Charts from 0 to endPoint
            decimal directCommissionMarginGoal = 0;
            if (srGoal.Direct_Sales_Goal__c > 0 && srGoal.Direct_Sales_Percentage__c > 0) {
                directCommissionMarginGoal = (srGoal.Direct_Sales_Goal__c * srGoal.Direct_Sales_Percentage__c)/100;
            }
            
            decimal buyResellMarginGoal = 0;
            if (srGoal.Resell_Sales_Goal__c > 0 && srGoal.Sales_Margin_Percentage__c > 0) {
                buyResellMarginGoal = (srGoal.Resell_Sales_Goal__c * srGoal.Sales_Margin_Percentage__c)/100;
            }
            if (buyResellMarginGoal > 0 || directCommissionMarginGoal > 0) {
                resp.chartTotalInDecimal = (buyResellMarginGoal + directCommissionMarginGoal).setScale(2);
            }
            if ( resp.chartTotalInDecimal == 0) {
                isError = true;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'please add the details of Sales Margin & Direct Sales Margin % in Sales rep goal for selected user:- ' +  srGoal.Name +  '<a href="/lightning/r/Sales_Rep_Goal__c/'+srGoal.Id+'/view" target="_blank"> Click Here</a>'));
                return;
            }
    
            // calculate Total Margin(booked) value
            if (selectedUserId == 'Midwest Machinery') {
                lstMarginGoal = [SELECT SUM(MarginBooked__c) marginbooked
                                   FROM Sales_Representative__c
                                   WHERE (Sales_Rep__r.Office_Location__c =: SAINT_LOUIS
                                                OR Sales_Rep__r.Office_Location__c =: OKLAHOMA 
                                                OR Sales_Rep__r.Office_Location__c =: KANSAS_CITY 
                                                OR Sales_Rep__r.Office_Location__c =: DENVER
                                                OR Sales_Rep__r.Office_Location__c =: MIDWEST_INDUSTRIAL_BUILDERS) 
                                    AND Opportunity__r.StageName = 'Closed Won' 
                                    AND Opportunity__r.Active_Financial_Quote__c != null 
                                    AND Opportunity__c != null
                                    AND Opportunity__r.Project__c != null
                                    AND Opportunity__r.Project__r.CreatedDate = THIS_YEAR
                                    AND Opportunity__r.Project__r.RemoveFromSalesResult__c != true];

            } else if (selectedUserId == SAINT_LOUIS 
                        || selectedUserId == OKLAHOMA 
                        || selectedUserId == KANSAS_CITY 
                        || selectedUserId == DENVER
                        || selectedUserId == MIDWEST_INDUSTRIAL_BUILDERS) {
                
                lstMarginGoal = [SELECT SUM(MarginBooked__c) marginbooked
                                  FROM Sales_Representative__c
                                  WHERE Sales_Rep__r.Office_Location__c = :selectedUserId 
                                  AND Opportunity__r.StageName = 'Closed Won' 
                                  AND Opportunity__r.Active_Financial_Quote__c != null 
                                  AND Opportunity__c != null
                                  AND Opportunity__r.Project__c != null
                                  AND Opportunity__r.Project__r.CreatedDate = THIS_YEAR
                                  AND Opportunity__r.Project__r.RemoveFromSalesResult__c != true];                        
                            
            } else {
                lstMarginGoal = [SELECT SUM(MarginBooked__c) marginbooked
                                  FROM Sales_Representative__c
                                  WHERE Sales_Rep__c = :selectedUserId
                                  AND Opportunity__r.StageName = 'Closed Won'
                                  AND Opportunity__r.Active_Financial_Quote__c != null 
                                  AND Opportunity__c != null
                                  AND Opportunity__r.Project__c != null
                                  AND Opportunity__r.Project__r.CreatedDate = THIS_YEAR
                                  AND Opportunity__r.Project__r.RemoveFromSalesResult__c != true];
                                                     
             system.debug('selected sales for particular user' +lstMarginGoal);   
            }
            if(!lstMarginGoal.isEmpty() && lstMarginGoal[0].get('marginbooked') != null){
                     resp.chartActualInDecimal = (decimal)lstMarginGoal[0].get('marginbooked');
            }
            marginChart = resp;    
            system.debug('marginChart== '+resp);
        
        }
          
    }


    public void loadRevGoalChart() {
        revenueChart = new chartResponse();
        isError = false;
        ApexPages.getMessages().clear();
        fetchSalesRepGoals();
        chartResponse revChatResp = new chartResponse();
        system.debug('srGoal==>'+srGoal);
        List<AggregateResult> lstYTD;
        List<Sales_Representative__c> salesEggSplits = new List<Sales_Representative__c> ();
        if (srGoal != null) {
            // to calulate RevenueGoal Gauge Charts from 0 to endPoint
            if (srGoal.Direct_Sales_Goal__c > 0 || srGoal.Resell_Sales_Goal__c > 0) {
                revChatResp.chartTotalInDecimal = srGoal.Direct_Sales_Goal__c + srGoal.Resell_Sales_Goal__c; 
            }
            else if ( revChatResp.chartTotalInDecimal == 0) {
                isError = true;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'please add the details of Direct Sales Goal & Resell Sales Goal in Sales rep goal for selected user ' +  srGoal.Name + '<a href="/lightning/r/Sales_Rep_Goal__c/'+srGoal.Id+'/view" target="_blank"> Click Here</a>'));
                return;
            }
            // calculate Total Sales(booked) value
            if (selectedUserId == 'Midwest Machinery') {
                lstYTD = [SELECT SUM(TotalSalesBooked__c) totalSales
                          FROM Sales_Representative__c
                          WHERE (Sales_Rep__r.Office_Location__c =: SAINT_LOUIS
                                            OR Sales_Rep__r.Office_Location__c =: OKLAHOMA 
                                            OR Sales_Rep__r.Office_Location__c =: KANSAS_CITY 
                                            OR Sales_Rep__r.Office_Location__c =: DENVER
                                            OR Sales_Rep__r.Office_Location__c =: MIDWEST_INDUSTRIAL_BUILDERS) 
                          AND Opportunity__r.StageName = 'Closed Won' 
                          AND Opportunity__r.Active_Financial_Quote__c != null 
                          AND Opportunity__c != null
                          AND Opportunity__r.Project__c != null
                          AND Opportunity__r.Project__r.CreatedDate = THIS_YEAR
                          AND Opportunity__r.Project__r.RemoveFromSalesResult__c != true];   

            } else if (selectedUserId == SAINT_LOUIS 
                        || selectedUserId == OKLAHOMA 
                        || selectedUserId == KANSAS_CITY 
                        || selectedUserId == DENVER
                        || selectedUserId == MIDWEST_INDUSTRIAL_BUILDERS) {
                
                 lstYTD = [SELECT SUM(TotalSalesBooked__c) totalSales
                            FROM Sales_Representative__c
                            WHERE Sales_Rep__r.Office_Location__c = :selectedUserId 
                            AND Opportunity__r.StageName = 'Closed Won' 
                            AND Opportunity__r.Active_Financial_Quote__c != null 
                            AND Opportunity__c != null
                            AND Opportunity__r.Project__c != null
                            AND Opportunity__r.Project__r.CreatedDate = THIS_YEAR
                            AND Opportunity__r.Project__r.RemoveFromSalesResult__c != true];                                                          
            } else {
                 lstYTD  = [SELECT SUM(TotalSalesBooked__c) totalSales
                            FROM Sales_Representative__c
                            WHERE Sales_Rep__c = :selectedUserId
                            AND Opportunity__r.StageName = 'Closed Won'
                            AND Opportunity__r.Active_Financial_Quote__c != null 
                            AND Opportunity__c != null
                            AND Opportunity__r.Project__c != null
                            AND Opportunity__r.Project__r.CreatedDate = THIS_YEAR
                            AND Opportunity__r.Project__r.RemoveFromSalesResult__c != true];
            
            //AND CALENDAR_YEAR(Opportunity__r.CloseDate) =: System.Today().year() 
            system.debug('lstYTD-Revenue == '+lstYTD);   
            }
            
            if (lstYTD.isEmpty()) {
                isError = true;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'data for sales engineering split not found for selected user:' + selectedUserName));
            } else if (!lstYTD.isEmpty() && lstYTD[0].get('totalSales') != null) {
                revChatResp.chartActualInDecimal = (decimal)lstYTD[0].get('totalSales');
            }
            
            revenueChart = revChatResp;
            system.debug('revenueChart== '+revenueChart);
        }
        
    }


    public void loadActivityGoalChart() {
        system.debug('Activity Chart Selected User id: '+selectedUserId);
        activityChart = new chartResponse();
        Integer totalNumber = 0;
        isError = false;
        ApexPages.getMessages().clear();
        chartResponse resp = new chartResponse();
        List<SalesActivityGoal__c>  chartTotlaList = new List<SalesActivityGoal__c>();

        if(selectedUserId.startsWith('005')){ // start with 005
                chartTotlaList = [SELECT Id,
                                        Total__c
                                        FROM SalesActivityGoal__c
                                        WHERE SalesRep__c = :selectedUserId // Use selected user id instead current user id
                                        AND Year__c = :String.valueOf(system.now().year())
                                        LIMIT 1];      
                                                    
        }else{
            chartTotlaList = [SELECT Id,
                                    Total__c
                                    FROM SalesActivityGoal__c
                                    WHERE Master_Report__c = :selectedUserId //  master report
                                    AND Year__c = :String.valueOf(system.now().year())
                                    LIMIT 1];
           
        }                                                                                                                              
    
        if(chartTotlaList != null && chartTotlaList.size() > 0){

            totalNumber = Integer.valueOf(chartTotlaList[0].Total__c);                                               
            resp.chartTotalInteger = totalNumber;
            if (totalNumber != null && totalNumber > 0 ) {
                system.debug('chartTotalInteger > 0 : '+resp.chartTotalInteger);
                DateTime lastYearDate = system.now().addMonths(-12);
                List<LogACall__c> activitiesOfSalesRep;
                    // master report for
                if (selectedUserId == 'Midwest Machinery') {
                    activitiesOfSalesRep = [SELECT Id,
                                                    Assigned_To__c,
                                                    Type_of_Call__c,
                                                    CreatedDate,
                                                    Event_Date__c
                                            FROM LogACall__c
                                            WHERE (Assigned_To__r.Office_Location__c =:SAINT_LOUIS
                                                   OR Assigned_To__r.Office_Location__c =:OKLAHOMA
                                                   OR Assigned_To__r.Office_Location__c =:KANSAS_CITY
                                                   OR Assigned_To__r.Office_Location__c =:DENVER
                                                   OR Assigned_To__r.Office_Location__c =:MIDWEST_INDUSTRIAL_BUILDERS)
                                            AND CreatedDate >= :lastYearDate
                                            AND Type_of_Call__c != null];
        
                } else if (selectedUserId == SAINT_LOUIS 
                            || selectedUserId == OKLAHOMA 
                            || selectedUserId == KANSAS_CITY 
                            || selectedUserId == DENVER
                            || selectedUserId == MIDWEST_INDUSTRIAL_BUILDERS) {
                    
                 activitiesOfSalesRep = [SELECT Id,
                                                Assigned_To__c,
                                                Type_of_Call__c,
                                                CreatedDate,
                                                Event_Date__c
                                        FROM LogACall__c
                                        WHERE Assigned_To__r.Office_Location__c =:selectedUserId
                                         AND CreatedDate >= :lastYearDate
                                         AND Type_of_Call__c != null];
                                                                                               
                } else {
                    activitiesOfSalesRep = [SELECT Id,
                                            Assigned_To__c,
                                            Type_of_Call__c,
                                            CreatedDate,
                                            Event_Date__c
                                        FROM LogACall__c
                                        WHERE Assigned_To__c =:selectedUserId
                                        AND CreatedDate >= :lastYearDate
                                        AND Type_of_Call__c != null];
                    system.debug('selected sales ActivityGoal' +activitiesOfSalesRep);                           
                }

                if(activitiesOfSalesRep != null && activitiesOfSalesRep.size() > 0){
                    Map<String, Integer> activityTypeCount = new Map<String, Integer>();

                    for (LogACall__c activity : activitiesOfSalesRep) {
                
                        if(activity.Type_of_Call__c != 'Expense Only' && activity.Event_Date__c.Year() == System.now().year()){
                            if (!activityTypeCount.containsKey(activity.Type_of_Call__c)) {
                                activityTypeCount.put(activity.Type_of_Call__c, 1);
                                
                            } else {
                                activityTypeCount.put(activity.Type_of_Call__c, 
                                                activityTypeCount.get(activity.Type_of_Call__c) + 1);
                            } 
                        }    
                    } 
                        

                    for (String activityName : activityTypeCount.keySet()) {
                        if (activityTypeCount.containsKey(activityName)) {
                            resp.chartActualInInteger += (ActivityGoalPoints__c.getValues(activityName).Point__c != null ? ActivityGoalPoints__c.getValues(activityName).Point__c : 0)
                             * (activityTypeCount.get(activityName) != null ? activityTypeCount.get(activityName) : 0);
                        }  
                        system.debug('resp.chartActualInInteger is :' + resp.chartActualInInteger);
                    }

                    List<AggregateResult> totalPoints = [Select 
                                                            SUM(Points__c) totalPoints
                                                        FROM LogACall__c
                                                        WHERE Assigned_To__c =:selectedUserId 
                                                        AND CreatedDate >= :lastYearDate
                                                        AND Type_of_Call__c != null];
                    if (totalPoints.isEmpty()) {
                        isError = true;
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'no call logged for selected user:' + selectedUserName));
                    } else if (!totalPoints.isEmpty() && totalPoints[0].get('totalPoints') != null) {
                        //resp.chartActualInInteger = Integer.valueOf(totalPoints[0].get('totalPoints'));
                    }
                    /*resp.chartActualInInteger = [SELECT Count()
                                                    FROM LogACall__c
                                                    WHERE Assigned_To__c =:selectedUserId // Use selected user id instead UserInfo.getUserId()
                                                    AND CreatedDate >= :lastYearDate
                                                    AND Type_of_Call__c != null];*/
                }
            } 
            system.debug('Final activityChart Resp: '+resp);
            activityChart = resp;
        }else{
            isError = true;
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'data for sales activity goal not found for selected user:' + selectedUserName));
        }      
    }

    public void fetchSalesRepGoals () {
        system.debug('selectedUserId=='+selectedUserId);
        try {
            if (selectedUserId.startsWith('005')) {
                srGoal = [Select Name,Margin_Goal__c,Monthly_Margin__c,
                                            Revenue_Goal__c,Monthly_Revenue__c,
                                            Direct_Sales_Goal__c,
                                            Resell_Sales_Goal__c,
                                            Direct_Sales_Percentage__c,
                                            Sales_Margin_Percentage__c
                                    FROM Sales_Rep_Goal__c
                                    WHERE Year__c =:  String.valueOf(System.Today().year())
                                    AND Sales_Rep__c =: selectedUserId];
                system.debug('sales rep for singal' + srGoal);                   
    
            } else {
                srGoal = [Select Name,Margin_Goal__c,Monthly_Margin__c,
                                            Revenue_Goal__c,Monthly_Revenue__c,Direct_Sales_Goal__c,
                                            Resell_Sales_Goal__c,
                                            Direct_Sales_Percentage__c,
                                            Sales_Margin_Percentage__c
                                    FROM Sales_Rep_Goal__c
                                    WHERE Year__c =:  String.valueOf(System.Today().year())
                                    AND Master_Report__c =: selectedUserId];
                system.debug('sales rep office level user ' + srGoal);                     
            }

           if (srGoal == null) {
                isError = true;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'sales rep goals are not set for selected user:' + selectedUserName));
                return;
            }

        } catch(Exception ex) {
            isError = true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'sales rep goals are not set for selected user:' + selectedUserName));
            return;
           // throw new applicationException('sales rep goals are not set for selected user:' + selectedUserId);
        }
    }

    public class chartResponse{
        @AuraEnabled
        public Integer chartTotalInteger{get;set;}
        @AuraEnabled
        public Decimal chartActualInInteger{get;set;}
        @AuraEnabled
        public Decimal chartActualInDecimal{get;set;}
        @AuraEnabled
        public Decimal chartTotalInDecimal{get;set;}
        
        public chartResponse(){
            //salesActivitySO = new SalesActivityGoal__c();
            chartTotalInteger = 0;
            chartActualInInteger = 0;
            chartActualInDecimal = 0;
            chartTotalInDecimal = 0;
        }  
    }
}