force-app/main/default/objects/Account/fields/Is_Taxable__c.field-meta.xml
<CustomField>
    <fullName>Is_Taxable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Taxable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bid_Date__c.field-meta.xml
<CustomField>
    <fullName>Bid_Date__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY())&amp;&apos; 2:00:00&apos;)</defaultValue>
    <inlineHelpText>When will you send your first firm bid?</inlineHelpText>
    <label>Bid Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ledger__c.field-meta.xml
<CustomField>
    <fullName>Ledger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ledger</label>
    <referenceTo>AcctSeed__Ledger__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <inlineHelpText>Which Midwest Group office is this for?</inlineHelpText>
    <label>Midwest Group Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Midwest Machinery STL</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery KC</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery OK</fullName>
            </value>
            <value>
                <fullName>Engineered Products</fullName>
            </value>
            <value>
                <fullName>MaRRS</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
            <value>
                <fullName>Spark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{YY}-{0000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OriginalName__c.field-meta.xml
<CustomField>
    <fullName>OriginalName__c</fullName>
    <label>Original Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Project_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin__c</fullName>
    <label>Total Project Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Attention_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Attention_to_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This will show up on the generated quote PDF for the &quot;Proposal To&quot; section. Example: Proposal to Acme Corporation.</inlineHelpText>
    <label>Attention to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Attention to Account)</relationshipLabel>
    <relationshipName>Quotes3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Bid_Date__c.field-meta.xml
<CustomField>
    <fullName>Bid_Date__c</fullName>
    <label>Quote Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Bidding_To__c.field-meta.xml
<CustomField>
    <fullName>Bidding_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name the person you are bidding this quote to. This persons name will show up on the generated quote in the &quot;Attention&quot; field at the top of the PDF.</inlineHelpText>
    <label>Bidding To Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Commissions_and_Rebates__c.field-meta.xml
<CustomField>
    <fullName>Commissions_and_Rebates__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commissions and Rebates</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Hide_Total_Base_Bid_Total__c.field-meta.xml
<CustomField>
    <fullName>Hide_Total_Base_Bid_Total__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Total Base Bid Total</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Is_Active_Project_Financials__c.field-meta.xml
<CustomField>
    <fullName>Is_Active_Project_Financials__c</fullName>
    <formula>IF(Id = Opportunity.Active_Financial_Quote__c , true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active Project Financials</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Is_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Locked?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Is_Sync_Quote__c.field-meta.xml
<CustomField>
    <fullName>Is_Sync_Quote__c</fullName>
    <formula>IF(Opportunity.Sync_Quote__c ==  Id, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Sync Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Close_Date__c</fullName>
    <formula>Opportunity.CloseDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <formula>Opportunity.Opportunity_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Sync_Quote__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Sync_Quote__c</fullName>
    <formula>Opportunity.Sync_Quote__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Sync Quote</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/prepared_by_user__c.field-meta.xml
<CustomField>
    <fullName>prepared_by_user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prepared by user (User)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CreateBy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Quantity_Total__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Total__c</fullName>
    <label>Quantity Total</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteDocumentVersion__c.field-meta.xml
<CustomField>
    <fullName>QuoteDocumentVersion__c</fullName>
    <description>Version of quote document as pdf</description>
    <label>Quote Document Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Base_Bid_Total__c.field-meta.xml
<CustomField>
    <fullName>Total_Base_Bid_Total__c</fullName>
    <label>Total Base Bid Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Buy_Resell_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Buy_Resell_Margin__c</fullName>
    <label>Total Buy/Resell Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Buy_Resell_Margin_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Total_Buy_Resell_Margin_Percentage__c</fullName>
    <label>Total Buy/Resell Margin (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Buy_Resell_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Buy_Resell_Price__c</fullName>
    <label>Total Buy Resell Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Direct_Sell_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Direct_Sell_Price__c</fullName>
    <label>Total Direct Sell Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Extended_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Extended_Cost__c</fullName>
    <label>Total Extended Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Project_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin__c</fullName>
    <label>Total Project Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Project_Margin_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin_Percentage__c</fullName>
    <label>Total Project Margin (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/QuoteConstants.cls
/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 03-21-2024
 * @last modified by  : Nilesh Badrakiya
**/
public with sharing class QuoteConstants {
    
    // sobject name
    public static final String SOBJECT_NAME = 'Quote';
	
    // field names
    public static final String FIELD_NAME_QUOTE_NUMBER = 'QuoteNumber';
    public static final String FIELD_NAME_TOTAL_BASE_BID_TOTAL = 'Total_Base_Bid_Total__c';
    public static final string FIELD_NAME_HIDE_TOTAL_BASE_BID_TOTAL = 'Hide_Total_Base_Bid_Total__c';
    public static final String FIELD_NAME_TOTAL_EXTENDED_COST = 'Total_Extended_Cost__c';
    public static final String FIELD_NAME_TOTAL_DIRECT_SELL_PRICE = 'Total_Direct_Sell_Price__c';
    public static final String FIELD_NAME_TOTAL_BUY_RESELL_PRICE = 'Total_Buy_Resell_Price__c';
    public static final String FIELD_NAME_TOTAL_BUY_RESELL_MARGIN = 'Total_Buy_Resell_Margin__c';
    public static final String FIELD_NAME_TOTAL_BUY_RESELL_MARGIN_PERCENTAGE = 'Total_Buy_Resell_Margin_Percentage__c';
    public static final String FIELD_NAME_COMMISSIONS_AND_REBATES = 'Commissions_and_Rebates__c';
    public static final String FIELD_NAME_TOTAL_PROJECT_MARGIN = 'Total_Project_Margin__c';
    public static final String FIELD_NAME_TOTAL_PROJECT_MARGIN_PERCENTAGE = 'Total_Project_Margin_Percentage__c';
    public static final String FIELD_NAME_QUANTITY_TOTAL = 'Quantity_Total__c';
    public static final String FIELD_NAME_IS_ACTIVE_PROJECT_FINANCIALS = 'Is_Active_Project_Financials__c';
    public static final String FIELD_NAME_DOCUMENT_VERSION = 'QuoteDocumentVersion__c';
    public static final String FIELD_NAME_OPPORTUNITY_NAME = 'Opportunity_Name__c'; 
    public static final String FIELD_NAME_BID_DATE = 'Bid_Date__c'; 
    public static final String FIELD_NAME_IS_SYNC_QUOTE = 'Is_Sync_Quote__c'; 
    public static final String FIELD_NAME_OPPORTUNITY_SYNC_QUOTE = 'Opportunity_Sync_Quote__c'; 
    public static final String FIELD_NAME_OPPORTUNITY_CLOSE_DATE = 'Opportunity_Close_Date__c'; 
    public static final String FIELD_NAME_IS_LOCKED = 'Is_Locked__c'; 
    public static final String FIELD_NAME_OPPORTUNITY_ID = 'OpportunityId';
    public static final String FIELD_NAME_OPPORTUNITY_NUMBER = 'Opportunity_Number__c';
    public static final String FIELD_NAME_SUBMITTED_BY = 'Submitted_By__c';
    public static final String FIELD_NAME_PREPARE_BY_USER = 'prepared_by_user__c';
    public static final String FIELD_NAME_BIDDING_TO = 'Bidding_To__c';
    public static final String FIELD_NAME_ATTENTION_TO_ACCOUNT = 'Attention_to_Account__c';
    public static final String FIELD_NAME_RUN_TIME_LOCK = 'Run_Time_Lock__c';
    public static final String FIELD_NAME_IS_LOCKED_BY = 'Is_Locked_By__c';



    // Relation Fields
    public static final String RELATIONSHIP_OPPORTUNITY_OFFICE = 'Opportunity.Office__c';
    public static final String RELATIONSHIP_OPPORTUNITY_ID = 'OpportunityId';
    public static final String RELATIONSHIP_OPPORTUNITY_NUMBER = 'Opportunity.Opportunity_Number__c';
    public static final String RELATIONSHIP_OPPORTUNITY_ORIGINAL_NAME = 'Opportunity.OriginalName__c';
    public static final String RELATIONSHIP_OPPORTUNITY_RECORD_TYPE_NAME = 'Opportunity.RecordType.Name';
    public static final String RELATIONSHIP_OPPORTUNITY_CREATED_DATE = 'Opportunity.CreatedDate';
    public static final String RELATIONSHIP_OPPORTUNITY_NAME = 'Opportunity.Name';
    public static final String RELATIONSHIP_OPPORTUNITY_TAXABLE = 'Opportunity.Account.Is_Taxable__c';
    public static final String RELATIONSHIP_OPPORTUNITY_ACCOUNT_ID = 'Opportunity.AccountId';
    public static final String RELATIONSHIP_OPPORTUNITY_LEDGER = 'Opportunity.Ledger__c';
    public static final String RELATIONSHIP_OPPORTUNITY_BID_DATE = 'Opportunity.Bid_Date__c';
    // public static final String RELATIONSHIP_OPPORTUNITY_NAME = 'Opportunity_Name__c'; 
}