force-app/main/default/objects/Account/fields/Payment_and_Accounting_Notes__c.field-meta.xml
<CustomField>
    <fullName>Payment_and_Accounting_Notes__c</fullName>
    <label>Payment and Accounting Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Bidder_Detail__c/Bidder_Detail__c.object-meta.xml
<CustomObject>
    <label>Bidder Detail</label>
    <nameField>
        <displayFormat>BN-{000000}</displayFormat>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidder Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bidder_Detail__c/fields/Bid_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bid_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bid Contact (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bidder Details</relationshipLabel>
    <relationshipName>Bidder_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bidder_Detail__c/fields/Credit_Notes__c.field-meta.xml
<CustomField>
    <fullName>Credit_Notes__c</fullName>
    <formula>IF( hasNotes__c,HYPERLINK(&quot;/apex/CreditNotes?Id=&quot; +   IF(ISBLANK(Bid_Contact__c), Mechanical_Contractor__c, Bid_Contact__r.AccountId) , &quot;Notes&quot;,&apos;_blank&apos;), &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credit Notes</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bidder_Detail__c/fields/hasNotes__c.field-meta.xml
<CustomField>
    <fullName>hasNotes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>hasNotes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bidder_Detail__c/fields/Mechanical_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mechanical Contractor (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidder Details</relationshipLabel>
    <relationshipName>Bidder_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync Address with Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bid_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bid_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Who is the contact person for this bid?</inlineHelpText>
    <label>Bid Contact (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Bid Contact)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Credit_Notes__c.field-meta.xml
<CustomField>
    <fullName>Credit_Notes__c</fullName>
    <label>Accounting Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/SyncAddressAccountTriggerTest.cls
/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 02-05-2024
 * @last modified by  : Nilesh Badrakiya
**/
@isTest
private class SyncAddressAccountTriggerTest {
    
    static testMethod void SyncTest() {
        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        newAccount.BillingStreet = '123 Main St';
        newAccount.BillingCity = 'Anytown';
        newAccount.BillingState = 'CA';
        newAccount.BillingPostalCode = '12345';
        newAccount.BillingCountry = 'USA';
        insert newAccount;
        
        Contact newContact = new Contact();
        newContact.FirstName = 'FirstName';
        newContact.LastName = 'LastName';
        newContact.AccountId = newAccount.Id;
        newContact.Sync__c = true;
        insert newContact;

        Opportunity testOpportunity = new Opportunity();
        testOpportunity.Name = 'Test Opportunity';
        testOpportunity.StageName = 'Prospecting';
        testOpportunity.CloseDate = Date.today();
        testOpportunity.AccountId = newAccount.Id;
        testOpportunity.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Equipment - Plan/Spec').getRecordTypeId();
        insert testOpportunity;

        // Create test bidder detail
        Bidder_Detail__c testBidderDetail = new Bidder_Detail__c();
        testBidderDetail.Bid_Contact__c = newContact.Id;
        testBidderDetail.Mechanical_Contractor__c = null;
        insert testBidderDetail;

        // Set payment and accounting notes
        newAccount.Payment_and_Accounting_Notes__c = 'Test notes';
        update newAccount;

        newContact = [SELECT Id, MailingStreet, MailingCity FROM Contact WHERE Id = :newContact.Id];
        System.assertEquals(newAccount.BillingStreet, newContact.MailingStreet);
        System.assertEquals(newAccount.BillingCity, newContact.MailingCity);

        testOpportunity = [SELECT Id, Credit_Notes__c FROM Opportunity WHERE Id = :testOpportunity.Id];
        System.assertEquals(newAccount.Payment_and_Accounting_Notes__c, testOpportunity.Credit_Notes__c);
 
         // Verify bidder detail updates
        testBidderDetail = [SELECT Id, hasNotes__c FROM Bidder_Detail__c WHERE Id = :testBidderDetail.Id];
        System.assertEquals(true, testBidderDetail.hasNotes__c);
    }
}