force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/fields/Inventory_Cost__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Cost__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Cost</label>
    <referenceTo>AcctSeed__Inventory_Cost__c</referenceTo>
    <relationshipLabel>Sales Order Line</relationshipLabel>
    <relationshipName>Sales_Order_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>Product_Select__c</referenceTo>
    <relationshipLabel>Sales Order Line</relationshipLabel>
    <relationshipName>Sales_Order_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Equipment/Projects</fullName>
            </value>
            <value>
                <fullName>Parts/Aftermarket</fullName>
            </value>
            <value>
                <fullName>General Contracting</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Web Store</fullName>
            </value>
            <value>
                <fullName>Marketing/ Rep Services</fullName>
            </value>
            <value>
                <fullName>General Contracting (MIB Only)</fullName>
            </value>
            <value>
                <fullName>Distribution/Fullfillment Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <formula>Quote_Line_Item__r.Tag__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tag</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/Product_Select__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Select__c/fields/CR__c.field-meta.xml
<CustomField>
    <fullName>CR__c</fullName>
    <label>CR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Descriptions__c.field-meta.xml
<CustomField>
    <fullName>Descriptions__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Inventory_Cost__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Cost__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Cost</label>
    <referenceTo>AcctSeed__Inventory_Cost__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B/R</fullName>
            </value>
            <value>
                <fullName>D/S</fullName>
            </value>
            <value>
                <fullName>C/R</fullName>
            </value>
            <value>
                <fullName>P/T</fullName>
            </value>
            <value>
                <fullName>LAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderLineItem.cls
/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 12-06-2023
 * @last modified by  : Nilesh Badrakiya
**/
public with sharing class OrderLineItem {
    
    public Boolean isSelect {get;set;}
    public Boolean isAlternate {get;set;}
    public String tag {get;set;}
    public AcctSeedERP__Sales_Order_Line__c orderLineItem {get;set;}
    public String descriptions {get;set;}
  
    
    public OrderLineItem(){
        orderLineItem = new AcctSeedERP__Sales_Order_Line__c();
    }

    public OrderLineItem(Boolean isSelect, Product_Select__c lineItem) {
        
        this.isSelect = isSelect;
        
        orderLineItem = new AcctSeedERP__Sales_Order_Line__c();
        isAlternate = lineItem.Alternate__c;
        orderLineItem.AcctSeedERP__Quantity_Ordered__c = lineItem.Quantity__c;
        orderLineItem.Inventory_Cost__c = lineItem.Inventory_Cost__c; // map IC from QLI to SOL 
        //orderLineItem.Sale_Type__c = lineItem.Sale_Type__c;
        orderLineItem.AcctSeedERP__Unit_Price__c  = 0;
        
        if(lineItem.Sale_Type__c == 'C/R') {
            orderLineItem.AcctSeedERP__Unit_Price__c = lineItem.CR__c;
        } else {
            if(lineItem.Sales_Price__c != null && lineItem.Sales_Price__c != 0) {
                if(lineItem.Quantity__c != null && lineItem.Quantity__c > 0) {
                    orderLineItem.AcctSeedERP__Unit_Price__c = (lineItem.Sales_Price__c / lineItem.Quantity__c).setScale(5);
                    
                }
            }
        }
        
         
        //orderLineItem.AcctSeedERP__Unit_Price__c =  lineItem.Unit_Cost__c;       
        orderLineItem.AcctSeedERP__Product__c = lineItem.ProductId__c;
        orderLineItem.AcctSeedERP__Comment__c = '';
        orderLineItem.Quote_Line_Item__c = lineItem.Id;
        this.descriptions = lineItem.Descriptions__c;
        //orderLineItem.Quote_Line_Item__r.Descriptions__c = lineItem.Descriptions__c;
        
        tag = lineItem.Tag__c;
    }

}