force-app/main/default/objects/Bidder_Detail__c/Bidder_Detail__c.object-meta.xml
<CustomObject>
    <label>Bidder Detail</label>
    <nameField>
        <displayFormat>BN-{000000}</displayFormat>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidder Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bidder_Detail__c/fields/Bid_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bid_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bid Contact (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bidder Details</relationshipLabel>
    <relationshipName>Bidder_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bidder_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bidder Details</relationshipLabel>
    <relationshipName>Bidder_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bidder_Detail__c/fields/Won_Lost_Bidding__c.field-meta.xml
<CustomField>
    <fullName>Won_Lost_Bidding__c</fullName>
    <inlineHelpText>Did this MC win the bid?</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Not Bidding</fullName>
            </value>
            <value>
                <fullName>Bidding</fullName>
            </value>
            <value>
                <fullName>Quote Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmailAllBidders.cls
global class EmailAllBidders{

    webservice static String SendEmail(Id oppId) { 
        
        String strEmail = '';
        system.debug('oppId---'+oppId);
        List<Bidder_Detail__c> lstBiddersName = [Select Bid_Contact__r.Email From Bidder_Detail__c
                                                WHERE Opportunity__c =: oppId
                                                AND Bid_Contact__c != null
                                                AND Bid_Contact__r.Email != ''
                                                AND Won_Lost_Bidding__c != 'Not Bidding'
                                                AND Won_Lost_Bidding__c != 'Lost'];
        system.debug('oppId---'+lstBiddersName);
        for(Bidder_Detail__c bd : lstBiddersName){
        	if(!strEmail.contains(bd.Bid_Contact__r.Email)){
        		strEmail = strEmail + bd.Bid_Contact__r.Email + ';';
        	}
        }
        
        return strEmail;
        
    }
    
}