force-app/main/default/objects/Bidder_Detail__c/Bidder_Detail__c.object-meta.xml
<CustomObject>
    <label>Bidder Detail</label>
    <nameField>
        <displayFormat>BN-{000000}</displayFormat>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidder Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bidder_Detail__c/fields/Bid_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bid_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bid Contact (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bidder Details</relationshipLabel>
    <relationshipName>Bidder_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bidder_Detail__c/fields/Mechanical_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mechanical Contractor (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidder Details</relationshipLabel>
    <relationshipName>Bidder_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bidder_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bidder Details</relationshipLabel>
    <relationshipName>Bidder_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bid_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bid_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Who is the contact person for this bid?</inlineHelpText>
    <label>Bid Contact (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Bid Contact)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a look up to account record to store end user.</description>
    <inlineHelpText>Please select an end user for this opportunity.</inlineHelpText>
    <label>End User Business Name (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>EndUserOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SendEmailToContactsTest.cls
@isTest
private class SendEmailToContactsTest{
 
    static testMethod void testMethod1() {
        
        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        insert newAccount;
        
        Contact newContact = new Contact();
        newContact.firstName = 'Test';
        newContact.LastName = 'Last Name';
        newContact.accountId = newAccount.Id;
        insert newContact;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(newAccount);
        SendEmailToContacts objSendEmailToContacts = new SendEmailToContacts(sc);
        objSendEmailToContacts.redirectBackToAccount();
        
    }
    
    static testMethod void testMethod2() {
        
        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        insert newAccount;
        
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.closeDate = Date.today();
        objOpportunity.Name = 'Test Opportunity';
        objOpportunity.stageName = 'Draft';
        objOpportunity.End_User__c = newAccount.Id;
        insert objOpportunity;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(newAccount);
        OpportunityEndUser objOpportunityEndUser = new OpportunityEndUser(sc);
        
        
    }
    
    static testMethod void testMethod3() {
        
        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        insert newAccount;
        
        Contact newContact = new Contact();
        newContact.firstName = 'Test';
        newContact.LastName = 'Last Name';
        newContact.accountId = newAccount.Id;
        insert newContact;
        
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.closeDate = Date.today();
        objOpportunity.Name = 'Test Opportunity';
        objOpportunity.stageName = 'Draft';
        objOpportunity.End_User__c = newAccount.Id;
        insert objOpportunity;
        
        Bidder_Detail__c newBid = new Bidder_Detail__c();
        newBid.Bid_Contact__c = newContact.Id;
        newBid.Mechanical_Contractor__c = newAccount.Id;
        newBid.Opportunity__c = objOpportunity.Id;
        insert newBid;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(newContact);
        OpportunityListOnContact objOpportunityListOnContact = new OpportunityListOnContact(sc);
        
        ApexPages.StandardController sc1 = new ApexPages.StandardController(newAccount);
        OpportunityMechanicalContractors objOpportunityMechanicalContractors = new OpportunityMechanicalContractors (sc1);
    }
}