force-app/main/default/objects/Bidder_Detail__c/Bidder_Detail__c.object-meta.xml
<CustomObject>
    <label>Bidder Detail</label>
    <nameField>
        <displayFormat>BN-{000000}</displayFormat>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidder Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bidder_Detail__c/fields/Bid_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bid_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bid Contact (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bidder Details</relationshipLabel>
    <relationshipName>Bidder_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bidder_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bidder Details</relationshipLabel>
    <relationshipName>Bidder_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bid_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bid_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Who is the contact person for this bid?</inlineHelpText>
    <label>Bid Contact (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Bid Contact)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Base_Bid_Total_Quote__c.field-meta.xml
<CustomField>
    <fullName>Total_Base_Bid_Total_Quote__c</fullName>
    <inlineHelpText>This is the total base bid for the quote currently synced with this opportunity.</inlineHelpText>
    <label>Base Bid Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OpportunityListOnContact.cls
public class OpportunityListOnContact{
    
    public List<Opportunity> lstOpportunity{get;set;}
    public String contactId{get;set;}
    
    public OpportunityListOnContact(Apexpages.StandardController stdCon){
        contactId = stdCon.getId();
        getOpportunities();
    }
    
    public void getOpportunities(){
        
        List<Bidder_Detail__c> lstBidderDetails = [Select Id, Opportunity__c From Bidder_Detail__c WHERE Bid_Contact__c =: contactId ];
        
        Set<Id> setOpportunityIds = new Set<Id>();
            
        for(Bidder_Detail__c bd : lstBidderDetails){
            setOpportunityIds.add(bd.Opportunity__c);
        }    
        
        lstOpportunity = [Select Id, Name, StageName, Total_Base_Bid_Total_Quote__c, CloseDate From Opportunity Where Id IN: setOpportunityIds];
            
        
    }
    
    
}