force-app/main/default/objects/Bidder_Detail__c/Bidder_Detail__c.object-meta.xml
<CustomObject>
    <label>Bidder Detail</label>
    <nameField>
        <displayFormat>BN-{000000}</displayFormat>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidder Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bidder_Detail__c/fields/Bid_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bid_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bid Contact (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bidder Details</relationshipLabel>
    <relationshipName>Bidder_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bidder_Detail__c/fields/Mechanical_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mechanical Contractor (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidder Details</relationshipLabel>
    <relationshipName>Bidder_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bidder_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bidder Details</relationshipLabel>
    <relationshipName>Bidder_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bidder_Detail__c/fields/Won_Lost_Bidding__c.field-meta.xml
<CustomField>
    <fullName>Won_Lost_Bidding__c</fullName>
    <inlineHelpText>Did this MC win the bid?</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Not Bidding</fullName>
            </value>
            <value>
                <fullName>Bidding</fullName>
            </value>
            <value>
                <fullName>Quote Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bid_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bid_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Who is the contact person for this bid?</inlineHelpText>
    <label>Bid Contact (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Bid Contact)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/updateBiddersOnOpportunityTest.cls
@isTest
private class updateBiddersOnOpportunityTest{
 
    @testSetup
    static void testSetup() {
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.closeDate = Date.today();
        objOpportunity.Name = 'Test Opportunity';
        objOpportunity.stageName = 'Draft';
        insert objOpportunity;
        
        Account acc = new Account();
        acc.Name = 'test';
        insert acc;
        
        Contact cont = new Contact();
        cont.LastName = 'Test Name';
        cont.AccountId = acc.Id;
        cont.Email = 'nilesh.badrakia@gmail.com';
        insert cont;
    }
    static testMethod void testMethod1() {

        Opportunity objOpportunity = [SELECT Id FROM Opportunity Limit 1];
        Contact cont = [SELECT Id FROM Contact Limit 1];
        Account acc = [SELECT Id FROM Account Limit 1];
        Bidder_Detail__c newBd = new Bidder_Detail__c();
        newBd.Bid_Contact__c = cont.Id;
        newBd.Opportunity__c = objOpportunity.Id;
        newBd.Won_Lost_Bidding__c = 'Bidding';
        newBd.Mechanical_Contractor__c = acc.Id;
        insert newBd;

        Test.startTest();
        newBd.Won_Lost_Bidding__c = 'Won';
        update newBd;
        Test.stopTest();
    }
    static testMethod void testMethod2() {

        Opportunity objOpportunity = [SELECT Id FROM Opportunity Limit 1];
        Contact cont = [SELECT Id FROM Contact Limit 1];
        Account acc = [SELECT Id FROM Account Limit 1];
        Bidder_Detail__c newBd1 = new Bidder_Detail__c();
        newBd1.Opportunity__c = objOpportunity.Id;
        newBd1.Won_Lost_Bidding__c = 'Won';
        newBd1.Mechanical_Contractor__c = acc.Id;
        insert newBd1;
        Test.startTest();
        newBd1.Won_Lost_Bidding__c = 'Bidding';
        update newBd1;
        delete newBd1;
        Test.stopTest();
    }
        
    static testMethod void testMethod3() {
        
        Opportunity objOpportunity = [SELECT Id FROM Opportunity Limit 1];
        Contact cont = [SELECT Id FROM Contact Limit 1];
        Account acc = [SELECT Id FROM Account Limit 1];
        Bidder_Detail__c newBd3 = new Bidder_Detail__c();
        newBd3.Opportunity__c = objOpportunity.Id;
        newBd3.Won_Lost_Bidding__c = 'Not Bidding';
        newBd3.Mechanical_Contractor__c = acc.Id;
        insert newBd3;

        Test.startTest();
        newBd3.Won_Lost_Bidding__c = 'Bidding';
        update newBd3;  
        Test.stopTest();
    }

    static testMethod void testMethod4() {
        
        Opportunity objOpportunity = [SELECT Id FROM Opportunity Limit 1];
        Contact cont = [SELECT Id FROM Contact Limit 1];
        Account acc = [SELECT Id FROM Account Limit 1];
        Bidder_Detail__c newBd2 = new Bidder_Detail__c();
        newBd2.Opportunity__c = objOpportunity.Id;
        newBd2.Won_Lost_Bidding__c = 'Not Bidding';
        newBd2.Mechanical_Contractor__c = acc.Id;
        insert newBd2;

        Test.startTest();
        newBd2.Won_Lost_Bidding__c = 'Won';
        update newBd2;
        Test.stopTest();
    }

    static testMethod void testMethod5() {
        
        Opportunity objOpportunity = [SELECT Id FROM Opportunity Limit 1];
        Contact cont = [SELECT Id FROM Contact Limit 1];
        Account acc = [SELECT Id FROM Account Limit 1];
        Bidder_Detail__c newBd2 = new Bidder_Detail__c();
        newBd2.Opportunity__c = objOpportunity.Id;
        newBd2.Won_Lost_Bidding__c = 'Won';
        newBd2.Mechanical_Contractor__c = acc.Id;
        insert newBd2;

        Test.startTest();
        newBd2.Won_Lost_Bidding__c = 'Lost';
        update newBd2;
        Test.stopTest();
    }
    
    static testMethod void testMethod6() {
        
        Opportunity objOpportunity = [SELECT Id FROM Opportunity Limit 1];
        Contact cont = [SELECT Id FROM Contact Limit 1];
        Account acc = [SELECT Id FROM Account Limit 1];
        Bidder_Detail__c testBidderDetail1 = new Bidder_Detail__c(Opportunity__c=objOpportunity.Id, Bid_Contact__c=cont.Id, Won_Lost_Bidding__c='Won',Mechanical_Contractor__c=acc.Id);
        insert testBidderDetail1;
    
        String emailList = EmailAllBidders.SendEmail(objOpportunity.Id);
        System.assertEquals('nilesh.badrakia@gmail.com;', emailList);
    }
}