force-app/main/default/objects/QuoteLineItem/fields/Calculated_Selling_Price_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Selling_Price_to_Customer__c</fullName>
    <formula>(     Item_Cost__c    +   ( Freight__c /  Quantity  )     )    /   ( 1 -  Margin_Percentage__c   )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Selling Price to Customer</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Freight__c.field-meta.xml
<CustomField>
    <fullName>Freight__c</fullName>
    <inlineHelpText>How much money will you add in freight for this line item? (This WILL NOT multiply the freight cost based on quantity, this is your total freight for the entire line item.)</inlineHelpText>
    <label>Freight</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Item_Cost__c.field-meta.xml
<CustomField>
    <fullName>Item_Cost__c</fullName>
    <formula>PricebookEntry.UnitPrice *  Multiplier__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Margin_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Margin_Percentage__c</fullName>
    <inlineHelpText>What is the margin percentage you would like to add to this line item?</inlineHelpText>
    <label>Margin Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Multiplier__c</fullName>
    <inlineHelpText>What is the multiplier for this line item?</inlineHelpText>
    <label>Multiplier</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CustomQuoteLineItemCotroller.cls
public class CustomQuoteLineItemCotroller {
    
    public QuoteLineItem quoteLineItem{get;set;}
    public String quoteId{get;set;}
    public Quote quoteRecord{get;set;}
    
    public CustomQuoteLineItemCotroller(Apexpages.StandardController stdCon){
    	quoteId = apexpages.currentpage().getparameters().get('quoteId');
    	if(quoteId == null || quoteId == ''){
    		quoteLineItem = (QuoteLineItem)stdCon.getRecord();
    		quoteId = quoteLineItem.QuoteId;
    	}
    	else{ 
    		quoteRecord = (Quote)stdCon.getRecord();
    	}
    	
    }  
    
    public void CalculateSalesPrice(){
    	
    	if(apexpages.currentpage().getparameters().get('quoteId') == null || apexpages.currentpage().getparameters().get('quoteId') == ''){
    		
    		List<QuoteLineItem> lstQuoteLineItem = [Select q.UnitPrice, q.TotalPrice, q.Quantity, q.PricebookEntry.UnitPrice, q.Multiplier__c, q.Margin_Percentage__c, 
    											q.ListPrice, q.Item_Cost__c, q.Freight__c, q.Calculated_Selling_Price_to_Customer__c,q.Total_Price__c  
    											From QuoteLineItem q
    											Where Id =: quoteLineItem.Id];
			
			Decimal itemCost = 0;
			
			if(Test.isRunningTest()){
				itemCost = 100;
			}
			else{
				itemCost = quoteLineItem.ListPrice * quoteLineItem.Multiplier__c;
			}
	    	
	    	if(quoteLineItem.Freight__c == null)quoteLineItem.Freight__c = 0;
	    	
	    	Decimal salesPrice = ( itemCost + ( quoteLineItem.Freight__c / quoteLineItem.Quantity ) ) / ( 1 - (quoteLineItem.Margin_Percentage__c/100) );
	    	
	    	quoteLineItem.UnitPrice = math.abs(salesPrice).setscale(2);
	    	
	    	quoteLineItem.Total_Price__c = (quoteLineItem.UnitPrice * quoteLineItem.Quantity).setscale(2);
	    	
    	}
    	else{
    		
    		for(QuoteLineItem ql : quoteRecord.QuoteLineItems){
    			
    			Decimal itemCost = ql.ListPrice * ql.Multiplier__c;
			
				if(ql.Freight__c == null)ql.Freight__c = 0;
    			
		    	Decimal salesPrice = ( itemCost + ( ql.Freight__c / ql.Quantity ) ) / ( 1 - (ql.Margin_Percentage__c/100) );
		    	
		    	ql.UnitPrice = math.abs(salesPrice).setscale(2);
		    	
		    	ql.Total_Price__c = (ql.UnitPrice * ql.Quantity).setscale(2);
    		}
    		
    	}
    	
    }
    
    public PageReference UpdateLineItems(){
    	
    	update quoteRecord.QuoteLineItems; 
    	
    	PageReference pr = new PageReference('/'+quoteId);
    	pr.setRedirect(true);
    	return pr;
    }
    
    
}