force-app/main/default/objects/Addition_Deduction__c/Addition_Deduction__c.object-meta.xml
<CustomObject>
    <label>Addition/Deduction</label>
    <nameField>
        <displayFormat>AD-{00000}</displayFormat>
        <label>Addition/Deduction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AdditionDeductions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Addition_Deduction__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>AdditionDeductions</relationshipLabel>
    <relationshipName>AdditionDeductions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Addition_Deduction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Addition</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Freight__c.field-meta.xml
<CustomField>
    <fullName>Freight__c</fullName>
    <inlineHelpText>What freight option will this order be using?</inlineHelpText>
    <label>Freight</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PPA</fullName>
            </value>
            <value>
                <fullName>Collect</fullName>
            </value>
            <value>
                <fullName>FFA</fullName>
            </value>
            <value>
                <fullName>3rd-Party Logistics</fullName>
            </value>
            <value>
                <fullName>Customer Pick Up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{YY}-{0000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <inlineHelpText>Add a &quot;tag&quot; or &quot;attention to&quot; for the shipping address if required.</inlineHelpText>
    <label>Tag</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Hide_Code__c.field-meta.xml
<CustomField>
    <fullName>Hide_Code__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Code</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Hide_Line__c.field-meta.xml
<CustomField>
    <fullName>Hide_Line__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Line</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Hide_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Hide_Pricing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Pricing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>Index</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Page_Break__c.field-meta.xml
<CustomField>
    <fullName>Page_Break__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Page Break</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Product Groups</relationshipLabel>
    <relationshipName>Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/Product_Select__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Select__c/fields/Descriptions__c.field-meta.xml
<CustomField>
    <fullName>Descriptions__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Extended_Cost__c.field-meta.xml
<CustomField>
    <fullName>Extended_Cost__c</fullName>
    <label>Extended Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <description>DNU for anything.</description>
    <label>Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Freight__c.field-meta.xml
<CustomField>
    <fullName>Freight__c</fullName>
    <label>Freight</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Is_Freight_Override__c.field-meta.xml
<CustomField>
    <fullName>Is_Freight_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Freight Override?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Is_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check whether the Line Item has SO Line Item associated with it.</description>
    <label>Is Locked?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/LBS__c.field-meta.xml
<CustomField>
    <fullName>LBS__c</fullName>
    <label>LBS</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Margin_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Margin_Percentage__c</fullName>
    <label>Margin Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Multiplier__c</fullName>
    <label>Multiplier</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Original_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Original_Product_Name__c</fullName>
    <label>Original Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>ProductSelects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Row_Index__c.field-meta.xml
<CustomField>
    <fullName>Row_Index__c</fullName>
    <label>Row Index</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B/R</fullName>
            </value>
            <value>
                <fullName>D/S</fullName>
            </value>
            <value>
                <fullName>C/R</fullName>
            </value>
            <value>
                <fullName>P/T</fullName>
            </value>
            <value>
                <fullName>LAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/T_LBS__c.field-meta.xml
<CustomField>
    <fullName>T_LBS__c</fullName>
    <label>T-LBS</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Is_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Locked?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <formula>Opportunity.Opportunity_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Original_Name__c.field-meta.xml
<CustomField>
    <fullName>Original_Name__c</fullName>
    <description>To hold original Quote Name</description>
    <inlineHelpText>This is the quote name that was used initially when the quote was created. This is the revision folder name in SharePoint.This is for reference purposes only.</inlineHelpText>
    <label>SharePoint Folder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Quote_FileName__c.field-meta.xml
<CustomField>
    <fullName>Quote_FileName__c</fullName>
    <label>Current Quote FileName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteDocumentVersion__c.field-meta.xml
<CustomField>
    <fullName>QuoteDocumentVersion__c</fullName>
    <description>Version of quote document as pdf</description>
    <label>Quote Document Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Scope_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Scope_File_Name__c</fullName>
    <label>Current Scope FileName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ScopeDocumentVersion__c.field-meta.xml
<CustomField>
    <fullName>ScopeDocumentVersion__c</fullName>
    <description>Scope Document Latest Version Number</description>
    <label>Scope Document Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/SubmittalDocumentVersion__c.field-meta.xml
<CustomField>
    <fullName>SubmittalDocumentVersion__c</fullName>
    <description>Submittal Document Latest Version</description>
    <label>Submittal Document Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CloneQuoteWithLineItems.cls
public with sharing class CloneQuoteWithLineItems{

    public Id quoteId{get;set;}
    public Quote oldQuote{get;set;}
    public Quote newQuote{get;set;}
    
    public CloneQuoteWithLineItems(ApexPages.StandardController controller) {
        quoteId = apexpages.currentpage().getparameters().get('id');
        oldQuote = database.query(getQuoteQuery());
        
    }
    
    public PageReference saveQuote() {
        system.debug('inside save method');
        UtilitySharePointToSFIntegration.quoteBulkInsertContext = true;
        newQuote = new Quote();
        newQuote = oldQuote.clone(false, false, false, false);
        newQuote.status = 'Draft';
        newQuote.Is_Locked__c = false;
        newQuote.Original_Name__c = newQuote.Name;
        newQuote.SubmittalDocumentVersion__c = 0;
        newQuote.ScopeDocumentVersion__c = 0;
        newQuote.QuoteDocumentVersion__c = 0;
        newQuote.Scope_File_Name__c = null;
        newQuote.Quote_FileName__c = null;
        insert newQuote;
        
        Quote newlyCreatedQuote = [select 
                                    Opportunity_Number__c,
                                    QuoteNumber,
                                    Opportunity_Name__c
                                    FROM 
                                    Quote where Id = :newQuote.Id];
        newQuote.Name = newlyCreatedQuote.Opportunity_Number__c+ '.' + newlyCreatedQuote.QuoteNumber + ' ' + newlyCreatedQuote.Opportunity_Name__c;
        
        //newQuote.Name = oldQuote.Name;
        system.debug('name of new quote>>'+ newQuote.Name);
        
        return null;
    }
    
    public PageReference cloneQuote(){
        
        /*Quote newQuote = oldQuote.clone(false, false, false, false);
        newQuote.status = 'Draft';
        newQuote.Is_Locked__c = false;
        newQuote.Original_Name__c = oldQuote.Name;
        newQuote.SubmittalDocumentVersion__c = 0;
        newQuote.ScopeDocumentVersion__c = 0;
        newQuote.QuoteDocumentVersion__c = 0;
        newQuote.Scope_File_Name__c = null;
        newQuote.Quote_FileName__c = null;
        insert newQuote;*/
        if(newQuote != null && newQuote.Id != null) {
            newQuote.Original_Name__c = newQuote.Name;
            update newQuote;
            //Database.executeBatch(new createFolderForQuote(New Set<Id>{newQuote.Id}) );
        }
        cloneGroups(newQuote.Id);
        
        PageReference pr = new PageReference('/'+newQuote.Id);
        pr.setRedirect(true);
        return pr;
    
    }
    
    public void cloneGroups(Id newQuoteId){
        
        List<Product_Select__c> lstQuoteLineItems = [SELECT Descriptions__c,Family__c,Freight__c,List_Price__c,
                                                        Margin_Percentage__c,Multiplier__c,Original_Product_Name__c,
                                                        Product_Code__c,Product_Group__c,Product_Name__c,
                                                        Quantity__c,Quote__c,Sales_Price__c,Total_Price__c,T_LBS__c,LBS__c,Tag__c,Extended_Cost__c,                                                               
                                                        Hide_Pricing__c,Hide_Line__c,Unit_Cost__c,Hide_Code__c,Row_Index__c,Page_Break__c,Is_Freight_Override__c,
                                                        Sale_Type__c,Manufacturer__c,Release_pick__c,CR__c,ProductId__c       
                                                        FROM Product_Select__c
                                                        WHERE Quote__c =: quoteId];
        
        List<Product_Select__c> lstQuoteLineItemsInsert = new List<Product_Select__c>();
        Set<Id> setChildProductGroupId = new Set<Id>();
        
        for(Product_Select__c qli : lstQuoteLineItems){
            Product_Select__c newQuoteLineItem = qli.clone(false,false,false,false);
            newQuoteLineItem.Quote__c = newQuoteId;
            newQuoteLineItem.IsBillingCreated__c = false;
            setChildProductGroupId.add(qli.Product_Group__c);
            lstQuoteLineItemsInsert.add(newQuoteLineItem);
        }
        
        List<Product_Group__c> lstProductGroups = [Select Id,Name, Parent_Product_Group__r.Name, Parent_Product_Group__c,Total_Line_Items__c,Total_Sub_Groups__c,
                                                     Hide_Pricing__c,Total_Extended_Cost__c,Hide_Base_Bid_Total__c,Total_Group_Extended_Cost__c, Index__c,
                                                     Hide_Code__c, Hide_Amount__c, Hide_Line__c,Quantity_Total__c,Total_Group_Freight__c,Total_Freight__c,Hide_Quantity__c,
                                                     Release_Number__c,Grand_Quantity_Total__c,Page_Break__c
                                                     FROM Product_Group__c
                                                     WHERE Quote__c =: quoteId];

        List<Product_Group__c>  lstProductGroupsInsert = new List<Product_Group__c>();                                   
        
        for(Product_Group__c pg : lstProductGroups){
            Product_Group__c newProductGroup = pg.clone(false,false,false,false);
            newProductGroup.Quote__c = newQuoteId;
            newProductGroup.Cloned_From__c = pg.Id;
            lstProductGroupsInsert.add(newProductGroup);
        }
        
        insert lstProductGroupsInsert;
        
        Map<Id, Id> mapParentChildProductGroup = new Map<Id, Id>();
        
        for(Product_Group__c pg : lstProductGroupsInsert){
            mapParentChildProductGroup.put(pg.Cloned_From__c,pg.Id);
        }
        
        for(Product_Select__c qli : lstQuoteLineItemsInsert){
            qli.Product_Group__c = mapParentChildProductGroup.get(qli.Product_Group__c);
        }
        
        for(Product_Group__c pg : lstProductGroupsInsert){
            if(pg.Parent_Product_Group__c != null){
                pg.Parent_Product_Group__c = mapParentChildProductGroup.get(pg.Parent_Product_Group__c);
            }
        }
        
        List<Addition_Deduction__c> lstAddDeduct = [Select Id, Amount__c, Details__c, Type__c
                                            FROM Addition_Deduction__c
                                            WHERE Quote__c =: quoteId];
        
        List<Addition_Deduction__c> lstInsertAddDeduct = new List<Addition_Deduction__c>();
        
        for(Addition_Deduction__c ad : lstAddDeduct){
            Addition_Deduction__c newAddDeduct = ad.clone(false,false,false,false);
            newAddDeduct.Quote__c = newQuoteId;
            lstInsertAddDeduct.add(newAddDeduct);
        }
        
        insert lstInsertAddDeduct;
        insert lstQuoteLineItemsInsert;
        update lstProductGroupsInsert;
    }
    
    public String getQuoteQuery(){
        
        String expr = '';
        
        Schema.DescribeSObjectResult a_desc = Quote.sObjectType.getDescribe();
        Map<String, Schema.SObjectField> a_fields = a_desc.fields.getMap();
        
        for(Schema.sObjectField fld:a_fields.values()){
            Schema.DescribeFieldResult fieldResult = fld.getDescribe(); 
            if(fieldResult.getName() == 'LastViewedDate' || fieldResult.getName() == 'LastReferencedDate') {
                Continue;
            }
            if(expr == ''){
                expr += fld;
            }
            else{
                expr += ', ' + fld ;
            }
            
        }
        expr += ', opportunity.Bid_Date__c';
        String qry = 'Select ' + expr + ' from Quote WHERE Id =' + '\''  + quoteId + '\'' ;
        system.debug(qry +'== query String');
        return qry;
    }
    public PageReference Cancel(){
        
        if (newQuote != null && newQuote.Id != null) {
            delete newQuote;
        }
        
        PageReference pr = new Pagereference('/' + quoteId);
        pr.setRedirect(true);
        return pr;
    }
    
}