force-app/main/default/objects/Addition_Deduction__c/Addition_Deduction__c.object-meta.xml
<CustomObject>
    <label>Addition/Deduction</label>
    <nameField>
        <displayFormat>AD-{00000}</displayFormat>
        <label>Addition/Deduction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AdditionDeductions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Addition_Deduction__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>AdditionDeductions</relationshipLabel>
    <relationshipName>AdditionDeductions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Active_Financial_Quote__c.field-meta.xml
<CustomField>
    <fullName>Active_Financial_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Financial Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunities (Active Financial Quote)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/B_R_BillingLine_Total__c.field-meta.xml
<CustomField>
    <fullName>B_R_BillingLine_Total__c</fullName>
    <description>From project financials tab INVOICED -(BUY/RESELL)
BUY/RESELL</description>
    <label>INVOICED-BUY/RESELL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billings__c.field-meta.xml
<CustomField>
    <fullName>Billings__c</fullName>
    <description>The total Billing value made against this opportunity</description>
    <inlineHelpText>The total Billing value made against this opportunity</inlineHelpText>
    <label>Billings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/C_R_BillingLine_Total__c.field-meta.xml
<CustomField>
    <fullName>C_R_BillingLine_Total__c</fullName>
    <description>From project financials tab INVOICED -(COMMISSION/REBATE)
COMMISSION/REBATE</description>
    <label>INVOICED-COMMISSION/REBATE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Freight__c.field-meta.xml
<CustomField>
    <fullName>Freight__c</fullName>
    <inlineHelpText>What freight option will this order be using?</inlineHelpText>
    <label>Freight</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PPA</fullName>
            </value>
            <value>
                <fullName>Collect</fullName>
            </value>
            <value>
                <fullName>FFA</fullName>
            </value>
            <value>
                <fullName>3rd-Party Logistics</fullName>
            </value>
            <value>
                <fullName>Customer Pick Up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MostRecentBillingDate__c.field-meta.xml
<CustomField>
    <fullName>MostRecentBillingDate__c</fullName>
    <label>Date of Most Recent Billing</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{YY}-{0000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Paid_Billings__c.field-meta.xml
<CustomField>
    <fullName>Paid_Billings__c</fullName>
    <label>Paid Billings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PO_Total__c.field-meta.xml
<CustomField>
    <fullName>PO_Total__c</fullName>
    <label>PO Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sync_Quote__c.field-meta.xml
<CustomField>
    <fullName>Sync_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sync Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.OpportunityId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <inlineHelpText>Add a &quot;tag&quot; or &quot;attention to&quot; for the shipping address if required.</inlineHelpText>
    <label>Tag</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Base_Bid_Total_Quote__c.field-meta.xml
<CustomField>
    <fullName>Total_Base_Bid_Total_Quote__c</fullName>
    <inlineHelpText>This is the total base bid for the quote currently synced with this opportunity.</inlineHelpText>
    <label>Base Bid Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Extended_Cost_Quote__c.field-meta.xml
<CustomField>
    <fullName>Total_Extended_Cost_Quote__c</fullName>
    <label>Total Extended Cost (Quote)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Project_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin__c</fullName>
    <label>Total Project Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Hide_Code__c.field-meta.xml
<CustomField>
    <fullName>Hide_Code__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Code</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Hide_Line__c.field-meta.xml
<CustomField>
    <fullName>Hide_Line__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Line</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Hide_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Hide_Pricing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Pricing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>Index</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Page_Break__c.field-meta.xml
<CustomField>
    <fullName>Page_Break__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Page Break</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Product Groups</relationshipLabel>
    <relationshipName>Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/Product_Select__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Select__c/fields/Descriptions__c.field-meta.xml
<CustomField>
    <fullName>Descriptions__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Extended_Cost__c.field-meta.xml
<CustomField>
    <fullName>Extended_Cost__c</fullName>
    <label>Extended Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <description>DNU for anything.</description>
    <label>Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Freight__c.field-meta.xml
<CustomField>
    <fullName>Freight__c</fullName>
    <label>Freight</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Is_Freight_Override__c.field-meta.xml
<CustomField>
    <fullName>Is_Freight_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Freight Override?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/LBS__c.field-meta.xml
<CustomField>
    <fullName>LBS__c</fullName>
    <label>LBS</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Margin_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Margin_Percentage__c</fullName>
    <label>Margin Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Multiplier__c</fullName>
    <label>Multiplier</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Original_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Original_Product_Name__c</fullName>
    <label>Original Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>ProductSelects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Row_Index__c.field-meta.xml
<CustomField>
    <fullName>Row_Index__c</fullName>
    <label>Row Index</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B/R</fullName>
            </value>
            <value>
                <fullName>D/S</fullName>
            </value>
            <value>
                <fullName>C/R</fullName>
            </value>
            <value>
                <fullName>P/T</fullName>
            </value>
            <value>
                <fullName>LAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/T_LBS__c.field-meta.xml
<CustomField>
    <fullName>T_LBS__c</fullName>
    <label>T-LBS</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <formula>Opportunity.Opportunity_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Quote_FileName__c.field-meta.xml
<CustomField>
    <fullName>Quote_FileName__c</fullName>
    <label>Current Quote FileName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteDocumentVersion__c.field-meta.xml
<CustomField>
    <fullName>QuoteDocumentVersion__c</fullName>
    <description>Version of quote document as pdf</description>
    <label>Quote Document Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Scope_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Scope_File_Name__c</fullName>
    <label>Current Scope FileName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ScopeDocumentVersion__c.field-meta.xml
<CustomField>
    <fullName>ScopeDocumentVersion__c</fullName>
    <description>Scope Document Latest Version Number</description>
    <label>Scope Document Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/SubmittalDocumentVersion__c.field-meta.xml
<CustomField>
    <fullName>SubmittalDocumentVersion__c</fullName>
    <description>Submittal Document Latest Version</description>
    <label>Submittal Document Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Project_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin__c</fullName>
    <label>Total Project Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CloneOpportunityController.cls
public class CloneOpportunityController {



    
    public Id opportunityId {get;set;}
    public static boolean bulkQuoteInsert = true;
    public Opportunity opp {get;set;}
    public List<wrapperQuoteList> wrapQuoteList {get; set;}
    public Boolean showQuote{get;set;}
    public Set<Id> selectedQuoteIds = new set<Id>();
    public Boolean quotesNotAvailable {get;set;}
    
    public CloneOpportunityController(ApexPages.StandardController controller) {
        showQuote = false;
        opportunityId = ApexPages.currentPage().getParameters().get('Id');
        opp = getOpportunity(opportunityId); 
        wrapQuoteList = getQuoteList(opportunityId);

    }
    
    public CloneOpportunityController(){
        /*showQuote = false;
        opportunityId = ApexPages.currentPage().getParameters().get('Id');
        opp = getOpportunity(opportunityId); 
        wrapQuoteList = getQuoteList(opportunityId);*/
    }
    public void showQuote() {
        showQuote = true;
        system.debug('size@@='+wrapQuoteList); 
        if(wrapQuoteList != null && wrapQuoteList.size() > 0) {
            for(wrapperQuoteList wrap : wrapQuoteList) {
                wrap.newQuote.Name = opp.Name;
            }   
        } else {
            quotesNotAvailable = true;
        }
    }
    public void hideQuote() {
        showQuote = false;
    }
    public PageReference cloneOpportunityWithChildObjects(){
        selectedQuoteIds = new Set<Id>();
        Id newOpportunityId = cloneOpportunity();
        
        PageReference pr = new PageReference('/'+newOpportunityId);
        pr.setRedirect(true);
        return pr;
    }
    
    public Id cloneOpportunity(){
         
        Opportunity cloneOpportunity = opp.clone(false, false, false, false);
        cloneOpportunity.Total_Base_Bid_Total_Quote__c = 0;
        cloneOpportunity.Total_Extended_Cost_Quote__c  = 0;
        cloneOpportunity.Total_Project_Margin__c = 0;
        cloneOpportunity.Sync_Quote__c = null;
        cloneOpportunity.Active_Financial_Quote__c = null;    
        cloneOpportunity.Name = cloneOpportunity.Name;
        cloneOpportunity.StageName = 'Bidding';

        // reset commision report related fields
        cloneOpportunity.Billings__c = 0;
        cloneOpportunity.MostRecentBillingDate__c = null;
        cloneOpportunity.B_R_BillingLine_Total__c = 0;
        cloneOpportunity.C_R_BillingLine_Total__c = 0;   
        cloneOpportunity.Paid_Billings__c = 0;
        cloneOpportunity.PO_Total__c = 0;

        //UtilitySharePointToSFIntegration.quoteBulkInsertContext = true;
        insert cloneOpportunity;
        
        cloneQuotes(cloneOpportunity.Id);
        
        return cloneOpportunity.Id;
    }
    
    public void cloneQuotes(Id newOpportunityId){
        //List<Quote> lstQuote = getQuotes();
        Opportunity newOpportunity = [SELECT Id,
                                            Opportunity_Number__c 
                                            FROM Opportunity WHERE Id = :newOpportunityId];
        List<Quote> lstQuote = new List<Quote>();  
        system.debug(wrapQuoteList);
        if(wrapQuoteList != null && wrapQuoteList.size() > 0) {
            for(wrapperQuoteList quoteWrap : wrapQuoteList) {
                
                if (quoteWrap!= null && quoteWrap.isSelected && quoteWrap.newQuote != null) {
                    Quote newQuoteToInsert = quoteWrap.newQuote;
                    newQuoteToInsert.Name = newOpportunity.Opportunity_Number__c + ' - ' + newQuoteToInsert.Name; 
                    newQuoteToInsert.OpportunityId = newOpportunity.Id;
                    newQuoteToInsert.status = 'Draft';
                    newQuoteToInsert.SubmittalDocumentVersion__c = 0;
                    newQuoteToInsert.ScopeDocumentVersion__c = 0;
                    newQuoteToInsert.QuoteDocumentVersion__c = 0;
                    newQuoteToInsert.Scope_File_Name__c = null;
                    newQuoteToInsert.Quote_FileName__c = null;
                    
                    insert newQuoteToInsert;
                    cloneGroups(quoteWrap.oldQuote.Id, newQuoteToInsert.Id);
                }
            }       
        }

        /*for(Quote q : lstQuote){
            Quote newQuote = q.clone(false, false, false, false);
            newQuote.Name = newQuote.Name + ' Clone';
            newQuote.OpportunityId = newOpportunityId;
            newQuote.status = 'Draft';
            insert newQuote;
            
            cloneGroups(q.Id, newQuote.Id);
        }*/

        
        //Database.executeBatch(new createfolderForOpportunity(newOpportunityId) );    
    }
    
    public void cloneGroups(Id OldQuoteId, Id newQuoteId){
        
        List<Product_Select__c> lstQuoteLineItems = [SELECT Descriptions__c,Family__c,Freight__c,List_Price__c,
                                                        Margin_Percentage__c,Multiplier__c,Original_Product_Name__c,
                                                        Product_Code__c,Product_Group__c,Product_Name__c,
                                                        Quantity__c,Quote__c,Sales_Price__c,Total_Price__c,T_LBS__c,LBS__c,Tag__c,Extended_Cost__c,                                                               
                                                        Hide_Pricing__c,Hide_Line__c,Unit_Cost__c,Hide_Code__c,Row_Index__c,Page_Break__c,Is_Freight_Override__c,
                                                        Sale_Type__c,Manufacturer__c,Release_pick__c,CR__c ,ProductId__c      
                                                        FROM Product_Select__c
                                                        WHERE Quote__c =: OldQuoteId];
        
        List<Product_Select__c> lstQuoteLineItemsInsert = new List<Product_Select__c>();
        Set<Id> setChildProductGroupId = new Set<Id>();
        
        for(Product_Select__c qli : lstQuoteLineItems){
            Product_Select__c newQuoteLineItem = qli.clone(false,false,false,false);
            newQuoteLineItem.Quote__c = newQuoteId;
            newQuoteLineItem.IsBillingCreated__c = false;
            setChildProductGroupId.add(qli.Product_Group__c);
            lstQuoteLineItemsInsert.add(newQuoteLineItem);
        }
        
        List<Product_Group__c> lstProductGroups = [Select Id,Name, Parent_Product_Group__r.Name, Parent_Product_Group__c,Total_Line_Items__c,Total_Sub_Groups__c,
                                                     Hide_Pricing__c,Total_Extended_Cost__c,Hide_Base_Bid_Total__c,Total_Group_Extended_Cost__c, Index__c,
                                                     Hide_Code__c, Hide_Amount__c, Hide_Line__c,Quantity_Total__c,Total_Group_Freight__c,Total_Freight__c,Hide_Quantity__c,
                                                     Release_Number__c,Grand_Quantity_Total__c,Page_Break__c
                                                     FROM Product_Group__c
                                                     WHERE Quote__c =: OldQuoteId];

        List<Product_Group__c>  lstProductGroupsInsert = new List<Product_Group__c>();                                   
        
        for(Product_Group__c pg : lstProductGroups){
            Product_Group__c newProductGroup = pg.clone(false,false,false,false);
            newProductGroup.Quote__c = newQuoteId;
            newProductGroup.Cloned_From__c = pg.Id;
            lstProductGroupsInsert.add(newProductGroup);
        }
        
        insert lstProductGroupsInsert;
        
        Map<Id, Id> mapParentChildProductGroup = new Map<Id, Id>();
        
        for(Product_Group__c pg : lstProductGroupsInsert){
            mapParentChildProductGroup.put(pg.Cloned_From__c,pg.Id);
        }
        
        for(Product_Select__c qli : lstQuoteLineItemsInsert){
            qli.Product_Group__c = mapParentChildProductGroup.get(qli.Product_Group__c);
        }
        
        for(Product_Group__c pg : lstProductGroupsInsert){
            if(pg.Parent_Product_Group__c != null){
                pg.Parent_Product_Group__c = mapParentChildProductGroup.get(pg.Parent_Product_Group__c);
            }
        }
        
        List<Addition_Deduction__c> lstAddDeduct = [Select Id, Amount__c, Details__c, Type__c
                                            FROM Addition_Deduction__c
                                            WHERE Quote__c =: OldQuoteId];
        
        List<Addition_Deduction__c> lstInsertAddDeduct = new List<Addition_Deduction__c>();
        
        for(Addition_Deduction__c ad : lstAddDeduct){
            Addition_Deduction__c newAddDeduct = ad.clone(false,false,false,false);
            newAddDeduct.Quote__c = newQuoteId;
            lstInsertAddDeduct.add(newAddDeduct);
        }
        
        insert lstInsertAddDeduct;
        insert lstQuoteLineItemsInsert;
        update lstProductGroupsInsert;
    }
    
    public List<Quote> getQuotes(){
        
        String qryString = buildQuery('Quote','OpportunityId' ,opportunityId);
        
        List<Quote> lstQuote = Database.query(qryString);
        
        return lstQuote;
    }
    
    public Opportunity getOpportunity(Id oppId){
        String qryString = buildQuery('Opportunity','Id' ,opportunityId);
        
        Opportunity opp = Database.query(qryString);
        
        return opp;
    }
    
     public String buildQuery(String selectedObject, String whereField, Id selectedObjectId){
        
        Map <String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe(); 
        Map <String, Schema.SObjectField> a_fields = schemaMap.get(selectedObject).getDescribe().fields.getMap(); 
         
        String expr = '';
        
        for(Schema.sObjectField fld:a_fields.values()){
            if(expr == ''){
                expr += fld;
            }
            else{
                expr += ', ' + fld ;
            }
            
        }
        
        String qry = 'Select ' + expr + ' from ' + selectedObject + ' WHERE ' + whereField + '=' + '\''  + selectedObjectId + '\'' ;
        if (selectedObject == 'Quote' && selectedQuoteIds.size() > 0) {
            set<Id> quoteIds = new set<Id>();
            
            for(wrapperQuoteList wrapQuote : wrapQuoteList) {
                if(wrapQuote.isSelected) {
                    quoteIds.add(wrapQuote.oldQuote.Id);    
                }
            }
            qry += ' AND OpportunityId IN :selectedQuoteIds'; 
        }
        return qry;
    }
    
    public List<wrapperQuoteList> getQuoteList(Id opportunityId) {
        List<wrapperQuoteList> quoteList = new List<wrapperQuoteList>();
        List<Quote> lstQuote = getQuotes();
        for(Quote quote : lstQuote) {
            quoteList.add(new wrapperQuoteList(quote));                     
        }
        if(!quoteList.isEmpty()) {
            return quoteList;   
        }
        
        return null;
    }
    
    public PageReference doCancel() {
        PageReference pr = new PageReference('/'+opportunityId);
        pr.setRedirect(true);
        return pr;      
    }
    public class wrapperQuoteList {
        public Boolean isSelected {get;set;}
        public Quote oldQuote {get;set;}
        public Quote newQuote {get;set;}
        public wrapperQuoteList(Quote q) {
            oldQuote = q;
            newQuote = q.clone(false, false, false, false);
            isSelected = true;  
        }
    
    } 
    
}