force-app/main/default/objects/PM_Tool_Send_Email_History__c/PM_Tool_Send_Email_History__c.object-meta.xml
<CustomObject>
    <label>PM Tool Send Email History</label>
    <nameField>
        <displayFormat>SEH-{0000000000}</displayFormat>
        <label>PM Tool Send Email History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SendEmails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PM_Tool_Send_Email_History__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>SendEmails</relationshipLabel>
    <relationshipName>SendEmails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_Tool_Send_Email_History__c/fields/Schedule_To__c.field-meta.xml
<CustomField>
    <fullName>Schedule_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SendEmails</relationshipLabel>
    <relationshipName>SendEmails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Schedule_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_End_Date__c</fullName>
    <label>Schedule End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Schedule_On__c.field-meta.xml
<CustomField>
    <fullName>Schedule_On__c</fullName>
    <label>Schedule On</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Schedule_To__c.field-meta.xml
<CustomField>
    <fullName>Schedule_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Schdule_To__c/Project_Schdule_To__c.object-meta.xml
<CustomObject>
    <label>Project Schdule To</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Project Schdule To Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Schdule_To__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Schdule_To__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Schdule_To__c/fields/Schedule_Type__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Type__c</fullName>
    <label>Schedule Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Schdule_To__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/debugScheduledEmailProjectTool.cls
global class debugScheduledEmailProjectTool implements Schedulable {
    public contact con;
    global debugScheduledEmailProjectTool (){
               
    }
    
    global String getOrgWideEmailAddressId(){
        
        String fromAddressId = null;
        
        List<OrgWideEmailAddress> lstOrgWideEmailAddress = [SELECT Id, Address,DisplayName 
                                                            FROM OrgWideEmailAddress
                                                            WHERE Address = 'info@midwestmachinery.net'];
        if(!lstOrgWideEmailAddress.isEmpty()){
            fromAddressId = lstOrgWideEmailAddress[0].Id;
        }
        
        return fromAddressId;
    }
    
    global void execute(SchedulableContext ctx) {
        
        con = [SELECT id from Contact where lastName = 'debug PM scheduleTp'];
        Datetime dt;
        /*
        if(con.pi__created_date__c == null) {
            dt = System.now();
        } else {
            dt = con.pi__created_date__c;
        }
        */
        
        String todayDay = dt.format('EEEE');
        
        List<Project__c> lstProjects = [Select Id, Schedule_To__c, Schedule_End_Date__c, Schedule_On__c,
                                        Owner.Email,
                                        (Select Contact__c, User__c, Contact__r.Email, User__r.Email, Schedule_Type__c
                                        FROM Schedules__r)
                                        FROM Project__c
                                        WHERE Schedule_On__c =: todayDay
                                        AND Schedule_End_Date__c >= TODAY];
        
        String fromEmailAddressId = getOrgWideEmailAddressId();
        
        EmailTemplate et = [Select Id From EmailTemplate WHERE developerName =: 'Stage_Startup_and_Warranty'];
        
        List<Messaging.SingleEmailMessage> lstEmailToSend = new List<Messaging.SingleEmailMessage>();
                                                
        for(Project__c project : lstProjects) {
            List<Project_Schdule_To__c> lstScheduleTo = project.Schedules__r;
            lstEmailToSend.add(sendEmail(et.Id, project.Id, lstScheduleTo, 'nilesh.badrakia@gmail.com', fromEmailAddressId));
        }
        
        if(lstEmailToSend.size() > 0){
            Messaging.sendemailResult[] r = Messaging.sendemail(lstEmailToSend);
            List<PM_Tool_Send_Email_History__c> lstSendEmailFailHistory = new List<PM_Tool_Send_Email_History__c>();
            
            for(Messaging.sendemailResult result : r){
                if(!result.IsSuccess()){
                    for(Messaging.sendEmailError error : result.getErrors()){
                        PM_Tool_Send_Email_History__c history = new PM_Tool_Send_Email_History__c();
                        history.Error_Message__c = error.getMessage();
                        history.Schedule_To__c = error.getTargetObjectId();
                        lstSendEmailFailHistory.add(history);
                    }
                    
                    
                }
            }
            
            if(!lstSendEmailFailHistory.isEmpty()){
                insert lstSendEmailFailHistory;
            }
        }
        
        
    }
    
    global Messaging.SingleEmailMessage sendEmail(String emailTemplateId, String projectId, List<Project_Schdule_To__c> lstScheduleTo, string ccEmail, string fromEmailId){
        
        List<String> lstCCEmail = new List<String>();
        lstCCEmail.add('nilesh.badrakia@gmail.com');
        
        List<String> lstEmailsTo = new List<String>();
        lstEmailsTo.add('vadariasagar@gmail.com');

        
        
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        
        message.setTemplateID(emailTemplateId);
        message.setCcAddresses(lstCCEmail);
        message.setTargetObjectID(con.Id);
        message.setToAddresses(lstEmailsTo);
        message.setWhatId(projectId);
        message.setOrgWideEmailAddressId(fromEmailId);
        
        return message;
        
    }
    
}