force-app/main/default/objects/AcctSeedERP__Purchase_Order__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Midwest Machinery STL</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery KC</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery OK</fullName>
            </value>
            <value>
                <fullName>Engineered Products</fullName>
            </value>
            <value>
                <fullName>MaRRS</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
            <value>
                <fullName>Spark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order__c/fields/Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Number__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+ Sales_Order__c ,  Sales_Order__r.Sales_Order_Number__c , &apos;_blank&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Sales_Order__c/fields/Customer_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_Number__c</fullName>
    <label>Customer PO Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Sales_Order__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
    <relationshipLabel>Sales Order</relationshipLabel>
    <relationshipName>Sales_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Sales_Order__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Sales Order</relationshipLabel>
    <relationshipName>Sales_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>Product_Select__c</referenceTo>
    <relationshipLabel>Sales Order Line</relationshipLabel>
    <relationshipName>Sales_Order_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/fields/Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Number__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+  AcctSeedERP__Sales_Order__c  ,  AcctSeedERP__Sales_Order__r.Sales_Order_Number__c  , &apos;_blank&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/Product_Select__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Select__c/fields/Descriptions__c.field-meta.xml
<CustomField>
    <fullName>Descriptions__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>ProductSelects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PurchaseOrderPDFCtrl.cls
public with sharing class PurchaseOrderPDFCtrl {
    
    public String salesOrderName{get;set;}
    public string officeName{get;set;}
    public Boolean withoutQuote{get;set;}
    public String salesOrderPONumber{get;set;}
    //public Boolean isEPUser {get;set;}
    public AcctSeedERP__Purchase_Order__c objPurchaseOrder{get;set;}
    public List<AcctSeedERP__Sales_Order_Line__c> lstLineItems{get;set;}
    public List<AcctSeedERP__Purchase_Order_Line__c> poLineItems{get;set;}

    public PurchaseOrderPDFCtrl(ApexPages.StandardController controller) {

        //withQuote = Boolean.valueOf(apexpages.currentpage().getparameters().get('isWithoutQuote'));
        objPurchaseOrder = [SELECT Id, Sales_Order__r.Name, Sales_Order__r.Sales_Order_Number__c,
                                    Sales_Order__c,
                                    Sales_Order__r.Quote__c, Sales_Order__r.Customer_PO_Number__c,
                                    Sales_Order__r.AcctSeedERP__Opportunity__r.Office__c,
                                    Office__c
                            FROM AcctSeedERP__Purchase_Order__c 
                            WHERE Id =: controller.getId()];
        //isEPUser = UtilitySharePointToSFIntegration.isCurrentUserFromEngineeredProducts();
        salesOrderPONumber = objPurchaseOrder.Sales_Order__r.Customer_PO_Number__c;
        if (objPurchaseOrder.Sales_Order__c != null) {
            officeName = objPurchaseOrder.Sales_Order__r.AcctSeedERP__Opportunity__r.Office__c;
        } else if(objPurchaseOrder.Office__c != null){
            officeName = objPurchaseOrder.Office__c;
        } else {
            officeName = 'Midwest Machinery STL';
        }
        if(objPurchaseOrder.Sales_Order__c == null) {
            withoutQuote = true;
            poLineItems = [SELECT Id,
                                AcctSeedERP__Product__r.Name,
                                AcctSeedERP__Product__r.ProductCode,
                                AcctSeedERP__Quantity__c,
                                AcctSeedERP__Unit_Price__c,
                                AcctSeedERP__Total__c
                            FROM AcctSeedERP__Purchase_Order_Line__c
                            WHERE AcctSeedERP__Purchase_Order__c = :objPurchaseOrder.Id];
        } else {
            withoutQuote = false;
        }
        if(withoutQuote == false) {
            salesOrderName = (objPurchaseOrder.Sales_Order__r.Sales_Order_Number__c == null || objPurchaseOrder.Sales_Order__r.Sales_Order_Number__c == '') 
                                ? objPurchaseOrder.Sales_Order__r.Name 
                                : objPurchaseOrder.Sales_Order__r.Sales_Order_Number__c;

            Map<Id, AcctSeedERP__Purchase_Order_Line__c> mapPurchaseOrder = new Map<Id, AcctSeedERP__Purchase_Order_Line__c>([SELECT Id
                                                                                                                                FROM AcctSeedERP__Purchase_Order_Line__c
                                                                                                                                WHERE AcctSeedERP__Purchase_Order__c = :controller.getId()]);

            lstLineItems = [SELECT Id,
                                    Name,
                                    AcctSeedERP__Purchase_Order_Line__r.Name,
                                    AcctSeedERP__Purchase_Order_Line__r.AcctSeedERP__Quantity_Received__c,
                                    AcctSeedERP__Purchase_Order_Line__r.AcctSeedERP__Total__c,
                                    AcctSeedERP__Purchase_Order_Line__r.AcctSeedERP__Unit_Price__c,
                                    AcctSeedERP__Product__r.ProductCode,
                                    AcctSeedERP__Quantity_Ordered__c,
                                    Quote_Line_Item__r.Descriptions__c,
                                    AcctSeedERP__Product__r.Name
                                FROM AcctSeedERP__Sales_Order_Line__c
                                WHERE AcctSeedERP__Purchase_Order_Line__c IN :mapPurchaseOrder.keySet()];
        }
    }
        

    
}