force-app/main/default/objects/Approver__c/Approver__c.object-meta.xml
<CustomObject>
    <label>Approver</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Approver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approver__c/fields/ApproverId__c.field-meta.xml
<CustomField>
    <fullName>ApproverId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ApproverId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approver__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Submitted Expense Line</label>
    <nameField>
        <displayFormat>Ex-{00000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submitted Expense Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Amount__c</fullName>
    <label>Expense Amount ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Type__c.field-meta.xml
<CustomField>
    <fullName>Expense_Type__c</fullName>
    <label>Expense Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Building Repair/Maintenance</fullName>
            </value>
            <value>
                <fullName>Construction Vehicles expense/fuel</fullName>
            </value>
            <value>
                <fullName>Donations</fullName>
            </value>
            <value>
                <fullName>Education/Training</fullName>
            </value>
            <value>
                <fullName>Entertainment w/ Customers</fullName>
            </value>
            <value>
                <fullName>Entertainment w/Employee</fullName>
            </value>
            <value>
                <fullName>Entertainment w/Vendors</fullName>
            </value>
            <value>
                <fullName>Fuel</fullName>
            </value>
            <value>
                <fullName>Job-Related Materials/Expenses</fullName>
            </value>
            <value>
                <fullName>Marketing/Advertising</fullName>
            </value>
            <value>
                <fullName>Meals w/customers</fullName>
            </value>
            <value>
                <fullName>Meal w/Employees</fullName>
            </value>
            <value>
                <fullName>Meal w/Vendor</fullName>
            </value>
            <value>
                <fullName>Mileage - Sales Executives</fullName>
            </value>
            <value>
                <fullName>Office/Break Room Supplies</fullName>
            </value>
            <value>
                <fullName>Office Equipment/Computers</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Personal Car Mileage</fullName>
            </value>
            <value>
                <fullName>Postage/Shipping</fullName>
            </value>
            <value>
                <fullName>Professional Subscription/Dues</fullName>
            </value>
            <value>
                <fullName>Promotional shows/Products</fullName>
            </value>
            <value>
                <fullName>Public Transportation</fullName>
            </value>
            <value>
                <fullName>Seminar/Course fees/Conference</fullName>
            </value>
            <value>
                <fullName>Tolls</fullName>
            </value>
            <value>
                <fullName>Travel - Airfare</fullName>
            </value>
            <value>
                <fullName>Travel - Car Rental</fullName>
            </value>
            <value>
                <fullName>Travel - Hotel</fullName>
            </value>
            <value>
                <fullName>Travel - Meal</fullName>
            </value>
            <value>
                <fullName>Travel - Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Uber/Taxi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Log_A_Call__c.field-meta.xml
<CustomField>
    <fullName>Log_A_Call__c</fullName>
    <label>Log A Call</label>
    <referenceTo>LogACall__c</referenceTo>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company Expense</fullName>
            </value>
            <value>
                <fullName>Personal Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Submit_Request__c.field-meta.xml
<CustomField>
    <fullName>Submit_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submit Request</label>
    <referenceTo>Submit_Request__c</referenceTo>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Vendor_Or_Venue__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Or_Venue__c</fullName>
    <label>Vendor Or Venue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogACall__c/LogACall__c.object-meta.xml
<CustomObject>
    <label>Log A Call</label>
    <nameField>
        <displayFormat>Call-{00000}</displayFormat>
        <label>Log A Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogACall__c/fields/Account_Names__c.field-meta.xml
<CustomField>
    <fullName>Account_Names__c</fullName>
    <label>Account Names</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LogCalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Contact_Names__c.field-meta.xml
<CustomField>
    <fullName>Contact_Names__c</fullName>
    <label>Contact Names</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Amount__c</fullName>
    <description>Total of expense Amount</description>
    <label>Expense Amount</label>
    <summarizedField>Expense__c.Expense_Amount__c</summarizedField>
    <summaryForeignKey>Expense__c.Log_A_Call__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Mileage_Traveled__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Traveled__c</fullName>
    <label>Mileage Traveled</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Mileage_Type__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Type__c</fullName>
    <label>Mileage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Car Allowance</fullName>
                <default>true</default>
                <label>Car Allowance</label>
            </value>
            <value>
                <fullName>No Car Allowance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Type_of_Call__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Call__c</fullName>
    <label>Type of Call</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client Office Visit</fullName>
            </value>
            <value>
                <fullName>End User Visit</fullName>
            </value>
            <value>
                <fullName>Entertain (Hpy Hr, Glf, Gms)</fullName>
            </value>
            <value>
                <fullName>Expense Only</fullName>
            </value>
            <value>
                <fullName>Factory Visit (Travel)</fullName>
            </value>
            <value>
                <fullName>Industry Event (Ashrae etc.)</fullName>
            </value>
            <value>
                <fullName>Meal</fullName>
            </value>
            <value>
                <fullName>Site Visit (Project Related)</fullName>
            </value>
            <value>
                <fullName>Training (L-N-L, Seminar)</fullName>
            </value>
            <value>
                <fullName>Factory Visit (Local)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Submit_Request__c/Submit_Request__c.object-meta.xml
<CustomObject>
    <label>Submit Request</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Submit Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submit Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Submit_Request__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Submit_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Submit_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Submit_Request__c/fields/Total_Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Expense_Amount__c</fullName>
    <label>Total Expense Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/MonthlyExpenseReportCtrlTest.cls
@isTest
public with sharing class MonthlyExpenseReportCtrlTest 
{
    @testSetup
    static void setup(){
         //ExpenseReportController
         final String PERSONAL_EXPENSE = 'Personal Expense';
         final String COMPANY_EXPENSE = 'Company Expense';
         final String TOLLS = 'Tolls';
         final String TRAVEL_HOTEL = 'Travel - Hotel';
         final String TRAVEL_MEAL = 'Travel - Meal';
         final String UBER_TAXI = 'Uber/Taxi';
         final String PARKING = 'Parking';
         final String DONATIONS = 'Donations';
        List<String> paymentType = new List<String>{PERSONAL_EXPENSE, COMPANY_EXPENSE};
        List<String> ExpenseType = new list<String>{TOLLS,TRAVEL_HOTEL,TRAVEL_MEAL,UBER_TAXI,PARKING,DONATIONS};

        Date createDate = Date.newInstance(System.today().year(), System.today().month(), 1);
        
        //MonthlyExpenseReportCtrl
        LogACall__c testLogcall = new LogACall__c();
        testLogcall.Type_of_Call__c = 'Meal';
        testLogcall.Mileage_Type__c ='Car Allowance';
        testLogcall.Mileage_Traveled__c = 35;
        testLogcall.Account_Names__c = 'Test Billing';
        testLogcall.Contact_Names__c = 'Brian Gomski';
        testLogcall.Assigned_To__c = UserInfo.getUserId();
        testLogcall.CreatedDate = createDate;
        testLogcall.Event_Date__c = createDate;
        insert testLogcall;
        System.debug('LogAcall inserted: '+testLogcall);

        Expense__c expenseObj = new Expense__c ();
        expenseObj.Log_A_Call__c = testLogcall.Id;
        expenseObj.Vendor_Or_Venue__c = 'Test of expense';
        expenseObj.Expense_Type__c = ExpenseType[0];
        expenseObj.Expense_Amount__c = 100;
        expenseObj.Payment_Type__c = paymentType[0];
        expenseObj.CreatedDate = createDate;
        expenseObj.Expense_Date__c = createDate;
        insert expenseObj;

        List<Expense__c> lstTestEpense = new List<Expense__c>();
        for(Integer i=0 ; i<12 ; i++){
            Expense__c testPersonalExpense = new Expense__c ();
            testPersonalExpense.Log_A_Call__c = testLogcall.Id;
            testPersonalExpense.Vendor_Or_Venue__c = 'Test of expense';
            testPersonalExpense.Expense_Type__c = ExpenseType[math.mod(i,6)];
            testPersonalExpense.Expense_Amount__c = 100;
            testPersonalExpense.Payment_Type__c = paymentType[0];
            testPersonalExpense.CreatedDate = system.now().addMonths(-(Math.mod(i,12)));
            testPersonalExpense.Expense_Date__c = system.now().addMonths(-(Math.mod(i,12))).date();
            lstTestEpense.add(testPersonalExpense);

            Expense__c testCompanyExpense = new Expense__c ();
            testCompanyExpense.Log_A_Call__c = testLogcall.Id;
            testCompanyExpense.Vendor_Or_Venue__c = 'Test of expense';
            testCompanyExpense.Expense_Type__c = ExpenseType[math.mod(i,6)];
            testCompanyExpense.Expense_Amount__c = 100;
            testCompanyExpense.Payment_Type__c = paymentType[1];
            testCompanyExpense.CreatedDate = system.now().addMonths(-(Math.mod(i,12)));
            testCompanyExpense.Expense_Date__c = system.now().addMonths(-(Math.mod(i,12))).date();
            lstTestEpense.add(testCompanyExpense);
        }
        insert lstTestEpense;


        List<LogACall__c> listofLogACalls = new List<LogACall__c>();
        for (Integer i=0; i<12; i++){

            LogACall__c  LogcallTst = new LogACall__c();
            LogcallTst.Type_of_Call__c = 'Meal';
            LogcallTst.Mileage_Traveled__c = 70;
            LogcallTst.CreatedDate = system.now().addMonths(-(Math.mod(i,10)));
            LogcallTst.Event_Date__c = system.now().addMonths(-(Math.mod(i,10))).date();
            listofLogACalls.add(LogcallTst);
        }  
        insert listofLogACalls; 
        

        //For the declined record trigger code coverage 

        LogACall__c testLogcall1 = new LogACall__c();
        testLogcall1.Event_Date__c = Date.newInstance(2022, 06, 06);
        insert testLogcall1;

        Submit_Request__c newSR = new Submit_Request__c();
        insert newSR;

        newSR.Total_Expense_Amount__c = 150;
        newSR.Status__c = 'Requested';
        update newSR;

        Expense__c newExpense = new Expense__c();
        newExpense.Log_A_Call__c = testLogcall1.Id;
        newExpense.Expense_Date__c = Date.newInstance(2022, 06, 06);
        newExpense.Expense_Amount__c = 150;
        newExpense.Submit_Request__c = newSR.Id;
        insert newExpense;

        newSR.Status__c = 'Declined';
        update newSR;
        

    }

    @isTest static void testMonthYear()
    {
     
        MonthlyExpenseReportCtrl.getCurrentMonth();
        MonthlyExpenseReportCtrl.getCurrentYear();
    }
    @isTest static void testExpensemonthlyReport(){

        MonthlyExpenseReportCtrl.getAllExpensemonthlyReport('June', '2022' );
         
    }
    @isTest static void testgetExpenseAccounting(){
          
         MonthlyExpenseReportCtrl.getExpenseAccounting('June', '2022');   
    }
    @isTest static void testhandleSubmitRequest(){
 
           LogACall__c testLogcall = new LogACall__c();
           //testLogcall.Event_Date__c = Date.newInstance(2022, 06, 06);
           testLogcall.Type_of_Call__c = 'Client Office Visit';
           insert testLogcall;
   
           Expense__c newExpense1 = new Expense__c();
           newExpense1.Log_A_Call__c = testLogcall.Id;
           newExpense1.Expense_Date__c = Date.newInstance(2022, 06, 20);
           newExpense1.Expense_Amount__c = 500;
           insert newExpense1;

           Submit_Request__c newSR1 = new Submit_Request__c();
           newSR1.Status__c = 'Requested';
           insert newSR1;

           newExpense1.Submit_Request__c = newSR1.Id;
           update newExpense1;
   
           Approver__c newApp = new Approver__c();
           newApp.ApproverId__c = UserInfo.getUserId();
           insert newApp;
   
           Approver__c newAppSub = new Approver__c();
           newAppSub.User__c = UserInfo.getUserId();
           newAppSub.ApproverId__c = newApp.ApproverId__c;
           insert newAppSub;
   
           newSR1.Total_Expense_Amount__c = 250;
           newSR1.Approver__c = newAppSub.ApproverId__c;
           update newSR1;


        Approval.ProcessSubmitRequest testapproval = new Approval.ProcessSubmitRequest();
        testapproval.setComments('Submitting request for approval');
        testapproval.setObjectId(newSR1.Id);
        testapproval.setSubmitterId(UserInfo.getUserId());
        Approval.ProcessResult result1 = Approval.process(testapproval);
        system.debug('Test Approval process record :-' +result1);
        system.debug('Test Approval process record :-' +result1.getNewWorkitemIds().get(0));

        // Verify the results
        System.assert(result1.isSuccess());
        System.assertEquals('Pending', result1.getInstanceStatus(), 'Instance Status'+result1.getInstanceStatus());
        system.debug('status for approval::'+result1.getInstanceStatus());

        MonthlyExpenseReportCtrl.handleSubmitRequest(newSR1.Id , 'June','2022'); 
        MonthlyExpenseReportCtrl.getSubmittedExpenseApprovalData('June','2022');

        MonthlyExpenseReportCtrl.ExpenseRelatedList(result1.getNewWorkitemIds().get(0));
    }

    @isTest static void testSubmittedExpenseList(){
        LogACall__c testLogcall = new LogACall__c();
       // testLogcall.Event_Date__c = Date.newInstance(2022, 06, 06);
        testLogcall.Type_of_Call__c = 'Client Office Visit';
        insert testLogcall;

        Expense__c newExpense1 = new Expense__c();
        newExpense1.Log_A_Call__c = testLogcall.Id;
        newExpense1.Expense_Date__c = Date.newInstance(2022, 06, 20);
        insert newExpense1;

        Submit_Request__c newSR1 = new Submit_Request__c();
        newSR1.Total_Expense_Amount__c = 150;
        newSR1.Status__c = 'Requested';
        insert newSR1;

        newExpense1.Submit_Request__c = newSR1.Id;
        update newExpense1;

        MonthlyExpenseReportCtrl.getSubmittedExpenseList('All','2022');
    }

    @isTest
    static void testSetTaskForSecondApproval()
    {

        Submit_Request__c newSR1 = new Submit_Request__c();
        newSR1.Status__c = 'Requested';
        insert newSR1;

        Approver__c newApp = new Approver__c();
        newApp.ApproverId__c = UserInfo.getUserId();
        insert newApp;

        Approver__c newAppSub = new Approver__c();
        newAppSub.User__c = UserInfo.getUserId();
        newAppSub.ApproverId__c = newApp.ApproverId__c;
        insert newAppSub;

        newSR1.Total_Expense_Amount__c = 250;
        newSR1.Approver__c = newAppSub.ApproverId__c;
        update newSR1;

        Submit_Request__c SrRecord = [SELECT id,name FROM Submit_Request__c where id=: newSR1.Id];
        system.debug('SrRecord :- '+SrRecord);

        Task taskForApproval = new Task();
        taskForApproval.OwnerId = UserInfo.getUserId(); 
        taskForApproval.SR_Name__c = SrRecord.Name;
        taskForApproval.Subject = 'Approver task';
        taskForApproval.ActivityDate = Date.today().addDays(3);
        taskForApproval.Priority = 'Medium';
        insert taskForApproval;


        Approval.ProcessSubmitRequest testapproval = new Approval.ProcessSubmitRequest();
        testapproval.setComments('Submitting request for approval');
        testapproval.setObjectId(newSR1.Id);
        testapproval.setSubmitterId(UserInfo.getUserId());

        Approval.ProcessResult result = Approval.process(testapproval);
        system.debug('Test-22 Approval process record :-' +result);

        System.assert(result.isSuccess());
        System.assertEquals('Pending', result.getInstanceStatus(), 'Instance Status'+result.getInstanceStatus());
        system.debug('status for approvalhistory::' +result.getInstanceStatus());

        List<Id> newWorkItemIds = result.getNewWorkitemIds();
        system.debug('newWorkItemIds ::'+newWorkItemIds );

        Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest(); 
        req2.setComments('Approving request.');
        req2.setAction('Approve');
        req2.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        req2.setWorkitemId(newWorkItemIds.get(0));

        Approval.ProcessResult result2 =  Approval.process(req2);
        system.debug('update approval process id :- '+result2);

        // Verify the results
        System.assert(result2.isSuccess(), 'Result Status:'+result2.isSuccess());

        // System.assertEquals(
        //     'Approved', result2.getInstanceStatus(), 
        //     'Instance Status'+result2.getInstanceStatus());
        // system.debug('status for approvalhistory::' +result2.getInstanceStatus());

        ProcessInstanceStep approvalHistory = [SELECT Id ,ProcessInstance.TargetObjectId FROM ProcessInstanceStep 
                                                    WHERE ProcessInstance.TargetObjectId =:newSR1.Id
                                                    AND StepStatus = 'Approved' order by CreatedDate desc LIMIT 1];
        system.debug('approvalHistrory record '+approvalHistory);                                            
        
        ApprovalProcSendCustomTaskCtrl.setTaskForSecondApproval(approvalHistory.Id);      
        
    }

    //Below test is covered for ExpenseReport.page -- ExpenseReportController
    @isTest static void testExpenseReport(){
        ExpenseReportController testExpenseReport = new ExpenseReportController();
        List<String> ExpenseTypeString = testExpenseReport.getExpenseType();
        
    }

    
 
  
}