force-app/main/default/objects/Approver__c/Approver__c.object-meta.xml
<CustomObject>
    <label>Approver</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Approver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approver__c/fields/ApproverId__c.field-meta.xml
<CustomField>
    <fullName>ApproverId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ApproverId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approver__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Submitted Expense Line</label>
    <nameField>
        <displayFormat>Ex-{00000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submitted Expense Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Amount__c</fullName>
    <label>Expense Amount ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Log_A_Call__c.field-meta.xml
<CustomField>
    <fullName>Log_A_Call__c</fullName>
    <label>Log A Call</label>
    <referenceTo>LogACall__c</referenceTo>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Submit_Request__c.field-meta.xml
<CustomField>
    <fullName>Submit_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submit Request</label>
    <referenceTo>Submit_Request__c</referenceTo>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogACall__c/LogACall__c.object-meta.xml
<CustomObject>
    <label>Log A Call</label>
    <nameField>
        <displayFormat>Call-{00000}</displayFormat>
        <label>Log A Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogACall__c/fields/Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Amount__c</fullName>
    <description>Total of expense Amount</description>
    <label>Expense Amount</label>
    <summarizedField>Expense__c.Expense_Amount__c</summarizedField>
    <summaryForeignKey>Expense__c.Log_A_Call__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Submit_Request__c/Submit_Request__c.object-meta.xml
<CustomObject>
    <label>Submit Request</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Submit Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submit Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Submit_Request__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Submit_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Submit_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Submit_Request__c/fields/Total_Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Expense_Amount__c</fullName>
    <label>Total Expense Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ApprovalRequestPageCtrlTest.cls
@isTest
public with sharing class ApprovalRequestPageCtrlTest {

    @isTest static void testhandleApprovalRequest(){
        LogACall__c testLogcall = new LogACall__c();
        testLogcall.Event_Date__c = Date.newInstance(2022, 06, 06);
        insert testLogcall;

        Submit_Request__c newSR1 = new Submit_Request__c();
        newSR1.Status__c = 'Requested';
        insert newSR1;

        Approver__c newApp = new Approver__c();
        newApp.ApproverId__c = UserInfo.getUserId();
        insert newApp;

        Approver__c newAppSub = new Approver__c();
        newAppSub.User__c = UserInfo.getUserId();
        newAppSub.ApproverId__c = newApp.ApproverId__c;
        insert newAppSub;

        newSR1.Total_Expense_Amount__c = 250;
        newSR1.Approver__c = newAppSub.ApproverId__c;
        update newSR1;

        Expense__c newExpense1 = new Expense__c();
        newExpense1.Log_A_Call__c = testLogcall.Id;
        newExpense1.Expense_Amount__c = 500;
        newExpense1.Submit_Request__c = newSR1.Id;
        newExpense1.Expense_Date__c = Date.today();
        insert newExpense1;

        Approval.ProcessSubmitRequest testapproval = new Approval.ProcessSubmitRequest();
        testapproval.setComments('Submitting request for approval');
        testapproval.setObjectId(newSR1.Id);
        testapproval.setSubmitterId(UserInfo.getUserId());
        Approval.ProcessResult result1 = Approval.process(testapproval);
        system.debug('Test Approval process record :-' +result1);
        system.debug('Test Approval process record :-' +result1.getNewWorkitemIds().get(0));

        ApprovalRequestPagectrl.expenseAccounting(result1.getNewWorkitemIds().get(0));
        ApprovalRequestPagectrl.submittedExpenseList(result1.getNewWorkitemIds().get(0));
        ApprovalRequestPagectrl.getApprovalComments(result1.getNewWorkitemIds().get(0));
    }
}