force-app/main/default/objects/Opportunity/fields/Active_Financial_Quote__c.field-meta.xml
<CustomField>
    <fullName>Active_Financial_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Financial Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunities (Active Financial Quote)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Application_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <inlineHelpText>Which Midwest Group office is this for?</inlineHelpText>
    <label>Midwest Group Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Midwest Machinery STL</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery KC</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery OK</fullName>
            </value>
            <value>
                <fullName>Engineered Products</fullName>
            </value>
            <value>
                <fullName>MaRRS</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
            <value>
                <fullName>Spark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <inlineHelpText>Does this job have a customer supplied PO Number?</inlineHelpText>
    <label>PO Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Receipt_of_Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Receipt_of_Order_Date__c</fullName>
    <inlineHelpText>What day did you receive the order? This is for reporting purposes.</inlineHelpText>
    <label>Receipt of Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sync_Quote__c.field-meta.xml
<CustomField>
    <fullName>Sync_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sync Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.OpportunityId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Project_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin__c</fullName>
    <label>Total Project Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/Product_Select__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Select__c/fields/CR__c.field-meta.xml
<CustomField>
    <fullName>CR__c</fullName>
    <label>CR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Estimated_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Ship_Date__c</fullName>
    <label>Est. Ship</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Include_in_Backlog__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Backlog__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Include in Backlog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Margin_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Margin_Percentage__c</fullName>
    <label>Margin Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>ProductSelects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B/R</fullName>
            </value>
            <value>
                <fullName>D/S</fullName>
            </value>
            <value>
                <fullName>C/R</fullName>
            </value>
            <value>
                <fullName>P/T</fullName>
            </value>
            <value>
                <fullName>LAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Active_Financial_Quote__c.field-meta.xml
<CustomField>
    <fullName>Active_Financial_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Financial Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Receipt_of_Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Receipt_of_Order_Date__c</fullName>
    <label>Receipt of Order Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Commissions_and_Rebates__c.field-meta.xml
<CustomField>
    <fullName>Commissions_and_Rebates__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commissions and Rebates</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Buy_Resell_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Buy_Resell_Margin__c</fullName>
    <label>Total Buy/Resell Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Buy_Resell_Margin_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Total_Buy_Resell_Margin_Percentage__c</fullName>
    <label>Total Buy/Resell Margin (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Buy_Resell_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Buy_Resell_Price__c</fullName>
    <label>Total Buy Resell Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Direct_Sell_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Direct_Sell_Price__c</fullName>
    <label>Total Direct Sell Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Project_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin__c</fullName>
    <label>Total Project Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/Sales_Rep_Goal__c.object-meta.xml
<CustomObject>
    <label>Sales Rep Goal</label>
    <nameField>
        <displayFormat>Goal - {00000}</displayFormat>
        <label>Sales Rep Goals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Direct_Sales_Goal__c.field-meta.xml
<CustomField>
    <fullName>Direct_Sales_Goal__c</fullName>
    <label>Direct Sales Goal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Direct_Sales_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Direct_Sales_Percentage__c</fullName>
    <description>in %</description>
    <inlineHelpText>in %</inlineHelpText>
    <label>Direct Sales Margin %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Margin_Goal__c.field-meta.xml
<CustomField>
    <fullName>Margin_Goal__c</fullName>
    <label>Margin Goal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Resell_Sales_Goal__c.field-meta.xml
<CustomField>
    <fullName>Resell_Sales_Goal__c</fullName>
    <label>Resell Sales Goal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Revenue_Goal__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Goal__c</fullName>
    <label>Revenue Goal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Sales_Margin_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Sales_Margin_Percentage__c</fullName>
    <inlineHelpText>In %</inlineHelpText>
    <label>Sales Margin %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Goal__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/Sales_Representative__c.object-meta.xml
<CustomObject>
    <label>Sales Representative</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sales Representative Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Representative__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Engineer Split</relationshipLabel>
    <relationshipName>SalesRepresentatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepresentatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesResultCtrlTest.cls
@isTest
public with sharing class SalesResultCtrlTest {


    @testSetup static void setup() 
    { 
        Sales_Rep_Goal__c  testsrGoal  = new Sales_Rep_Goal__c();
        testsrGoal.Margin_Goal__c = 1500000;
        testsrGoal.Revenue_Goal__c = 40000000;
        testsrGoal.Direct_Sales_Goal__c = 260000;
        testsrGoal.Resell_Sales_Goal__c = 200000;
        testsrGoal.Direct_Sales_Percentage__c = 7;
        testsrGoal.Sales_Margin_Percentage__c = 40;
        testsrGoal.Year__c = String.valueof(system.now().year());
        testsrGoal.Sales_Rep__c = UserInfo.getUserId();
        insert testsrGoal;
        System.debug('TestSales rep goal inserted: '+testsrGoal); 

        Account acctobj = new Account();
        acctobj.Name = 'Testing GoalChart';
        acctobj.AcctSeed__Accounting_Type__c = 'Customer';
        insert acctobj;
        System.debug('TestAccount Inserted: '+acctobj);

         // calculate booked value
         Opportunity testobjOppo = new Opportunity();
         testobjOppo.Name = ' salesResult goals';
         testobjOppo.AccountId = acctobj.Id;
         testobjOppo.closeDate = Date.today();
         testobjOppo.StageName = 'Closed Won';
         testobjOppo.Project_Manager__c = UserInfo.getUserId();
         testobjOppo.Application_Engineer__c = UserInfo.getUserId();
         testobjOppo.Probability = 70;
         testobjOppo.Total_Project_Margin__c = 150;
         testobjOppo.Office__c = 'Midwest Machinery STL';
         insert testobjOppo;
 
         System.debug('TestOpportunity Inserted: '+testobjOppo); 

         // Quote 
         Quote newQuote = new Quote();
         newQuote.Name = 'Quote';
         newQuote.Total_Project_Margin__c = 150;
         newQuote.Total_Buy_Resell_Price__c= 75000;
         newQuote.Total_Buy_Resell_Margin__c = 150;
         newQuote.Total_Buy_Resell_Margin_Percentage__c = 400;
         newQuote.Commissions_and_Rebates__c =70;
         newQuote.Total_Direct_Sell_Price__c = 150;
         newQuote.opportunityId = testobjOppo.Id;
         insert newQuote;
 
         System.debug('TestQuote Inserted: '+newQuote);
         testobjOppo.Sync_Quote__c = newQuote.Id;
         testobjOppo.Active_Financial_Quote__c  = newQuote.Id;
         update testobjOppo;

         //Quote line item
         Product_Select__c testQuoteLine = new Product_Select__c();
         testQuoteLine.Product_Name__c = 'Parent Product Name';
         testQuoteLine.Quote__c = newQuote.Id;
         testQuoteLine.Sale_Type__c = 'B/R';
         testQuoteLine.Estimated_Ship_Date__c = system.now().date();
         testQuoteLine.Product_Name__c = 'Freight';
         testQuoteLine.Margin_Percentage__c = 75;
         testQuoteLine.List_Price__c = 100;
         testQuoteLine.Quantity__c = 4;
         testQuoteLine.CR__c = 2830;
         testQuoteLine.Sales_Price__c = 1050;
         testQuoteLine.Include_in_Backlog__c = true;
         insert testQuoteLine;
         System.debug('testQuoteLine Inserted: '+testQuoteLine);

         Project__c testProject = new Project__c();
         testProject.Name = testobjOppo.Name;
         testProject.PO_Number__c ='PO-1234';
         testProject.Receipt_of_Order_Date__c = system.now().date();
         testProject.Opportunity__c =testobjOppo.Id;
         testProject.Active_Financial_Quote__c = newQuote.Id;
         testProject.ProjectShipDate__c = system.now().date();
         testProject.CreatedDate = system.now().date();
         insert testProject;

         testobjOppo.Project__c = testProject.id;
         update testobjOppo;
         System.debug('TestProject Inserted: '+testProject); 

         // for this you need to create quote
         Sales_Representative__c testsalesEggSplits = new Sales_Representative__c();  
         testsalesEggSplits.Commision__c = 100;
         testsalesEggSplits.Sales_Rep__c = UserInfo.getUserId(); 
         testsalesEggSplits.Opportunity__c = testobjOppo.Id;
         insert testsalesEggSplits ;
         System.debug('TestSales Representative Inserted: '+testsalesEggSplits);

    }

    @isTest static void testBuyResellMarginGoal(){  

        SalesResultCtrl.buildSalesResultsWrapper(UserInfo.getUserId());
    }   
    @isTest static void testgetSalesRepIds(){
        SalesResultCtrl.getSalesRepIds(UserInfo.getUserId());
    }
       
    @isTest static void testGetPercentageGoals(){
        SalesResultCtrl.getPercentageGoals(UserInfo.getUserId());
    }

    @isTest static void testGetSalesBackLog()
    {
        SalesResultCtrl.getSalesBackLog(UserInfo.getUserId());
    }

    @isTest static void testGetDashboardBackLog()
    {
        SalesResultCtrl.getDashboardBackLog(UserInfo.getUserId());
        SalesResultCtrl.getDashboardBackLog2(UserInfo.getUserId());
    }

}