force-app/main/default/objects/Opportunity/fields/Active_Financial_Quote__c.field-meta.xml
<CustomField>
    <fullName>Active_Financial_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Financial Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunities (Active Financial Quote)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Freight__c.field-meta.xml
<CustomField>
    <fullName>Freight__c</fullName>
    <inlineHelpText>What freight option will this order be using?</inlineHelpText>
    <label>Freight</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PPA</fullName>
            </value>
            <value>
                <fullName>Collect</fullName>
            </value>
            <value>
                <fullName>FFA</fullName>
            </value>
            <value>
                <fullName>3rd-Party Logistics</fullName>
            </value>
            <value>
                <fullName>Customer Pick Up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <inlineHelpText>Add a &quot;tag&quot; or &quot;attention to&quot; for the shipping address if required.</inlineHelpText>
    <label>Tag</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Alternate__c.field-meta.xml
<CustomField>
    <fullName>Alternate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Alternate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>Index</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Is_Section_Closed__c.field-meta.xml
<CustomField>
    <fullName>Is_Section_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Section Closed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Parent_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipLabel>Product Groups (Parent Product Group)</relationshipLabel>
    <relationshipName>ProductGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Product Groups</relationshipLabel>
    <relationshipName>Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Total_Extended_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Extended_Cost__c</fullName>
    <label>Total Extended Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Total_Freight__c.field-meta.xml
<CustomField>
    <fullName>Total_Freight__c</fullName>
    <label>Total Freight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Total_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Total_Line_Items__c</fullName>
    <label>Total Line Items</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/Product_Select__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Select__c/fields/CR__c.field-meta.xml
<CustomField>
    <fullName>CR__c</fullName>
    <label>CR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Descriptions__c.field-meta.xml
<CustomField>
    <fullName>Descriptions__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Extended_Cost__c.field-meta.xml
<CustomField>
    <fullName>Extended_Cost__c</fullName>
    <label>Extended Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <description>DNU for anything.</description>
    <label>Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Freight__c.field-meta.xml
<CustomField>
    <fullName>Freight__c</fullName>
    <label>Freight</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Is_SalePrice_Override__c.field-meta.xml
<CustomField>
    <fullName>Is_SalePrice_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is SalePrice Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <label>Manufacturer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Ace Heaters</fullName>
            </value>
            <value>
                <fullName>Advanced Cooling Technologies (ACT)</fullName>
            </value>
            <value>
                <fullName>Advanced Thermal Hydronics (ATH)</fullName>
            </value>
            <value>
                <fullName>Aldrich</fullName>
            </value>
            <value>
                <fullName>Alfa Laval</fullName>
            </value>
            <value>
                <fullName>Alliance Air Products</fullName>
            </value>
            <value>
                <fullName>Amazon</fullName>
            </value>
            <value>
                <fullName>Ameco</fullName>
            </value>
            <value>
                <fullName>American Granby</fullName>
            </value>
            <value>
                <fullName>American Wheatley</fullName>
            </value>
            <value>
                <fullName>Amitrol</fullName>
            </value>
            <value>
                <fullName>Applied Industrial Technologies</fullName>
            </value>
            <value>
                <fullName>Aquanomix</fullName>
            </value>
            <value>
                <fullName>Pumps - Armstrong</fullName>
                <label>Armstrong</label>
            </value>
            <value>
                <fullName>Armstrong Humidifiers</fullName>
            </value>
            <value>
                <fullName>ASC Pumping Equipment</fullName>
            </value>
            <value>
                <fullName>AtmosAir</fullName>
            </value>
            <value>
                <fullName>AU/Hydro Pump</fullName>
            </value>
            <value>
                <fullName>Aurora (Pentair)</fullName>
            </value>
            <value>
                <fullName>Avalara</fullName>
            </value>
            <value>
                <fullName>Baltimore Aircoil</fullName>
            </value>
            <value>
                <fullName>Bearings Inc.</fullName>
            </value>
            <value>
                <fullName>Bessamaire</fullName>
            </value>
            <value>
                <fullName>Boilers &amp; Heaters - Other</fullName>
            </value>
            <value>
                <fullName>Bosch</fullName>
            </value>
            <value>
                <fullName>Bryant Refractory</fullName>
            </value>
            <value>
                <fullName>Bryant Refractory Co</fullName>
            </value>
            <value>
                <fullName>Caleffi North America</fullName>
            </value>
            <value>
                <fullName>Caleffi North America Inc.</fullName>
            </value>
            <value>
                <fullName>Boilers &amp; Heaters - Camus Hydronics</fullName>
                <label>Camus Hydronics</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Margin_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Margin_Percentage__c</fullName>
    <label>Margin Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Multiplier__c</fullName>
    <label>Multiplier</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Original_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Original_Product_Name__c</fullName>
    <label>Original Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Manufacturer__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Accessories (hose kits, etc)</fullName>
            </value>
            <value>
                <fullName>Actuators</fullName>
            </value>
            <value>
                <fullName>Adapters</fullName>
            </value>
            <value>
                <fullName>Air Eliminators</fullName>
            </value>
            <value>
                <fullName>Air Handler</fullName>
            </value>
            <value>
                <fullName>Air Vent</fullName>
            </value>
            <value>
                <fullName>Assembly</fullName>
            </value>
            <value>
                <fullName>AtmosAir</fullName>
            </value>
            <value>
                <fullName>Bag Filter</fullName>
            </value>
            <value>
                <fullName>Balance Valve</fullName>
            </value>
            <value>
                <fullName>Bands</fullName>
            </value>
            <value>
                <fullName>Baseboard</fullName>
            </value>
            <value>
                <fullName>Bearings</fullName>
            </value>
            <value>
                <fullName>Belt Drive Units</fullName>
            </value>
            <value>
                <fullName>BiPolar Ionizer</fullName>
            </value>
            <value>
                <fullName>Blades</fullName>
            </value>
            <value>
                <fullName>Blower Coil Unit</fullName>
            </value>
            <value>
                <fullName>Boiler - Condensing</fullName>
            </value>
            <value>
                <fullName>Boiler - Condensing - Other</fullName>
            </value>
            <value>
                <fullName>Boiler - NON Condensing</fullName>
            </value>
            <value>
                <fullName>Brazed Plate Heat Exchanger</fullName>
            </value>
            <value>
                <fullName>Budgeting</fullName>
            </value>
            <value>
                <fullName>Buffer Tank</fullName>
            </value>
            <value>
                <fullName>Burners</fullName>
            </value>
            <value>
                <fullName>Bushings</fullName>
            </value>
            <value>
                <fullName>Cabinet Heater Unit</fullName>
            </value>
            <value>
                <fullName>Cabinet Unit Heaters</fullName>
            </value>
            <value>
                <fullName>Caps</fullName>
            </value>
            <value>
                <fullName>Centrifugal Separator</fullName>
            </value>
            <value>
                <fullName>Chassis Water Source Heat Pump</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>ProductSelects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B/R</fullName>
            </value>
            <value>
                <fullName>D/S</fullName>
            </value>
            <value>
                <fullName>C/R</fullName>
            </value>
            <value>
                <fullName>P/T</fullName>
            </value>
            <value>
                <fullName>LAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuoteUtils.cls
public with sharing class QuoteUtils {
    
    public static Boolean isActiveFinancialQuote(Id quoteId) {
        List<Opportunity> lstActiveFinancialQuoteOpp = [SELECT Id 
                                                            FROM Opportunity 
                                                            WHERE Active_Financial_Quote__c =:quoteId];
        if(!lstActiveFinancialQuoteOpp.isEmpty()) {
            return true;
        }
        
        return false;
    }

    public static Product_Group__c cloneGroup(Product_Group__c grp) {
        Product_Group__c cloneGroup = new Product_Group__c();
        cloneGroup.Name = grp.Name;
        cloneGroup.Total_Freight__c = grp.Total_Freight__c;
        cloneGroup.Total_Extended_Cost__c = grp.Total_Extended_Cost__c;
        cloneGroup.Total_Line_Items__c = grp.Total_Line_Items__c;
        cloneGroup.Alternate__c = grp.Alternate__c;
        cloneGroup.Quote__c = grp.Quote__c;
        cloneGroup.Is_Section_Closed__c = grp.Is_Section_Closed__c;
        if(grp.Parent_Product_Group__c == null) {
            cloneGroup.Index__c = CartQueryHelper.getTotalGroups(grp.Quote__c) + 1;
        }
        cloneGroup.External_Id__c = generateExternalId();
        return cloneGroup;
    }

    public static Product_Select__c cloneLineItem(Product_Select__c lineItem) {
        Product_Select__c cloneLineItem = new Product_Select__c();
        cloneLineItem.Sale_Type__c = lineItem.Sale_Type__c;
        cloneLineItem.Tag__c = lineItem.Tag__c;
        cloneLineItem.Product_Name__c = lineItem.Product_Name__c;
        cloneLineItem.Original_Product_Name__c = lineItem.Original_Product_Name__c;
        cloneLineItem.Product_Code__c = lineItem.Product_Code__c;
        cloneLineItem.Alternate__c = lineItem.Alternate__c;
        cloneLineItem.Descriptions__c = lineItem.Descriptions__c;
        cloneLineItem.Quantity__c = lineItem.Quantity__c;
        cloneLineItem.List_Price__c = lineItem.List_Price__c;
        cloneLineItem.Multiplier__c = lineItem.Multiplier__c;
        cloneLineItem.Unit_Cost__c = lineItem.Unit_Cost__c;
        cloneLineItem.Freight__c = lineItem.Freight__c;
        cloneLineItem.Extended_Cost__c = lineItem.Extended_Cost__c;
        cloneLineItem.Margin_Percentage__c = lineItem.Margin_Percentage__c;
        cloneLineItem.Sales_Price__c = lineItem.Sales_Price__c;
        cloneLineItem.CR__c = lineItem.CR__c;
        cloneLineItem.Family__c = lineItem.Family__c;
        cloneLineItem.Manufacturer__c = lineItem.Manufacturer__c;
        cloneLineItem.Product_Type__c = lineItem.Product_Type__c;
        cloneLineItem.Is_SalePrice_Override__c = lineItem.Is_SalePrice_Override__c;
        return cloneLineItem;
    }

    public static String generateExternalId(){
        String hashString = Math.round(Math.random()*1000) + String.valueOf(Datetime.now().formatGMT('yyyy-MM-dd HH:mm:ss.SSS'));
        Blob hash = Crypto.generateDigest('MD5', Blob.valueOf(hashString));
        String hexDigest = EncodingUtil.convertToHex(hash);
        return hexDigest;
    }

}