force-app/main/default/objects/Opportunity/fields/Application_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Application_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Attention_to__c.field-meta.xml
<CustomField>
    <fullName>Attention_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Who will we call attention to on the quote?</inlineHelpText>
    <label>Buyer (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Attention to)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bid_Date__c.field-meta.xml
<CustomField>
    <fullName>Bid_Date__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY())&amp;&apos; 2:00:00&apos;)</defaultValue>
    <inlineHelpText>When will you send your first firm bid?</inlineHelpText>
    <label>Bid Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Consulting_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Consulting_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a look up to account record to store the consulting engineer.</description>
    <inlineHelpText>Please select a consulting engineering firm for this opportunity.</inlineHelpText>
    <label>Consulting Engineer (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Consulting Engineer)</relationshipLabel>
    <relationshipName>ConsultingEngineerOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>End_User_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Who is the person that will be operating and looking after the equipment after the job is complete?</inlineHelpText>
    <label>End User Contact Name (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/General_Contractor__c.field-meta.xml
<CustomField>
    <fullName>General_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a look up to account record to store the general contractor.</description>
    <inlineHelpText>Please select a general contractor for this opportunity.</inlineHelpText>
    <label>General Contractor (Account)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Service Mechanical Contractor, Plan &amp; Spec Mechanical Contractor, Design/Build Mechanical Contractor, Electrical Contractor, Plumbing Contractor, Controls / Energy Contractor, General Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (General Contractor)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{YY}-{0000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Name__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Name__c</fullName>
    <label>Shipping Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sync_Quote__c.field-meta.xml
<CustomField>
    <fullName>Sync_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sync Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.OpportunityId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/MaRRS.recordType-meta.xml
<RecordType>
    <fullName>MaRRS</fullName>
    <active>true</active>
    <businessProcess>MaRRS</businessProcess>
    <description>MaRRS quotes for freight and distribution</description>
    <label>MaRRS</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Attention_to__c.field-meta.xml
<CustomField>
    <fullName>Attention_to__c</fullName>
    <formula>Opportunity.Attention_to__r.FirstName + &quot; &quot; + Opportunity.Attention_to__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attention to</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Attention_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Attention_to_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This will show up on the generated quote PDF for the &quot;Proposal To&quot; section. Example: Proposal to Acme Corporation.</inlineHelpText>
    <label>Attention to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Attention to Account)</relationshipLabel>
    <relationshipName>Quotes3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Bid_Date__c.field-meta.xml
<CustomField>
    <fullName>Bid_Date__c</fullName>
    <label>Quote Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Bidding_To__c.field-meta.xml
<CustomField>
    <fullName>Bidding_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name the person you are bidding this quote to. This persons name will show up on the generated quote in the &quot;Attention&quot; field at the top of the PDF.</inlineHelpText>
    <label>Bidding To Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Consulting_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Consulting_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consulting Engineer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/General_Contractor__c.field-meta.xml
<CustomField>
    <fullName>General_Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>General Contractor (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (General Contractor)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <formula>Opportunity.Opportunity_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Original_Name__c.field-meta.xml
<CustomField>
    <fullName>Original_Name__c</fullName>
    <description>To hold original Quote Name</description>
    <inlineHelpText>This is the quote name that was used initially when the quote was created. This is the revision folder name in SharePoint.This is for reference purposes only.</inlineHelpText>
    <label>SharePoint Folder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/Sales_Representative__c.object-meta.xml
<CustomObject>
    <label>Sales Representative</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sales Representative Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Representative__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Engineer Split</relationshipLabel>
    <relationshipName>SalesRepresentatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NewQuoteController.cls
/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 02-14-2024
 * @last modified by  : Nilesh Badrakiya
**/
public with sharing class NewQuoteController{
    
    public Quote quote{get;set;}
    public String strOpportunityId{get;set;}
    public String opportunityNumber{get;set;}
    public Opportunity opportunity{get;set;}
    public Boolean hasSplitEngineer{get;set;} 
    public Boolean isMaRRsOpportunity {get;set;}
    public Boolean hasApplicationEngineer{get;set;} 
    
    public transient SavePoint sp{get;set;}
    
    public NewQuoteController(Apexpages.standardController stdCon){
    
        quote = new Quote();
                
        strOpportunityId = apexpages.currentpage().getparameters().get('oppid');
        
        hasSplitEngineer = getSplitEngineer();
        
        List<Opportunity> lstOpportunity = [Select Id, AccountId, End_User_Contact_Name__c,Consulting_Engineer__c,General_Contractor__c,
                                                                                Opportunity_Number__c, RecordType.Name, Shipping_Name__c,
                                            Bid_Date__c, Name, Attention_to__c,Sync_Quote__c,Application_Engineer__c
                                            FROM Opportunity
                                            WHERE Id =: strOpportunityId];
         
        if(lstOpportunity.size() > 0){
            opportunity = lstOpportunity[0];

            isMaRRsOpportunity = opportunity.RecordType.Name == 'MaRRS' ? true : false;
            
            if((opportunity.RecordType.Name == 'Equipment - Plan/Spec' || opportunity.RecordType.Name == 'Equipment - Design/Build') && opportunity.Application_Engineer__c == null) {
                hasApplicationEngineer = false;
            } else {
                hasApplicationEngineer = true;
            }
            quote.General_Contractor__c = lstOpportunity[0].General_Contractor__c;
            quote.Consulting_Engineer__c = lstOpportunity[0].Consulting_Engineer__c;
            quote.opportunityId = strOpportunityId;
            quote.Attention_to_Account__c = lstOpportunity[0].AccountId;
            quote.Bidding_To__c = lstOpportunity[0].Attention_to__c;
            opportunityNumber = lstOpportunity[0].Opportunity_Number__c;
            quote.Name = lstOpportunity[0].Opportunity_Number__c + ' - ' + lstOpportunity[0].Name + ' - ' + system.now();
            if(lstOpportunity[0].RecordType.Name == 'MaRRS'){
                quote.ShippingName = lstOpportunity[0].Shipping_Name__c;
            }
        }
        
    }
    
    public PageReference updateQuote() {
        //UtilitySharePointToSFIntegration.isUpdateFromQuoteUI = true;
        if (quote != null && quote.Id != null) {
            system.debug('updated quote Name=>'+quote.Name);
            system.debug('updated quote sharepointName=>'+quote.Original_Name__c);
            upsert quote;
            
            //Database.executeBatch(new createFolderForQuote(New Set<Id>{quote.Id}) );
            
        } 
        
        
        PageReference pr = new PageReference('/'+quote.Id);
        pr.setRedirect(true);
        return pr;
    }
        
    public PageReference SaveQuote(){
       
       if(quote.Id != null) {
           return null;
       }
        
       List<Quote> lstDuplicateNameQuote = [Select Id From Quote Where Name =: quote.Name];
        
        if(!lstDuplicateNameQuote.isEmpty()){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Quote Name should be unique. There is quote exist with the same Name.'));
            return null;
        }
        
        String quoteRecordTypeName = opportunity.RecordType.Name + ' Quote';
        
        Id quoteRecordTypeId = Schema.SObjectType.Quote.getRecordTypeInfosByName().get(quoteRecordTypeName).getRecordTypeId();
        
        quote.RecordTypeId = quoteRecordTypeId;
        
        //SavePoint sp = Database.setSavepoint();
        UtilitySharePointToSFIntegration.quoteBulkInsertContext = true;
        system.debug('quote name before insert =>'+quote.Name);
        insert quote;
        
        if(opportunity.Sync_Quote__c == null){
                opportunity.Sync_Quote__c = quote.Id;
                update opportunity;
        }
        
        Quote updateQuote = [Select Id, QuoteNumber From Quote Where Id =: quote.Id];
        
        quote.Name = opportunity.Opportunity_Number__c + '.' + updateQuote.QuoteNumber + ' ' + opportunity.Name;
        
        //Database.rollback(sp);
        
        //quote = new Quote();
        //quote.General_Contractor__c = opportunity .General_Contractor__c;
        //quote.Consulting_Engineer__c = opportunity.Consulting_Engineer__c;
        //quote.opportunityId = strOpportunityId;
        //quote.Attention_to_Account__c = opportunity.AccountId;
        //quote.Bidding_To__c = opportunity.Attention_to__c;
        //opportunityNumber = opportunity.Opportunity_Number__c;
        //quote.Name = quoteName;
             
        return null;
    }
    
    public PageReference Cancel(){
        
        if (quote != null && quote.Id != null) {
            delete quote;
        }
        
        PageReference pr = new Pagereference('/' + strOpportunityId);
        pr.setRedirect(true);
        return pr;
    }
    
    public Boolean getSplitEngineer(){
        List<Sales_Representative__c> lstSalesRepresentative = [Select Id
                                                                                                                        FROM Sales_Representative__c
                                                                                                                        WHERE Opportunity__c =: strOpportunityId];
                
                if(!lstSalesRepresentative.isEmpty()){
                        return true;
                }
                
                return false;
    }
    
    
}