force-app/main/default/objects/Opportunity/fields/Application_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Application_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Commissions_and_Rebates__c.field-meta.xml
<CustomField>
    <fullName>Commissions_and_Rebates__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commissions and Rebates</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Scope_Revision_Number__c.field-meta.xml
<CustomField>
    <fullName>Scope_Revision_Number__c</fullName>
    <label>Scope/Quote Revision Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <default>true</default>
                <label>00</label>
            </value>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Submittal_Revision_Number__c.field-meta.xml
<CustomField>
    <fullName>Submittal_Revision_Number__c</fullName>
    <label>Submittal Revision Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <default>true</default>
                <label>00</label>
            </value>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Buy_Resell_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Buy_Resell_Margin__c</fullName>
    <label>Total Buy/Resell Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Buy_Resell_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Buy_Resell_Price__c</fullName>
    <label>Total Buy Resell Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Direct_Sell_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Direct_Sell_Price__c</fullName>
    <label>Total Direct Sell Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/NewQuoteControllerTest.cls
@isTest
private class NewQuoteControllerTest {
 
    static testMethod void testMethod1() {
        
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.closeDate = Date.today();
        objOpportunity.Name = 'Test Opportunity';
        objOpportunity.stageName = 'Draft';
        objOpportunity.Application_Engineer__c = UserInfo.getUserId();
        insert objOpportunity;
        
        apexpages.currentpage().getparameters().put('oppid',objOpportunity.Id); 
        
        ApexPages.StandardController sc = new ApexPages.StandardController(new Quote());
        NewQuoteController objNewQuoteController = new NewQuoteController(sc);
        
        //objNewQuoteController.quote = new Quote();
        objNewQuoteController.quote.Name = 'Test Quote';
        objNewQuoteController.quote.opportunityId = objOpportunity.Id;
        objNewQuoteController.quote.Scope_Revision_Number__c = '01';
        objNewQuoteController.quote.Submittal_Revision_Number__c = '01';
        objNewQuoteController.SaveQuote();
        objNewQuoteController.Cancel();
        
    }

    static testMethod void testMethod2() {
        //Create test account
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;

        //Create test Opp Account
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.closedate = System.today();
        opp.StageName = 'Non Qualified';
        opp.AccountId = acc.Id;
        insert opp;

        // Create a new quote record for testing
        Quote testQuote = new Quote(
            Name = 'Test Quote',
            opportunityId = opp.Id,
            Total_Direct_Sell_Price__c = 100.00,
            Total_Buy_Resell_Margin__c = 50.00,
            Commissions_and_Rebates__c = 10.00,
            Total_Buy_Resell_Price__c = 60.00
        );
        insert testQuote;

        ProjectFinancials pf = new ProjectFinancials();
        Quote result = ProjectFinancials.getQuote(testQuote.Id);

        // Verify that the result matches the expected values
        System.assertEquals(testQuote.Total_Direct_Sell_Price__c, result.Total_Direct_Sell_Price__c);
        System.assertEquals(testQuote.Total_Buy_Resell_Margin__c, result.Total_Buy_Resell_Margin__c);
    }
    
}