force-app/main/default/objects/Opportunity/fields/Bid_Date__c.field-meta.xml
<CustomField>
    <fullName>Bid_Date__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY())&amp;&apos; 2:00:00&apos;)</defaultValue>
    <inlineHelpText>When will you send your first firm bid?</inlineHelpText>
    <label>Bid Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <inlineHelpText>Which Midwest Group office is this for?</inlineHelpText>
    <label>Midwest Group Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Midwest Machinery STL</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery KC</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery OK</fullName>
            </value>
            <value>
                <fullName>Engineered Products</fullName>
            </value>
            <value>
                <fullName>MaRRS</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
            <value>
                <fullName>Spark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roles_With_Public_Calendars__c/Roles_With_Public_Calendars__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Create events when opportunity is created with bid-date. There is a limitation in salesforce, we can not get public calendar id in apex. To get this we have configured this custom setting.</description>
    <label>Roles With Public Calendars</label>
</CustomObject>

force-app/main/default/objects/Roles_With_Public_Calendars__c/fields/Calendar_Id__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Id__c</fullName>
    <description>Used to store the public calendar id.</description>
    <inlineHelpText>Used to store the public calendar id.</inlineHelpText>
    <label>Calendar Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/Sales_Representative__c.object-meta.xml
<CustomObject>
    <label>Sales Representative</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sales Representative Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Representative__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Engineer Split</relationshipLabel>
    <relationshipName>SalesRepresentatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepresentatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerTest.cls
@isTest
private class OpportunityTriggerTest {
    static testMethod void myUnitTest(){
        // Create Account
        Account acc = createAccount();
        
        // get Logged in users role
        User user = [Select Id, Name, UserRole.Name from User where Id =: Userinfo.getUserId()];
        
        // Create custom setting. 
        Roles_With_Public_Calendars__c calendar = createPublicCalendarConfiguration(user.UserRole.Name);
        
        // Create new opportunity.
        Opportunity opp = new Opportunity();
        opp.AccountId = acc.Id;
        opp.StageName = 'Bidding';
        opp.Name = 'Test Opp 01';
        opp.CloseDate = system.today().addDays(30);
        opp.Bid_Date__c = system.today().addDays(3);
        
        insert opp;
        
        List<Event> newEvents = [Select Id, StartDateTime from Event where WhatId =: opp.Id];
        //system.assert(newEvents.size() > 0);
        //system.assertEquals(opp.Bid_Date__c, newEvents.get(0).StartDateTime);
        
        // Update Opportunity Bid Date.
        opp.Bid_Date__c = system.today().addDays(5);
        update opp;
        
        List<Event> updatedEvents = [Select Id, StartDateTime from Event where WhatId =: opp.Id];
        //system.assert(updatedEvents.size() > 0);
        //system.assertEquals(opp.Bid_Date__c, updatedEvents.get(0).StartDateTime);
    }
    
    private static Account createAccount(){
        Account acc = new Account();
        acc.Name = 'Test Account 01';
        
        insert acc;
        
        return acc;
    }
    
    private static Roles_With_Public_Calendars__c createPublicCalendarConfiguration(String roleName){
        Roles_With_Public_Calendars__c config = new Roles_With_Public_Calendars__c();
        config.Calendar_Id__c = Userinfo.getUserId();
        if(roleName == '' || roleName == null) roleName = 'Test Role';
        config.Name = roleName;
        
        insert config;
        
        return config;
    }

    //SalesEngineerSplitTriggerHandler controller.
    static testMethod void testSaleEngieerSplit(){

        Opportunity opp1 = new Opportunity();
        opp1.StageName = 'Bidding';
        opp1.Name = 'Test Split Opportunity';
        opp1.CloseDate = system.today().addDays(30);
        opp1.Office__c ='Midwest Machinery STL';
        insert opp1;

        SalesEngineerSplitTriggerHandler.updateSalesRepEntry(opp1.Id, 'Midwest Machinery STL');

         List<Sales_Representative__c> salesReps = [SELECT Id, Sales_Rep__c FROM Sales_Representative__c 
                                                    WHERE Opportunity__c = :opp1.Id Limit 1];                                       
         System.assertEquals(1, salesReps.size());
         System.assertEquals('00561000000gZ3T', salesReps[0].Sales_Rep__c);
    }
}