force-app/main/default/objects/Opportunity/fields/Bid_Date__c.field-meta.xml
<CustomField>
    <fullName>Bid_Date__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY())&amp;&apos; 2:00:00&apos;)</defaultValue>
    <inlineHelpText>When will you send your first firm bid?</inlineHelpText>
    <label>Bid Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Bid_Date__c.field-meta.xml
<CustomField>
    <fullName>Bid_Date__c</fullName>
    <label>Quote Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Scope_Revision_Number__c.field-meta.xml
<CustomField>
    <fullName>Scope_Revision_Number__c</fullName>
    <label>Scope/Quote Revision Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <default>true</default>
                <label>00</label>
            </value>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Submittal_Revision_Number__c.field-meta.xml
<CustomField>
    <fullName>Submittal_Revision_Number__c</fullName>
    <label>Submittal Revision Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <default>true</default>
                <label>00</label>
            </value>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GeneratePdfOnQuoteControllerTest.cls
/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 02-05-2024
 * @last modified by  : Nilesh Badrakiya
**/
@isTest
Private class GeneratePdfOnQuoteControllerTest {
    
     static testMethod void Testmethod1(){
        RecordType oppType = [SELECT ID,Name From RecordType WHERE Name = 'Equipment - Plan/Spec'];
         
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.closeDate = Date.today();
        objOpportunity.Name = 'Test Opportunity';
        objOpportunity.stageName = 'Draft';
        objOpportunity.RecordTypeId =oppType.Id;
        insert objOpportunity;
        
        Quote newQuote = new Quote();
        newQuote.Name = 'Test Quote';
        newQuote.opportunityId = objOpportunity.Id;
        newQuote.Scope_Revision_Number__c = '01';
        newQuote.Submittal_Revision_Number__c = '01';
        newQuote.Bid_Date__c = Date.Today();
        insert newQuote;
            
        Test.StartTest();
           
        PageReference pageRef = Page.GeneratePdfOnQuote;
         Test.setCurrentPage(pageRef);
         pageRef.getParameters().put('id',newQuote.id);
        pageRef.getParameters().put('type','quote');
        
        ApexPages.StandardController sc = new ApexPages.StandardController(newQuote);
        GeneratePdfOnQuoteController Testobj = New GeneratePdfOnQuoteController(sc);

        Testobj.createFile();
         
         PageReference pageRef1 = Page.GeneratePdfOnQuote;
         Test.setCurrentPage(pageRef1);
         pageRef1.getParameters().put('id',newQuote.id);
        pageRef1.getParameters().put('type','scope');
         
         ApexPages.StandardController sc1 = new ApexPages.StandardController(newQuote);
        GeneratePdfOnQuoteController Testobj1 = New GeneratePdfOnQuoteController(sc1);

         Testobj1.createFile();
        
        /*pageRef.getParameters().put('id',newQuote.id);
        pageRef.getParameters().put('type','scope');
         Test.setCurrentPage(pageRef);
        Testobj.createFile();*/

         Testobj.closepopup();
         
        Test.StopTest();
        
    }

}