force-app/main/default/objects/Opportunity/fields/Bidders__c.field-meta.xml
<CustomField>
    <fullName>Bidders__c</fullName>
    <label>Bidders</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{YY}-{0000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Date__c</fullName>
    <inlineHelpText>When do you estimate the equipment will ship?</inlineHelpText>
    <label>Estimated Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Targeted__c.field-meta.xml
<CustomField>
    <fullName>Targeted__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Use this checkbox to flag the opportunity so it stays on your &quot;radar&quot; at all times regardless of stage.</inlineHelpText>
    <label>Targeted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Base_Bid_Total_Quote__c.field-meta.xml
<CustomField>
    <fullName>Total_Base_Bid_Total_Quote__c</fullName>
    <inlineHelpText>This is the total base bid for the quote currently synced with this opportunity.</inlineHelpText>
    <label>Base Bid Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Project_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin__c</fullName>
    <label>Total Project Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/Sales_Representative__c.object-meta.xml
<CustomObject>
    <label>Sales Representative</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sales Representative Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Representative__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <formula>Commision__c * Opportunity__r.Total_Project_Margin__c *  Opportunity__r.Probability</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <formula>TEXT(Sales_Rep__r.Office_Location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Office Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Engineer Split</relationshipLabel>
    <relationshipName>SalesRepresentatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <formula>Commision__c *  Opportunity__r.Probability *  Opportunity__r.Total_Base_Bid_Total_Quote__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepresentatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saint Louis</fullName>
            </value>
            <value>
                <fullName>Oklahoma</fullName>
            </value>
            <value>
                <fullName>Kansas City</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TopOpportunitiesController.cls
/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 01-24-2024
 * @last modified by  : Nilesh Badrakiya
**/
public with sharing class TopOpportunitiesController {
    public static final String TARGET_NEGOTIATING = 'TARGET/NEGOTIATING';
    public static final String POST_BID = 'POST BID';
    public static final String BIDDING = 'BIDDING';
    public static final String LEAD_DD_BUDGET = 'LEAD, DD/BUDGET';
    public static final String SAINT_LOUIS = 'Saint Louis';
    public static final String OKLAHOMA = 'Oklahoma';
    public static final String KANSAS_CITY = 'Kansas City';
    public static final String DENVER = 'Denver';
    public static final String MIDWEST_INDUSTRIAL_BUILDERS = 'Midwest Industrial Builders';

    public static Map<Id, Decimal> mapRevenue; 
    public static Map<Id, Decimal> mapMargin;
    //public static String selectSalesRep{get;set;}
    
    public TopOpportunitiesController() {

    }

    @AuraEnabled(cacheable=true)
    public static List<OpportunityWrapper> buildOpporunityWrapper(String stageName, String selectedUserId){
        system.debug('selectedUserId in buildOpporunityWrapper=>'+selectedUserId);
        //system.debug('selectSalesRep=>'+selectSalesRep);
        List<OpportunityWrapper> lstOpportunityWrapper = new List<OpportunityWrapper>();
        
        List<Opportunity> lstOpportunity = null;
        
        if(stageName == TARGET_NEGOTIATING){
            lstOpportunity = [Select ID, Opportunity_Number__c,Name,Total_Project_Margin__c,Total_Base_Bid_Total_Quote__c,
                                Probability,Bidders__c,Description,Owner.Name,Ship_Date__c,CloseDate,LastModifiedDate,
                                (Select Body From Feeds Order By LastModifiedDate desc) lastChatterAction 
                                From Opportunity
                                WHERE Id IN: getSalesRepOpportunityIds(selectedUserId)
                                AND (StageName IN :getSetFromStageName(stageName)
                                OR Targeted__c = true)
                                AND Total_Project_Margin__c != null
                                ORDER BY Total_Project_Margin__c desc
                                LIMIT 10];
                                
        } else {
            system.debug('stageName='+stageName);
            lstOpportunity = [Select ID, Opportunity_Number__c,Name,Total_Project_Margin__c,Total_Base_Bid_Total_Quote__c,
                                Probability,Bidders__c,Description,Owner.Name,Ship_Date__c,CloseDate,LastModifiedDate,
                                (Select Body From Feeds Order By LastModifiedDate desc) lastChatterAction 
                                From Opportunity
                                WHERE Id IN: getSalesRepOpportunityIds(selectedUserId)
                                AND StageName IN :getSetFromStageName(stageName)
                                AND Total_Project_Margin__c != null
                                ORDER BY Total_Project_Margin__c desc
                                LIMIT 10];

                                
        }        
        
        
        for(Opportunity opp : lstOpportunity){
            String lastChatterAction = '';
            OpportunityFeed lastOppFeed = getLastChatterDetails(opp.Feeds);
            
            
            if(lastOppFeed != null){
                lastChatterAction = lastOppFeed.Body.stripHtmlTags();
                system.debug('The lastChatterAction -2' +lastChatterAction);
            }
           
            system.debug('mapMargin=>'+mapMargin);
            system.debug('mapRevenue=>'+mapRevenue);
            system.debug('opp=>'+opp);
            OpportunityWrapper objOpportunityWrapper = new OpportunityWrapper(opp, mapRevenue.get(opp.Id),mapMargin.get(opp.Id),lastChatterAction);
            lstOpportunityWrapper.add(objOpportunityWrapper);
                        
        }
        
        return lstOpportunityWrapper;
    }

    public static OpportunityFeed getLastChatterDetails(List<OpportunityFeed> lstOpportunityFeeds){
        for(OpportunityFeed oppfeed : lstOpportunityFeeds){
            if(oppfeed.Body != null){
                return oppfeed;    
            }
        }
        return null;
    }

    public static Set<Id> getSalesRepOpportunityIds(String selectSalesRep){
        
        mapRevenue = new Map<Id, Decimal>();
         mapMargin = new Map<Id, Decimal>();
        
        List<Sales_Representative__c > lstSalesRep;
        
        Set<Id> setOpportunityIds = new Set<Id>();
        
        if(selectSalesRep == 'Midwest Machinery'){
            lstSalesRep =[Select Opportunity__c,Revenue__c,Margin__c 
                            FROM Sales_Representative__c 
                            Where (Sales_Rep__r.Office_Location__c =: SAINT_LOUIS
                            OR Sales_Rep__r.Office_Location__c =: OKLAHOMA 
                            OR Sales_Rep__r.Office_Location__c =: KANSAS_CITY 
                            OR Sales_Rep__r.Office_Location__c =: DENVER
                            OR Sales_Rep__r.Office_Location__c =: MIDWEST_INDUSTRIAL_BUILDERS)];
                            
        }else if(selectSalesRep == SAINT_LOUIS || selectSalesRep == OKLAHOMA || selectSalesRep == KANSAS_CITY || selectSalesRep == DENVER || selectSalesRep == MIDWEST_INDUSTRIAL_BUILDERS){
            lstSalesRep =[Select Opportunity__c,Revenue__c,Margin__c 
                            FROM Sales_Representative__c 
                            Where Sales_Rep__r.Office_Location__c =: selectSalesRep];
        }else{
            lstSalesRep =[Select Opportunity__c,Revenue__c,Margin__c 
                            FROM Sales_Representative__c 
                            Where Sales_Rep__c =: selectSalesRep];
        }
        
        for(Sales_Representative__c  sr : lstSalesRep){
            setOpportunityIds.add(sr.Opportunity__c);
            if(!mapMargin.containsKey(sr.Opportunity__c)){
                mapMargin.put(sr.Opportunity__c,sr.Margin__c);
                mapRevenue.put(sr.Opportunity__c,sr.Revenue__c);
            }
            else{
                mapMargin.put(sr.Opportunity__c,mapMargin.get(sr.Opportunity__c) + sr.Margin__c);
                mapRevenue.put(sr.Opportunity__c,mapRevenue.get(sr.Opportunity__c) + sr.Revenue__c);
            }
            
        }
        
        return setOpportunityIds;
    }

    public static Set<String> getSetFromStageName(String stageName){
        
        Set<String> setStageName = new Set<String>();
        
        if(stageName == LEAD_DD_BUDGET){
            setStageName.add('Lead');
            setStageName.add('DD/Budget');
        }else{
            setStageName.add(stageName);
        }
        system.debug('setStageName==>'+setStageName);
        return setStageName;
        
    }

    public class OpportunityWrapper{
        @AuraEnabled
        public Opportunity opportunity{get;set;}
        @AuraEnabled
        public Decimal revenue{get;set;}
        @AuraEnabled
        public Decimal margin{get;set;}
        @AuraEnabled
        public String lastChatterAction{get;set;}
        
        public opportunityWrapper(Opportunity opp, Decimal rev, Decimal mar, String lca){
            opportunity = opp;
            revenue = rev;
            margin = mar;
            lastChatterAction = lca;
            
        }
        
        public opportunityWrapper(Opportunity opp){
            opportunity = opp;
        }
    }
}