force-app/main/default/objects/Opportunity/fields/Bidders__c.field-meta.xml
<CustomField>
    <fullName>Bidders__c</fullName>
    <label>Bidders</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{YY}-{0000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Date__c</fullName>
    <inlineHelpText>When do you estimate the equipment will ship?</inlineHelpText>
    <label>Estimated Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Targeted__c.field-meta.xml
<CustomField>
    <fullName>Targeted__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Use this checkbox to flag the opportunity so it stays on your &quot;radar&quot; at all times regardless of stage.</inlineHelpText>
    <label>Targeted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Base_Bid_Total_Quote__c.field-meta.xml
<CustomField>
    <fullName>Total_Base_Bid_Total_Quote__c</fullName>
    <inlineHelpText>This is the total base bid for the quote currently synced with this opportunity.</inlineHelpText>
    <label>Base Bid Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Project_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin__c</fullName>
    <label>Total Project Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <formula>Opportunity__r.Active_Financial_Quote__r.Commissions_and_Rebates__c + Opportunity__r.Active_Financial_Quote__r.Total_Buy_Resell_Margin__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Stage__c.field-meta.xml
<CustomField>
    <fullName>Project_Stage__c</fullName>
    <label>PM Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Pre-submittals</fullName>
            </value>
            <value>
                <fullName>All submittals sent – awaiting approval(s)</fullName>
            </value>
            <value>
                <fullName>Submittals approved</fullName>
            </value>
            <value>
                <fullName>Equipment Partially Released</fullName>
            </value>
            <value>
                <fullName>Released all equipment</fullName>
            </value>
            <value>
                <fullName>Partially shipped</fullName>
            </value>
            <value>
                <fullName>Fully shipped</fullName>
            </value>
            <value>
                <fullName>Startup and owner training</fullName>
            </value>
            <value>
                <fullName>Partially invoiced</fullName>
            </value>
            <value>
                <fullName>Fully invoiced</fullName>
            </value>
            <value>
                <fullName>Partially paid</fullName>
            </value>
            <value>
                <fullName>All paid</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>All Submitted Waiting for Approval</fullName>
                <isActive>false</isActive>
                <label>All Submitted Waiting for Approval</label>
            </value>
            <value>
                <fullName>Received Customer PO</fullName>
                <isActive>false</isActive>
                <label>Received Customer PO</label>
            </value>
            <value>
                <fullName>Shipped and Invoiced All</fullName>
                <isActive>false</isActive>
                <label>Shipped and Invoiced All</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/Sales_Representative__c.object-meta.xml
<CustomObject>
    <label>Sales Representative</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sales Representative Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Representative__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <formula>Commision__c * Opportunity__r.Total_Project_Margin__c *  Opportunity__r.Probability</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <formula>TEXT(Sales_Rep__r.Office_Location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Office Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Engineer Split</relationshipLabel>
    <relationshipName>SalesRepresentatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <formula>Commision__c *  Opportunity__r.Probability *  Opportunity__r.Total_Base_Bid_Total_Quote__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepresentatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saint Louis</fullName>
            </value>
            <value>
                <fullName>Oklahoma</fullName>
            </value>
            <value>
                <fullName>Kansas City</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ShowAllOpportunity.cls
/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 01-24-2024
 * @last modified by  : Nilesh Badrakiya
**/
public with sharing class ShowAllOpportunity{
    
    public final String TARGET_NEGOTIATING = 'TARGET/NEGOTIATING';
    public final String POST_BID = 'POST BID';
    public final String BIDDING = 'BIDDING';
    public final String LEAD_DD_BUDGET = 'LEAD, DD/BUDGET';
    
    public Final Integer PAGE_SIZE = 50;
    
    public final String SAINT_LOUIS = 'Saint Louis';
    public final String OKLAHOMA = 'Oklahoma';
    public final String KANSAS_CITY = 'Kansas City';
    public final String DENVER = 'Denver';
    public final String MIDWEST_INDUSTRIAL_BUILDERS = 'Midwest Industrial Builders';
    
    Map<Id, Decimal> mapMargin;
    Map<Id, Decimal> mapRevenue;
    
    public String selectSalesRep{get;set;}
    public String stageName{get;set;}
    
    public  List<OpportunityWrapper> opportunity;
    
    public ShowAllOpportunity() {

    }
    
    public ShowAllOpportunity(ApexPages.StandardController controller) {

    }
    
    public Set<Id> getSalesRepOpportunityIds(){
        
        mapRevenue = new Map<Id, Decimal>();
        mapMargin = new Map<Id, Decimal>();
        
        List<AggregateResult> lstSalesRep;
        
        Set<Id> setOpportunityIds = new Set<Id>();
        
        if(selectSalesRep == 'Midwest Machinery'){
            lstSalesRep =[Select Opportunity__c, sum(Revenue__c) revenue, sum(Margin__c) Margin  
                            FROM Sales_Representative__c 
                            Where (Sales_Rep__r.Office_Location__c =: SAINT_LOUIS
                            OR Sales_Rep__r.Office_Location__c =: OKLAHOMA 
                            OR Sales_Rep__r.Office_Location__c =: KANSAS_CITY 
                            OR Sales_Rep__r.Office_Location__c =: DENVER
                            OR Sales_Rep__r.Office_Location__c =: MIDWEST_INDUSTRIAL_BUILDERS) 
                            AND Opportunity__r.stageName != 'Closed Won' 
                            AND Opportunity__r.stageName != 'Closed/Dropped' 
                            AND (Opportunity__r.Total_Project_Margin__c != null AND Opportunity__r.Total_Project_Margin__c != 0)
                            GROUP BY Opportunity__c];
                            
        }else if(selectSalesRep == SAINT_LOUIS || selectSalesRep == OKLAHOMA || selectSalesRep == KANSAS_CITY || selectSalesRep == DENVER || selectSalesRep == MIDWEST_INDUSTRIAL_BUILDERS){
            lstSalesRep =[Select Opportunity__c, sum(Revenue__c) revenue, sum(Margin__c) Margin 
                            FROM Sales_Representative__c 
                            Where Sales_Rep__r.Office_Location__c =: selectSalesRep 
                            AND Opportunity__r.stageName != 'Closed Won' 
                            AND (Opportunity__r.Total_Project_Margin__c != null AND Opportunity__r.Total_Project_Margin__c != 0)
                            GROUP BY Opportunity__c];
        }else{
            lstSalesRep =[Select Opportunity__c, sum(Revenue__c) revenue, sum(Margin__c) Margin 
                          FROM Sales_Representative__c 
                          WHERE Sales_Rep__c =: selectSalesRep
                          AND Opportunity__r.stageName != 'Closed Won' 
                          AND (Opportunity__r.Total_Project_Margin__c != null AND Opportunity__r.Total_Project_Margin__c != 0)
                          GROUP BY Opportunity__c];
        }
        system.debug('Selected salesRep:- '+selectSalesRep);
        // for(Sales_Representative__c  sr : lstSalesRep){
        //     setOpportunityIds.add(sr.Opportunity__c);
        //     if(mapMargin.get(sr.Opportunity__c) == null){
        //         mapMargin.put(sr.Opportunity__c,sr.Margin__c);
        //         mapRevenue.put(sr.Opportunity__c,sr.Revenue__c);
        //     }
        //     else{
        //         mapMargin.put(sr.Opportunity__c,mapMargin.get(sr.Opportunity__c) + sr.Margin__c);
        //         mapRevenue.put(sr.Opportunity__c,mapRevenue.get(sr.Opportunity__c) + sr.Revenue__c);
        //     }   
        // } 
        
        for(AggregateResult  sr : lstSalesRep){
            String oppId = (String) sr.get('Opportunity__c');
            Decimal margin = (Decimal) sr.get('Margin');
            Decimal revenue = (Decimal) sr.get('revenue');

            setOpportunityIds.add(oppId);
            if(mapMargin.get(oppId) == null){
                mapMargin.put(oppId, margin);
                mapRevenue.put(oppId, revenue);
            }else{
                mapMargin.put(oppId, mapMargin.get(oppId) + margin);
                mapRevenue.put(oppId, mapRevenue.get(oppId) + revenue);
            }
        }
        system.debug('SalesRep opportunity ids:- '+setOpportunityIds.size());
        return setOpportunityIds;
    }
    
    public Set<String> getSetFromStageName(String stageName){
        
        Set<String> setStageName = new Set<String>();
        
        if(stageName == LEAD_DD_BUDGET){
            setStageName.add('Lead');
            setStageName.add('DD/Budget');
        }else{
            setStageName.add(stageName);
        }
        
        return setStageName;
        
    }
    
    public ApexPages.StandardSetController con {
        get {
            if(con == null) {
                stageName = Apexpages.currentPage().getParameters().get('stageName');
                selectSalesRep = Apexpages.currentPage().getParameters().get('selectSalesRep');
                if(stageName != 'Open Projects' && stageName != 'Past Due'){
                    if(stageName == TARGET_NEGOTIATING){
                        con = new ApexPages.StandardSetController(Database.getQueryLocator([Select Opportunity_Number__c,Name,Total_Project_Margin__c,Total_Base_Bid_Total_Quote__c,
                                                                                Probability,Bidders__c,Description,Owner.Name,Ship_Date__c,CloseDate,LastActivityDate,
                                                                                (Select Body From Feeds Order By LastModifiedDate desc LIMIT 1) lastChatterAction 
                                                                                From Opportunity
                                                                                WHERE Id IN: getSalesRepOpportunityIds()
                                                                                AND (StageName IN :getSetFromStageName(stageName)
                                                                                OR Targeted__c = true)
                                                                                AND Total_Project_Margin__c != null
                                                                                ORDER BY Total_Project_Margin__c desc 
                                                                                LIMIT 1000])); 
                        system.debug('In Target negotiation stage');
                    } else {
                        con = new ApexPages.StandardSetController(Database.getQueryLocator([Select Opportunity_Number__c,Name,Total_Project_Margin__c,Total_Base_Bid_Total_Quote__c,
                                                                                Probability,Bidders__c,Description,Owner.Name,Ship_Date__c,CloseDate,LastActivityDate,
                                                                                (Select Body From Feeds Order By LastModifiedDate desc LIMIT 1) lastChatterAction 
                                                                                From Opportunity
                                                                                WHERE Id IN: getSalesRepOpportunityIds()
                                                                                AND StageName IN :getSetFromStageName(stageName)
                                                                                AND Total_Project_Margin__c != null
                                                                                ORDER BY Total_Project_Margin__c desc
                                                                                LIMIT 1000]));
                        system.debug('else case getResultSize()=> '+con.getResultSize());
                        system.debug('else case stage name:- '+stageName);
                    }
                    
                }
                else if(stageName == 'Open Projects'){
                    
                    con = new ApexPages.StandardSetController(Database.getQueryLocator([Select Opportunity_Number__c,Name,Total_Project_Margin__c,Total_Base_Bid_Total_Quote__c,
                                                                                        Probability,Bidders__c,Description,Owner.Name,Ship_Date__c,CloseDate,LastActivityDate,
                                                                                        (Select Body From Feeds Order By LastModifiedDate desc LIMIT 1) lastChatterAction  
                                                                                        From Opportunity
                                                                                        WHERE Id IN (Select Opportunity__c From Project__c 
                                                                                                        WHERE Opportunity__c != null 
                                                                                                        AND Project_Stage__c != 'Archived'
                                                                                                        AND Opportunity__c IN :getSalesRepOpportunityIds())
                                                                                        AND Total_Project_Margin__c != null
                                                                                        ORDER BY Total_Project_Margin__c desc]));
                    
                }
                else if(stageName == 'Past Due'){
                    con = new ApexPages.StandardSetController(Database.getQueryLocator([Select Opportunity_Number__c,Name,Total_Project_Margin__c,Total_Base_Bid_Total_Quote__c,
                                                                                        Probability,Bidders__c,Description,Owner.Name,Ship_Date__c,CloseDate,LastActivityDate,
                                                                                        (Select Body From Feeds Order By LastModifiedDate desc LIMIT 1) lastChatterAction  
                                                                                        From Opportunity
                                                                                        WHERE Id NOT IN (Select Opportunity__c From Project__c Where Opportunity__c != null) 
                                                                                        AND Id IN :getSalesRepOpportunityIds()
                                                                                        AND Total_Project_Margin__c != null
                                                                                        AND CloseDate <= Today
                                                                                        AND (StageName = 'Bidding'
                                                                                          OR StageName = 'Post Bid'
                                                                                          OR StageName = 'TARGET/NEGOTIATING'
                                                                                          OR StageName = 'LEAD'
                                                                                          OR StageName = 'DD/BUDGET')
                                                                                        ORDER BY Total_Project_Margin__c desc]));
                }
                con.setPageSize(PAGE_SIZE);
            }
            return con;
        }
        set;
    }
    
    public List<OpportunityWrapper> getOpportunity() {
        
        opportunity = new List<OpportunityWrapper>();
        
        for (Opportunity opp : (List<Opportunity>)con.getRecords()){

            String lastChatterAction = '';
            OpportunityFeed lastOppFeed = getLastChatterDetails(opp.Feeds);
            
            if(lastOppFeed != null){
                lastChatterAction = lastOppFeed.Body.stripHtmlTags();
            }
            OpportunityWrapper objOpportunityWrapper = new OpportunityWrapper(opp, mapRevenue.get(opp.Id),mapMargin.get(opp.Id),lastChatterAction);
            opportunity.add(objOpportunityWrapper);            
        }
        system.debug('Opportunity records size for top opportunity page:- '+opportunity.size());
        return opportunity;
    }
    
    public OpportunityFeed getLastChatterDetails(List<OpportunityFeed> lstOpportunityFeeds){
    
        for(OpportunityFeed oppfeed : lstOpportunityFeeds){
            if(oppfeed.Body != null){
                return oppfeed;
                break;
            }
        }
        
        return null;
        
    }
    
    public Boolean hasNext {
        get {
            return con.getHasNext();
        }
        set;
    }
    
    public Boolean hasPrevious {
        get {
            return con.getHasPrevious();
        }
        set;
    }
    
    public Integer pageNumber {
        get {
            return con.getPageNumber();
        }
        set;
    }
    
    public void first() {
         con.first();
     }
     
     public void last() {
         con.last();
     }
     
     public void previous() {
         con.previous();
     }
     
     public void next() {
         con.next();
     }
    
    public class OpportunityWrapper{
        public  Opportunity opportunity{get;set;}
        public  Decimal revenue{get;set;}
        public  Decimal margin{get;set;}
        public  String lastChatterAction{get;set;}
        
        public opportunityWrapper(Opportunity opp, Decimal rev, Decimal mar, String lca){
            opportunity = opp;
            revenue = rev;
            margin = mar;
            lastChatterAction = lca;
            
        }
        
        public opportunityWrapper(Opportunity opp){
            opportunity = opp;
        }
    }
    

}