force-app/main/default/objects/Opportunity/fields/Bidders__c.field-meta.xml
<CustomField>
    <fullName>Bidders__c</fullName>
    <label>Bidders</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{YY}-{0000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Date__c</fullName>
    <inlineHelpText>When do you estimate the equipment will ship?</inlineHelpText>
    <label>Estimated Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Base_Bid_Total_Quote__c.field-meta.xml
<CustomField>
    <fullName>Total_Base_Bid_Total_Quote__c</fullName>
    <inlineHelpText>This is the total base bid for the quote currently synced with this opportunity.</inlineHelpText>
    <label>Base Bid Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Project_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin__c</fullName>
    <label>Total Project Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Parts.recordType-meta.xml
<RecordType>
    <fullName>Parts</fullName>
    <active>true</active>
    <businessProcess>Parts</businessProcess>
    <description>Select this opportunity for replacement parts, end user orders etc.</description>
    <label>Parts</label>
</RecordType>

force-app/main/default/objects/Sales_Representative__c/Sales_Representative__c.object-meta.xml
<CustomObject>
    <label>Sales Representative</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sales Representative Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Representative__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <formula>Commision__c * Opportunity__r.Total_Project_Margin__c *  Opportunity__r.Probability</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <formula>TEXT(Sales_Rep__r.Office_Location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Office Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Engineer Split</relationshipLabel>
    <relationshipName>SalesRepresentatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <formula>Commision__c *  Opportunity__r.Probability *  Opportunity__r.Total_Base_Bid_Total_Quote__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepresentatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saint Louis</fullName>
            </value>
            <value>
                <fullName>Oklahoma</fullName>
            </value>
            <value>
                <fullName>Kansas City</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/STLDashboard.cls
public with sharing class STLDashboard{
    
    public final String TARGET_NEGOTIATING = 'TARGET/NEGOTIATING';
    public final String SAINT_LOUIS = 'Saint Louis';
    
    public String selectSalesRep{get;set;}
    public List<OpportunityWrapper> lstOpportunityTargetedWrapper{get;set;}
    
    public Decimal totalTargeted{get;set;}
    
    Map<Id, Decimal> mapRevenue{get;set;}
    
    public STLDashboard(){
        refreshDashBoard();
        
    }
    
    public void refreshDashBoard(){
        totalTargeted = 0;
        selectSalesRep = SAINT_LOUIS;
        
        lstOpportunityTargetedWrapper = BuildOpporunityWrapper(TARGET_NEGOTIATING);
    }
    
    public List<OpportunityWrapper> buildOpporunityWrapper(String stageName){
    
        Id partsRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Parts').getRecordTypeId();
        List<OpportunityWrapper> lstOpportunityWrapper = new List<OpportunityWrapper>();
                
        List<Opportunity> lstOpportunity = [Select Opportunity_Number__c,Name,Total_Project_Margin__c,Total_Base_Bid_Total_Quote__c,
                                            Probability,Bidders__c,Description,Owner.Name,Ship_Date__c,CloseDate,LastModifiedDate,
                                            (Select Body From Feeds Order By LastModifiedDate desc) lastChatterAction 
                                            From Opportunity
                                            WHERE Id IN: getSalesRepOpportunityIds() AND 
                                            StageName IN :getSetFromStageName(stageName) AND
                                            RecordTypeId != :partsRecordTypeId
                                            ORDER BY Total_Project_Margin__c desc
                                            LIMIT 10];
        
        String rowColor = 'white';
        
        for(Opportunity opp : lstOpportunity){
            if(opp.Total_Base_Bid_Total_Quote__c != null){
                totalTargeted += opp.Total_Base_Bid_Total_Quote__c;
            }
            
            
            String lastChatterAction = '';
            OpportunityFeed lastOppFeed = getLastChatterDetails(opp.Feeds);
            
            if(lastOppFeed != null){
                lastChatterAction = lastOppFeed.Body;
            }
            
            if(rowColor == '#E4E3E0'){
                rowColor = 'white';
            } 
            else{
                rowColor = '#E4E3E0';
            }
            
            OpportunityWrapper objOpportunityWrapper = new OpportunityWrapper(opp, mapRevenue.get(opp.Id),lastChatterAction,rowColor);
            lstOpportunityWrapper.add(objOpportunityWrapper);
                        
        }
        
        return lstOpportunityWrapper;
    }
    
    public Set<String> getSetFromStageName(String stageName){
        
        Set<String> setStageName = new Set<String>();
        
        setStageName.add(stageName);
        
        return setStageName;
        
    }
    
    public Set<Id> getSalesRepOpportunityIds(){
        
        mapRevenue = new Map<Id, Decimal>();
        
        List<Sales_Representative__c > lstSalesRep;
        Set<Id> setOpportunityIds = new Set<Id>();
        
        if(selectSalesRep == SAINT_LOUIS){
            lstSalesRep =[Select Opportunity__c,Revenue__c,Margin__c 
                            FROM Sales_Representative__c 
                            Where Sales_Rep__r.Office_Location__c =: selectSalesRep];
        }
        
        for(Sales_Representative__c  sr : lstSalesRep){
            setOpportunityIds.add(sr.Opportunity__c);
            if(mapRevenue.get(sr.Opportunity__c) == null){
                mapRevenue.put(sr.Opportunity__c,sr.Revenue__c);
            }
            else{
                mapRevenue.put(sr.Opportunity__c,mapRevenue.get(sr.Opportunity__c) + sr.Revenue__c);
            }
        }
        
        return setOpportunityIds;
    }
    
    public OpportunityFeed getLastChatterDetails(List<OpportunityFeed> lstOpportunityFeeds){
    
        for(OpportunityFeed oppfeed : lstOpportunityFeeds){
            if(oppfeed.Body != null){
                return oppfeed;
            }
        }
        
        return null;
        
    }
    
    
    
    public class OpportunityWrapper{
        public Opportunity opportunity{get;set;}
        public Decimal revenue{get;set;}
        public String rowColor{get;set;}
        public String lastChatterAction{get;set;}
        public String strColor{get;set;}
        
        public opportunityWrapper(Opportunity opp, Decimal rev, String lca, String rc){
            opportunity = opp;
            revenue = rev;
            lastChatterAction = lca;
            rowColor = rc;
            strColor = isRowRedGreen(opp);
        }
        
        public opportunityWrapper(Opportunity opp){
            opportunity = opp;
        }
        
        public String isRowRedGreen(Opportunity opp){
        
            String strColor = 'ABC';
            
            Date todayDate = Date.today();
            String strDate = String.valueOf(opp.LastModifiedDate);
            DateTime dT = DateTime.valueOf(strDate);
            Date lastActivateDate  = date.newinstance(dT.year(), dT.month(), dT.day());
            Integer lstActivateDays = lastActivateDate.daysBetween(todayDate);
            
            if(opp.Probability >= 75 && lstActivateDays <= 14){
                strColor = '#c2f8c2';
            }
            else if(opp.Probability <= 50 && lstActivateDays > 14){
                strColor = '#d79c9c';
            }
            
            return strColor;
            
            
        }
    }
    
}