force-app/main/default/objects/Opportunity/fields/Consulting_Engineer_Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Consulting_Engineer_Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consulting Engineer (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Consulting Engineer Contact Person)</relationshipLabel>
    <relationshipName>Opportunities79sk</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mechanical_Contractor_10__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Contractor_10__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the name of the company we are bidding to.</inlineHelpText>
    <label>Mechanical Contractor 10 (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Company 10)</relationshipLabel>
    <relationshipName>OpportunitiesADra</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mechanical_Contractor_1__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Contractor_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the name of the company we are bidding to.</inlineHelpText>
    <label>Mechanical Contractor 1 (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Company 1)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mechanical_Contractor_2__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Contractor_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the name of the company we are bidding to.</inlineHelpText>
    <label>Mechanical Contractor 2 (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Company 2)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mechanical_Contractor_3__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Contractor_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the name of the company we are bidding to.</inlineHelpText>
    <label>Mechanical Contractor 3 (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Company 3)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mechanical_Contractor_4__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Contractor_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the name of the company we are bidding to.</inlineHelpText>
    <label>Mechanical Contractor 4 (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Company 4)</relationshipLabel>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mechanical_Contractor_5__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Contractor_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the name of the company we are bidding to.</inlineHelpText>
    <label>Mechanical Contractor 5 (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Company 5)</relationshipLabel>
    <relationshipName>Opportunities5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mechanical_Contractor_6__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Contractor_6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the name of the company we are bidding to.</inlineHelpText>
    <label>Mechanical Contractor 6 (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Company 6)</relationshipLabel>
    <relationshipName>Opportunities6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mechanical_Contractor_7__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Contractor_7__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the name of the company we are bidding to.</inlineHelpText>
    <label>Mechanical Contractor 7 (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Company 7)</relationshipLabel>
    <relationshipName>Opportunities7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mechanical_Contractor_8__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Contractor_8__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the name of the company we are bidding to.</inlineHelpText>
    <label>Mechanical Contractor 8 (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Company 8)</relationshipLabel>
    <relationshipName>Opportunities8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mechanical_Contractor_9__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Contractor_9__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the name of the company we are bidding to.</inlineHelpText>
    <label>Mechanical Contractor 9 (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Company 9)</relationshipLabel>
    <relationshipName>Opportunities9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Owner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BiddersNameTriggerTest.cls
@isTest
private class BiddersNameTriggerTest {
    static testMethod void testBiddersName() {
        
        Account newAcc = new Account();
        newAcc.Name = 'Test Account';
        insert newAcc;

        Contact con = new Contact();
        con.FirstName ='TestFname';
        con.LastName = 'LastNm';
        con.Email = 'SA@test.com';
        insert con; 
        
        Opportunity newOpp = new Opportunity();
        newOpp.Name = 'Test Opportunity';
        newOpp.StageName = 'Open';
        newOpp.CloseDate = Date.Today();
        newOpp.Mechanical_Contractor_1__c = newAcc.Id;
        newOpp.Mechanical_Contractor_2__c = newAcc.Id;
        newOpp.Mechanical_Contractor_3__c = newAcc.Id;
        newOpp.Mechanical_Contractor_4__c = newAcc.Id;
        newOpp.Mechanical_Contractor_5__c = newAcc.Id;
        newOpp.Mechanical_Contractor_6__c = newAcc.Id;
        newOpp.Mechanical_Contractor_7__c = newAcc.Id;
        newOpp.Mechanical_Contractor_8__c = newAcc.Id;
        newOpp.Mechanical_Contractor_9__c = newAcc.Id;
        newOpp.Mechanical_Contractor_10__c = newAcc.Id;
        newOpp.Consulting_Engineer_Contact_Person__c = con.Id;
        newOpp.Opportunity_Owner__c = UserInfo.getUserId();
        insert newOpp;
    }
}