force-app/main/default/objects/Opportunity/fields/Consulting_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Consulting_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a look up to account record to store the consulting engineer.</description>
    <inlineHelpText>Please select a consulting engineering firm for this opportunity.</inlineHelpText>
    <label>Consulting Engineer (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Consulting Engineer)</relationshipLabel>
    <relationshipName>ConsultingEngineerOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Consulting_Engineer_Account__c.field-meta.xml
<CustomField>
    <fullName>Consulting_Engineer_Account__c</fullName>
    <formula>HYPERLINK(IF(ISBLANK(Consulting_Engineer_Contact_Person__c), &apos;/&apos;+ Consulting_Engineer__c,  Consulting_Engineer_Contact_Person__r.AccountId),  IF(ISBLANK(Consulting_Engineer_Contact_Person__c), Consulting_Engineer__r.Name ,  Consulting_Engineer_Contact_Person__r.Account.Name), &quot;__blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Consulting Engineer (Account)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{YY}-{0000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Parts.recordType-meta.xml
<RecordType>
    <fullName>Parts</fullName>
    <active>true</active>
    <businessProcess>Parts</businessProcess>
    <description>Select this opportunity for replacement parts, end user orders etc.</description>
    <label>Parts</label>
</RecordType>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Total_Extended_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Extended_Cost__c</fullName>
    <label>Total Extended Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/Product_Select__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Select__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Attention_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Attention_to_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This will show up on the generated quote PDF for the &quot;Proposal To&quot; section. Example: Proposal to Acme Corporation.</inlineHelpText>
    <label>Attention to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Attention to Account)</relationshipLabel>
    <relationshipName>Quotes3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Attention_To_Person__c.field-meta.xml
<CustomField>
    <fullName>Attention_To_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attention to Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Attention To Person)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Bidding_To__c.field-meta.xml
<CustomField>
    <fullName>Bidding_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name the person you are bidding this quote to. This persons name will show up on the generated quote in the &quot;Attention&quot; field at the top of the PDF.</inlineHelpText>
    <label>Bidding To Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Bottom_Exception_Notes__c.field-meta.xml
<CustomField>
    <fullName>Bottom_Exception_Notes__c</fullName>
    <label>Closing Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Consulting_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Consulting_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consulting Engineer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Current_Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Current_Lead_Time__c</fullName>
    <inlineHelpText>Select the lead time on the project. This will display on generated documents.</inlineHelpText>
    <label>Current Lead Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Stock</fullName>
            </value>
            <value>
                <fullName>Less than 1 week</fullName>
            </value>
            <value>
                <fullName>1 - 2 weeks</fullName>
            </value>
            <value>
                <fullName>2 - 4 weeks</fullName>
            </value>
            <value>
                <fullName>4 - 6 weeks</fullName>
            </value>
            <value>
                <fullName>6 - 8 weeks</fullName>
            </value>
            <value>
                <fullName>8 - 10 weeks</fullName>
            </value>
            <value>
                <fullName>10 - 12 weeks</fullName>
            </value>
            <value>
                <fullName>12 - 14 weeks</fullName>
            </value>
            <value>
                <fullName>14 - 16 weeks</fullName>
            </value>
            <value>
                <fullName>16 - 18 weeks</fullName>
            </value>
            <value>
                <fullName>18 - 20 weeks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Customer_P_O__c.field-meta.xml
<CustomField>
    <fullName>Customer_P_O__c</fullName>
    <label>Customer P.O.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Hide_All_Tags__c.field-meta.xml
<CustomField>
    <fullName>Hide_All_Tags__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide All Tags</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Hide_Total_Base_Bid_Total__c.field-meta.xml
<CustomField>
    <fullName>Hide_Total_Base_Bid_Total__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Total Base Bid Total</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Hide_Total_Extended_Cost__c.field-meta.xml
<CustomField>
    <fullName>Hide_Total_Extended_Cost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Total Extended Cost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Include_Cover_Letter__c.field-meta.xml
<CustomField>
    <fullName>Include_Cover_Letter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include Cover Letter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <inlineHelpText>Where will the equipment be shipped to?</inlineHelpText>
    <label>Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <formula>Opportunity.Opportunity_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Original_Name__c.field-meta.xml
<CustomField>
    <fullName>Original_Name__c</fullName>
    <description>To hold original Quote Name</description>
    <inlineHelpText>This is the quote name that was used initially when the quote was created. This is the revision folder name in SharePoint.This is for reference purposes only.</inlineHelpText>
    <label>SharePoint Folder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Plan_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Date__c</fullName>
    <inlineHelpText>This is the date the &quot;plans and drawings&quot; have from the client.</inlineHelpText>
    <label>Plan Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/prepared_by_user__c.field-meta.xml
<CustomField>
    <fullName>prepared_by_user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prepared by user (User)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CreateBy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <label>Revision</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Scope_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Work__c</fullName>
    <inlineHelpText>Type a cover letter if required.</inlineHelpText>
    <label>Cover Letter</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Submittal_Closing_Comments__c.field-meta.xml
<CustomField>
    <fullName>Submittal_Closing_Comments__c</fullName>
    <label>Submittal Closing Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Submittal_opening_comments__c.field-meta.xml
<CustomField>
    <fullName>Submittal_opening_comments__c</fullName>
    <label>Submittal Opening Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Submittal_Revision_Number__c.field-meta.xml
<CustomField>
    <fullName>Submittal_Revision_Number__c</fullName>
    <label>Submittal Revision Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <default>true</default>
                <label>00</label>
            </value>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/This_data_is_submitted_for__c.field-meta.xml
<CustomField>
    <fullName>This_data_is_submitted_for__c</fullName>
    <label>This data is submitted for:</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approval</fullName>
            </value>
            <value>
                <fullName>Record Purposes</fullName>
            </value>
            <value>
                <fullName>Re-Submittal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Top_Exception_Notes__c.field-meta.xml
<CustomField>
    <fullName>Top_Exception_Notes__c</fullName>
    <label>Opening Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Base_Bid_Total__c.field-meta.xml
<CustomField>
    <fullName>Total_Base_Bid_Total__c</fullName>
    <label>Total Base Bid Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Extended_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Extended_Cost__c</fullName>
    <label>Total Extended Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/GenerateSubmittalController.cls
/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 02-05-2024
 * @last modified by  : Nilesh Badrakiya
**/
public class GenerateSubmittalController{
    
    public List<Product_Group__c> lstProductGroups{get;set;}
    public Id quoteId{get;set;}
    public Quote quote{get;set;}
    public Product_Group__c currentSubGroup{get;set;}
    public Boolean isDenverUser{get;set;}
    public string officeName = null;
     
    public GenerateSubmittalController(Apexpages.StandardController stdCont){
   
        quoteId = stdCont.getId();
        
        quote = [Select Id, Name,Original_Name__c,Scope_of_Work__c,Opportunity_Number__c,Opportunity.Name, Opportunity.Owner.Name,QuoteNumber,Include_Cover_Letter__c,
                    Top_Exception_Notes__c,Bottom_Exception_Notes__c,Hide_Total_Extended_Cost__c ,Hide_Total_Base_Bid_Total__c,
                    Total_Base_Bid_Total__c,Total_Extended_Cost__c,Hide_All_Tags__c,Submittal_opening_comments__c,Submittal_Closing_Comments__c,
                    Consulting_Engineer__r.Name,Location__c,Customer_P_O__c,Revision__c,Current_Lead_Time__c,prepared_by_user__r.Name,
                    Submitted_By__r.Name,This_data_is_submitted_for__c,Submittal_Revision_Number__c,Opportunity.Opportunity_Number__c,
                    Attention_to_Account__r.Name,Bidding_To__r.Name,Plan_Date__c,Attention_To_Person__r.Name,Consulting_Engineer_Account__c,
                    Opportunity.Consulting_Engineer_Contact_Person__r.Account.Name,Opportunity.OriginalName__c,GEN__c,Attention_to_Contact__r.Name,SubmittalDocumentVersion__c,
                    Opportunity.RecordType.Name, Opportunity.CreatedDate,Opportunity.CreatedById
                    From Quote Where Id =: quoteId];

         User currentUser = [SELECT Office_Location__c 
                            FROM User 
                            WHERE Id = :quote.Opportunity.CreatedById];
        /*if(currentUser.Office_Location__c != null) {
            
            if(currentUser.Office_Location__c.equalsIgnoreCase(UtilitySharePointToSFIntegration.DENVER_CITY)) 
                officeName = 'Engineered Products';
            else
                officeName = currentUser.Office_Location__c;   
        }*/

        String subGroupId = apexpages.currentpage().getparameters().get('subGroupId');
        if(subGroupId != null && subGroupId != ''){
            lstProductGroups = [Select Id,Name,Hide_Quantity__c,    
                                (SELECT Descriptions__c,Tag__c,Product_Code__c,Product_Name__c,Quote__c,Quantity__c,Page_Break__c,Hide_Quantity__c  
                                    FROM Quote_Line_Items__r WHERE Hide_Line__c = false
                                    ORDER BY Row_Index__c ASC)
                                From Product_Group__c 
                                WHERE Quote__c =: quoteId
                                AND Id =: subGroupId
                                ORDER BY Index__c ASC]; 
            currentSubGroup = lstProductGroups[0];
        }
        else{
            lstProductGroups = [Select Id,Name,Hide_Quantity__c ,   
                                    (SELECT Descriptions__c,Tag__c,Product_Code__c,Product_Name__c,Quote__c,Quantity__c,Page_Break__c,Hide_Quantity__c  
                                        FROM Quote_Line_Items__r WHERE Hide_Line__c = false
                                        ORDER BY Row_Index__c ASC)
                                    From Product_Group__c 
                                    WHERE Quote__c =: quoteId
                                    AND Parent_Product_Group__c != null
                                    ORDER BY Index__c ASC]; 
        }
        isDenverUser = checkIsDenverUser();
    }
    
    public Boolean checkIsDenverUser(){
        
        for (GroupMember user : [Select Id, UserOrGroupId From GroupMember Where Group.Name = 'Engineered Products']){
            if(user.UserOrGroupId == UserInfo.getUserId()){ 
                return true;
            }
        }
        
        if(quote.OpportunityId != null){
            List<Opportunity> lstOpportunity = [Select Id,Office__c,Opportunity.RecordType.Name,
                                                        CreatedById                    
                                                From Opportunity
                                                WHERE Id =: quote.OpportunityId];
                                
            if(!lstOpportunity.isEmpty()){
                officeName = UtilitySharePointToSFIntegration.assigneSharepointRootFolder(lstOpportunity[0]);
                Opportunity opp = lstOpportunity[0];
                if(opp.RecordType.Name == 'Parts' && opp.Office__c == 'Engineered Products'){
                  return true;
                }
            }
        }
        
        return false;
    }
    
    public PageReference generateAttachment(){
        
        Integer versionnumber = quote.SubmittalDocumentVersion__c != null ? Integer.valueOf(quote.SubmittalDocumentVersion__c) : 0;
        versionnumber ++;
        Quote updateVersion = new Quote(SubmittalDocumentVersion__c = versionnumber,Id = quote.Id);
        
        // construct encoded opportunity name
        String oppName = Quote.Opportunity.Opportunity_Number__c + ' ' + Quote.Opportunity.OriginalName__c;
        oppName = EncodingUtil.urlEncode(oppName, 'UTF-8');
        oppName = oppName.replace('+',' ');

        String TimeStamp = String.valueOf(system.now());
        TimeStamp = TimeStamp.replace('-','');
        TimeStamp = TimeStamp.replace(' ','');
        TimeStamp = TimeStamp.replace(':','');
        // create for aaproval sub folder under quote submittals
        /*string quoteSubFolder = UtilitySharePointToSFIntegration.opportunityFolderNamesMap.get(3)+'/'+
                                quote.QuoteNumber +' '+quote.Name+ '/'+
                                UtilitySharePointToSFIntegration.quoteFolderNamesMap.get(1); */
                                
        /*String folderPath = UtilitySharePointToSFIntegration.MainFolderOpeningPath + 
                            quote.Opportunity.Opportunity_Number__c+' '+quote.Opportunity.OriginalName__c+'/' +
                            UtilitySharePointToSFIntegration.opportunityFolderNamesMap.get(3) + '/' +
                            quote.QuoteNumber +' '+quote.Original_Name__c + '/' +
                            UtilitySharePointToSFIntegration.quoteFolderNamesMap.get(3) + '/'+
                            'V'+versionnumber+' '+UtilitySharePointToSFIntegration.submittalSubFolder +
                            UtilitySharePointToSFIntegration.MainFolderClosingPath; */
                            
         //folderPath = folderPath .replace(' ','%20');
        
        //SharePointRestServiceCallOut.authenticateSharePoint();    
        //SharePointRestServiceCallOut.createFolder(folderPath);
            
        List<Attachment> lstAttachmentsToInsert = new List<Attachment>();
        if(UtilitySharePointToSFIntegration.OPP_EQUIPMENT_RECORDTYPE == quote.Opportunity.RecordType.Name || UtilitySharePointToSFIntegration.OPP_EQUIPMENT_DESIGN_BUILD_RECORDTYPE == quote.Opportunity.RecordType.Name
        || UtilitySharePointToSFIntegration.OPP_REPAIR_RECORDTYPE == quote.Opportunity.RecordType.Name) {
            if (lstProductGroups.size() > 0) {
                
                update updateVersion;
            }
            for(Product_Group__c pg : lstProductGroups){
                
            
                PageReference pdf = new PageReference('/apex/GenerateSubmittal?Id='+quoteId+'&subGroupId='+pg.Id);
                
                /*String fileName = quote.QuoteNumber +' '+
                                  quote.Name +' '+
                                  pg.Name+' '+
                                  'For Approval '+
                                  ' V'+versionnumber+
                                  '.'+'pdf';*/
                                  
                String fileName = quote.Opportunity_Number__c + '.';
                fileName += quote.QuoteNumber.substringAfter('-') + ' - ';                 
                fileName += quote.Opportunity.OriginalName__c;
                fileName += ' '+pg.Name;
                fileName += ' Submittal'+versionnumber;
                fileName += '.pdf';                  

                // construct encoded file name
                String encodedFileName =  EncodingUtil.urlEncode(FileName, 'UTF-8').replace('+', '%20');
                system.debug('encodedScopeName ==>'+encodedFileName );                    
                        
                //String fileName = TimeStamp+' '+quote.Opportunity.Opportunity_Number__c + ' - ' + quote.QuoteNumber + ' ' + quote.Opportunity.Name + ' ' + pg.Name + ' SUBMITTAL REV ' + quote.Submittal_Revision_Number__c + '.pdf';
                blob body;
            
                if(Test.isRunningTest()) { 
                    body = blob.valueOf('Unit.Test');
                } else {
                    body = pdf.getContentAsPDF();
                }
                
                String filePath = UtilitySharePointToSFIntegration.RootFolderForFilePath + 
                                quote.Opportunity.CreatedDate.Year();
                if(officeName != null && !UtilitySharePointToSFIntegration.isCurrentUserFromEngineeredProducts()) {
                    filePath = filePath + '/' + officeName;
                }
                filePath = filePath + '/' + oppName +'/' ;
                if(UtilitySharePointToSFIntegration.OPP_EQUIPMENT_RECORDTYPE == quote.Opportunity.RecordType.Name || UtilitySharePointToSFIntegration.OPP_EQUIPMENT_DESIGN_BUILD_RECORDTYPE == quote.Opportunity.RecordType.Name) {
                    if(UtilitySharePointToSFIntegration.isCurrentUserFromEngineeredProducts()) {
                        filePath = filePath + UtilitySharePointToSFIntegration.equipmentOpportunityFolders.get(22);
                    } else {
                        filePath = filePath + UtilitySharePointToSFIntegration.equipmentOpportunityFolders.get(16);
                    }
                } else if(UtilitySharePointToSFIntegration.OPP_REPAIR_RECORDTYPE == quote.Opportunity.RecordType.Name) {
                    filePath = filePath + UtilitySharePointToSFIntegration.repairOpportunityFolders.get(22);
                }
                
                system.debug('filePath=>'+filePath);         
                                  //+'/'+UtilitySharePointToSFIntegration.fetchQuoteFolderName(quote) + '/' +
                                  //UtilitySharePointToSFIntegration.quoteFolderNamesMap.get(3) + '/'+
                                  //UtilitySharePointToSFIntegration.submittalSubFolder; 
                CreateAttachmentInSharePoint.createFile(filePath,
                                                        encodedFileName,
                                                        body,
                                                        'Submittal',
                                                        updateVersion.Id);
                
                Attachment newAttachment = new Attachment();
                newAttachment.Name = fileName;
                newAttachment.IsPrivate = false;
                newAttachment.ParentId = quoteId;
                if(!Test.isRunningTest()){
                    newAttachment.body = pdf.getContentAsPDF();
                }
                else{
                    Blob content = Blob.valueOf('UNIT.TEST');
                    newAttachment.body = content;
                }
                lstAttachmentsToInsert.add(newAttachment);
        }
            

            
        }
        
        if(!lstAttachmentsToInsert.isEmpty()){
            insert lstAttachmentsToInsert;
        }
        
        
        PageReference pr = new PageReference('/'+quoteId);
        pr.setRedirect(true);
        return pr;
        
    }
    
}