force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a look up to account record to store end user.</description>
    <inlineHelpText>Please select an end user for this opportunity.</inlineHelpText>
    <label>End User Business Name (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>EndUserOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Base_Bid_Total_Quote__c.field-meta.xml
<CustomField>
    <fullName>Total_Base_Bid_Total_Quote__c</fullName>
    <inlineHelpText>This is the total base bid for the quote currently synced with this opportunity.</inlineHelpText>
    <label>Base Bid Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OpportunityEndUser.cls
public class OpportunityEndUser{
    
    public Id accountId{get;set;}
    public List<Opportunity> lstOpportunity{get;set;}
    
    public OpportunityEndUser(Apexpages.StandardController stdCon){
        accountId = stdCon.getId();
        getOpportunities();
    }
    
    public void getOpportunities(){
        
        lstOpportunity = [Select Id, Name, StageName, Total_Base_Bid_Total_Quote__c, CloseDate From Opportunity Where End_User__c =: accountId];
            
        
    }
    
}