force-app/main/default/objects/Opportunity/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <inlineHelpText>Which Midwest Group office is this for?</inlineHelpText>
    <label>Midwest Group Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Midwest Machinery STL</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery KC</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery OK</fullName>
            </value>
            <value>
                <fullName>Engineered Products</fullName>
            </value>
            <value>
                <fullName>MaRRS</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
            <value>
                <fullName>Spark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Base_Bid_Total_Quote__c.field-meta.xml
<CustomField>
    <fullName>Total_Base_Bid_Total_Quote__c</fullName>
    <inlineHelpText>This is the total base bid for the quote currently synced with this opportunity.</inlineHelpText>
    <label>Base Bid Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Project_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin__c</fullName>
    <label>Total Project Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/Sales_Representative__c.object-meta.xml
<CustomObject>
    <label>Sales Representative</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sales Representative Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Representative__c/fields/Commision__c.field-meta.xml
<CustomField>
    <fullName>Commision__c</fullName>
    <label>Commision</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Engineer Split</relationshipLabel>
    <relationshipName>SalesRepresentatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepresentatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ActualForecastBookingControllerTest.cls
@isTest
private class ActualForecastBookingControllerTest {

    @TestSetup
    static void createData(){

        Account objAccount = new Account();
        objAccount.Name = 'Test Account';
        objAccount.AcctSeed__Accounting_Type__c = 'Customer';
        insert objAccount;

        Opportunity objOpportunityActual = new Opportunity();
        objOpportunityActual.AccountId = objAccount.Id;
        objOpportunityActual.Name = 'Test Opportuntiy Actual Booking';
        objOpportunityActual.StageName = 'Closed Won';
        objOpportunityActual.Project_Manager__c = UserInfo.getUserId();
        objOpportunityActual.CloseDate = Date.Today();
        objOpportunityActual.Total_Base_Bid_Total_Quote__c = 10000;
        objOpportunityActual.Total_Project_Margin__c = 20000;
        objOpportunityActual.Office__c = 'Midwest Machinery STL';
        
        Opportunity objOpportunityForecast = new Opportunity();
        objOpportunityForecast.AccountId = objAccount.Id;
        objOpportunityForecast.Name = 'Test Opportuntiy Forecast Booking';
        objOpportunityForecast.StageName = 'Bidding';
        objOpportunityForecast.Project_Manager__c = UserInfo.getUserId();
        objOpportunityForecast.CloseDate = Date.Today();
        objOpportunityForecast.Total_Base_Bid_Total_Quote__c = 10000;
        objOpportunityForecast.Total_Project_Margin__c = 20000;
        
        insert new List<Opportunity>{objOpportunityActual, objOpportunityForecast};

        Sales_Representative__c objSalesRep = new Sales_Representative__c();
        objSalesRep.Commision__c = 100;
        objSalesRep.Opportunity__c = objOpportunityActual.Id;
        objSalesRep.Sales_Rep__c = UserInfo.getUserId();

        Sales_Representative__c objSalesRep1 = new Sales_Representative__c();
        objSalesRep1.Commision__c = 100;
        objSalesRep1.Opportunity__c = objOpportunityForecast.Id;
        objSalesRep1.Sales_Rep__c = UserInfo.getUserId();
        insert new List<Sales_Representative__c>{objSalesRep, objSalesRep1};
    }

	static testMethod void testActualBooking() {
        Apexpages.currentpage().getparameters().put('selectSalesRep', UserInfo.getUserId());
        Apexpages.currentpage().getparameters().put('reportType','Actual Booking');
        Apexpages.currentpage().getparameters().put('duration','12');
        ActualForecastBookingController objActualForecastBookingController = new ActualForecastBookingController();
        objActualForecastBookingController.getOpportunity();
        
    }

    static testMethod void testForecastBooking() {
        Apexpages.currentpage().getparameters().put('selectSalesRep', UserInfo.getUserId());
        Apexpages.currentpage().getparameters().put('reportType','Forecast Booking');
        Apexpages.currentpage().getparameters().put('duration','12');
        ActualForecastBookingController objActualForecastBookingController = new ActualForecastBookingController();
        objActualForecastBookingController.getOpportunity();
    }
}