force-app/main/default/objects/Opportunity/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <inlineHelpText>Which Midwest Group office is this for?</inlineHelpText>
    <label>Midwest Group Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Midwest Machinery STL</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery KC</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery OK</fullName>
            </value>
            <value>
                <fullName>Engineered Products</fullName>
            </value>
            <value>
                <fullName>MaRRS</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
            <value>
                <fullName>Spark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Date__c</fullName>
    <inlineHelpText>When do you estimate the equipment will ship?</inlineHelpText>
    <label>Estimated Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Targeted__c.field-meta.xml
<CustomField>
    <fullName>Targeted__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Use this checkbox to flag the opportunity so it stays on your &quot;radar&quot; at all times regardless of stage.</inlineHelpText>
    <label>Targeted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Base_Bid_Total_Quote__c.field-meta.xml
<CustomField>
    <fullName>Total_Base_Bid_Total_Quote__c</fullName>
    <inlineHelpText>This is the total base bid for the quote currently synced with this opportunity.</inlineHelpText>
    <label>Base Bid Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Project_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin__c</fullName>
    <label>Total Project Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/Sales_Representative__c.object-meta.xml
<CustomObject>
    <label>Sales Representative</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sales Representative Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Representatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Representative__c/fields/Commision__c.field-meta.xml
<CustomField>
    <fullName>Commision__c</fullName>
    <label>Commision</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Engineer Split</relationshipLabel>
    <relationshipName>SalesRepresentatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Representative__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepresentatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TopOpportunitiesControllerTest.cls
@isTest
public with sharing class TopOpportunitiesControllerTest {

   @testSetup static void setup()
   {
       Account acctobj = new Account();
       acctobj.Name = 'Testing oppo';
       acctobj.AcctSeed__Accounting_Type__c = 'Customer';
       insert acctobj;

       Opportunity testobjOppo = new Opportunity();
       testobjOppo.Name = 'Test opportunity';
       testobjOppo.AccountId = acctobj.Id;
       testobjOppo.StageName = 'TARGET_NEGOTIATING';
       testobjOppo.Project_Manager__c = UserInfo.getUserId();
       testobjOppo.Office__c = 'Midwest Machinery STL';
       testobjOppo.Total_Project_Margin__c = 1520;
       testobjOppo.Total_Base_Bid_Total_Quote__c = 2150;
       testobjOppo.Probability = 70;
       testobjOppo.Ship_Date__c = Date.today();
       testobjOppo.closeDate = Date.today();
       testobjOppo.Targeted__c = true;
       
       insert testobjOppo;
       System.debug('TestOpportunity Inserted: '+testobjOppo);

       Sales_Representative__c testsalesRep = new Sales_Representative__c();  
       testsalesRep.Commision__c = 100;
       testsalesRep.Sales_Rep__c = UserInfo.getUserId(); 
       testsalesRep.Opportunity__c = testobjOppo.Id;
       insert testsalesRep ;
       System.debug('TestsalesRep testsalesRep: '+testsalesRep);

   } 

    @isTest static void testgetSalesRepOppoIds(){
        TopOpportunitiesController topOppController = new TopOpportunitiesController();
        TopOpportunitiesController.getSalesRepOpportunityIds(UserInfo.getUserId());
        //else if case
        TopOpportunitiesController.getSalesRepOpportunityIds('Oklahoma');
        //for else case
        TopOpportunitiesController.getSalesRepOpportunityIds('Midwest Machinery');
    }

    @isTest static void testgetSetFromStageName(){
        TopOpportunitiesController.getSetFromStageName('TARGET/NEGOTIATING');

    }
    @isTest static void testbuildOpporunityWrapper(){
        TopOpportunitiesController.buildOpporunityWrapper('TARGET/NEGOTIATING' , UserInfo.getUserId());
        //for else case 
        TopOpportunitiesController.buildOpporunityWrapper('BIDDING' , UserInfo.getUserId());   
    }
}