force-app/main/default/objects/Opportunity/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <inlineHelpText>Which Midwest Group office is this for?</inlineHelpText>
    <label>Midwest Group Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Midwest Machinery STL</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery KC</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery OK</fullName>
            </value>
            <value>
                <fullName>Engineered Products</fullName>
            </value>
            <value>
                <fullName>MaRRS</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
            <value>
                <fullName>Spark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sync_Quote__c.field-meta.xml
<CustomField>
    <fullName>Sync_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sync Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.OpportunityId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/MaRRS.recordType-meta.xml
<RecordType>
    <fullName>MaRRS</fullName>
    <active>true</active>
    <businessProcess>MaRRS</businessProcess>
    <description>MaRRS quotes for freight and distribution</description>
    <label>MaRRS</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Midwest_Group_Office__c.field-meta.xml
<CustomField>
    <fullName>Midwest_Group_Office__c</fullName>
    <label>Midwest Group Office</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Midwest Machinery STL</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery KC</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery OK</fullName>
            </value>
            <value>
                <fullName>Engineered Products</fullName>
            </value>
            <value>
                <fullName>MaRRS</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
            <value>
                <fullName>Spark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Parent_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipLabel>Product Groups (Parent Product Group)</relationshipLabel>
    <relationshipName>ProductGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Product Groups</relationshipLabel>
    <relationshipName>Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/Product_Select__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Select__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>ProductSelects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Scope_Revision_Number__c.field-meta.xml
<CustomField>
    <fullName>Scope_Revision_Number__c</fullName>
    <label>Scope/Quote Revision Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <default>true</default>
                <label>00</label>
            </value>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Submittal_Revision_Number__c.field-meta.xml
<CustomField>
    <fullName>Submittal_Revision_Number__c</fullName>
    <label>Submittal Revision Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <default>true</default>
                <label>00</label>
            </value>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MarrsConfigureQuoteTest.cls
@isTest

private class MarrsConfigureQuoteTest {

    static testMethod void testMarsConfigureQuote2() {
        Quote newQuote = [SELECT Id,Name,opportunityId From Quote limit 1];
        ApexPages.StandardController sc = new ApexPages.StandardController(newQuote);
        MarrsConfigureQuoteController marsQuoteConfigure = new MarrsConfigureQuoteController(sc);
        marsQuoteConfigure.subGroupNameCreateGroup = 'subGroup1';
        marsQuoteConfigure.groupName = 'grp name';
        marsQuoteConfigure.addNewGroup();
        Id groupId = [SELECT Id 
                        FROM Product_Group__c 
                        WHERE Quote__c = :newQuote.Id 
                        AND Parent_Product_Group__c = null
                        LIMIT 1].Id;
        Id hidSubGrpId = [SELECT Id 
                            FROM Product_Group__c 
                            WHERE Quote__c = :newQuote.Id 
                            AND Parent_Product_Group__c = :groupId
                            LIMIT 1].Id; 

        // line item operations
        Product_Select__c objChildLineItem = new Product_Select__c();
        objChildLineItem.Product_Name__c = 'Child Product Name';
        objChildLineItem.Quote__c = newQuote.Id;
        objChildLineItem.Product_Group__c = hidSubGrpId;
        objChildLineItem.Sales_Price__c = 10;
        insert objChildLineItem;
        marsQuoteConfigure.lstGroups = marsQuoteConfigure.prepareCartPage();     
        marsQuoteConfigure.cloneLineItem();
        marsQuoteConfigure.deleteLineItem();
        marsQuoteConfigure.hidGroupId = groupId;

        marsQuoteConfigure.cloneGroup();
        marsQuoteConfigure.subGroupNameCreateSubGroup = 'subGroup2';
        marsQuoteConfigure.addNewSubGroup();


        marsQuoteConfigure.hidSubGroupId = hidSubGrpId;
        Test.startTest();
        marsQuoteConfigure.cloneSubGroup();
        
        marsQuoteConfigure.hidSubGroupIndex = 1;
        marsQuoteConfigure.deleteSubGroup();

        marsQuoteConfigure.hidGroupIndex = 1;
        marsQuoteConfigure.deleteGroup();

        marsQuoteConfigure.saveAndExit();
        marsQuoteConfigure.redirectToQuote();
        marsQuoteConfigure.addProduct();
        marsQuoteConfigure.addProducts();
        marsQuoteConfigure.searchProduct = 'testSA';
        marsQuoteConfigure.searchProducts();
        marsQuoteConfigure.getProducts();
        marsQuoteConfigure.addProductsToCart();
      
        marsQuoteConfigure.previewQuote();

        
        marsQuoteConfigure.first();
        marsQuoteConfigure.previous();
        marsQuoteConfigure.last();
        marsQuoteConfigure.next();
        Test.stopTest();

        
    }

    static testMethod void testMarsConfigureQuote() {
        Quote newQuote = [SELECT Id,Name,opportunityId From Quote limit 1];
        ApexPages.StandardController sc = new ApexPages.StandardController(newQuote);
        MarrsConfigureQuoteController marsQuoteConfigure = new MarrsConfigureQuoteController(sc);
        marsQuoteConfigure.subGroupNameCreateGroup = 'subGroup1';
        marsQuoteConfigure.groupName = 'grp name';
        marsQuoteConfigure.addNewGroup();
        Id groupId = [SELECT Id 
                        FROM Product_Group__c 
                        WHERE Quote__c = :newQuote.Id 
                        AND Parent_Product_Group__c = null
                        LIMIT 1].Id;
        Id hidSubGrpId = [SELECT Id 
                            FROM Product_Group__c 
                            WHERE Quote__c = :newQuote.Id 
                            AND Parent_Product_Group__c = :groupId
                            LIMIT 1].Id; 

        // line item operations
        Product_Select__c objChildLineItem = new Product_Select__c();
        objChildLineItem.Product_Name__c = 'Child Product Name';
        objChildLineItem.Quote__c = newQuote.Id;
        objChildLineItem.Product_Group__c = hidSubGrpId;
        objChildLineItem.Sales_Price__c = 10;
        insert objChildLineItem;
        marsQuoteConfigure.lstGroups = marsQuoteConfigure.prepareCartPage();
        marsQuoteConfigure.hidLineItemIndex = 0;
        marsQuoteConfigure.hidSubGroupIndex = 0;
        marsQuoteConfigure.hidGroupIndex = 0;
        system.debug('marrsQuoteConfigure=>'+marsQuoteConfigure.lstGroups.size());
        marsQuoteConfigure.updateDescription();  
    }

    static testMethod void testProductWrapper() {

        Quote newQuote = [SELECT Id,Name,opportunityId From Quote limit 1];
        PricebookEntry customPrice = [SELECT id FROM PricebookEntry WHERE UnitPrice = 12000];
        ProductWrapper productWrapper = new ProductWrapper(true, customPrice);
        List<Product_Group__c> testProductGroup = CartQueryHelper.getGroupsAndSubGroups(newQuote.Id);
        List<AcctSeedERP__Sales_Order_Line__c> testSalesOrderLine = CartQueryHelper.getAccountingSeedLineItemsForPMTool(newQuote.Id);
        // This code is for GroupWrapper And Subgroup
        GroupWrapper gp = new GroupWrapper();
        SubGroup sb = new SubGroup();
    }


    @testSetup static void createData() {
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.closeDate = Date.today();
        objOpportunity.Name = 'Test Opportunity';
        objOpportunity.stageName = 'Draft';
        objOpportunity.Office__c = 'MaRRs';
        insert objOpportunity;
        
        Quote newQuote = new Quote();
        newQuote.Name = 'Test Quote';
        newQuote.opportunityId = objOpportunity.Id;
        newQuote.Scope_Revision_Number__c = '01';
        newQuote.Submittal_Revision_Number__c = '01';
        //newQuote.recordTypeId = [SELECT ]
        insert newQuote;

        objOpportunity.Sync_Quote__c = newQuote.Id;
        update objOpportunity;

        Product2 prod = new Product2(Name = 'testSA 1', 
            Family = 'Recold', Midwest_Group_Office__c = 'MaRRs');
        insert prod;
        System.debug('Product2 :-' + prod);

        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        System.debug('PricebookEntry :-' + prod);

        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;

        PricebookEntry customPrice = new PricebookEntry(
            Pricebook2Id = customPB.Id, Product2Id = prod.Id,
            UnitPrice = 12000, IsActive = true);
        insert customPrice;
        
    }
}