force-app/main/default/objects/Opportunity/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <inlineHelpText>Which Midwest Group office is this for?</inlineHelpText>
    <label>Midwest Group Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Midwest Machinery STL</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery KC</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery OK</fullName>
            </value>
            <value>
                <fullName>Engineered Products</fullName>
            </value>
            <value>
                <fullName>MaRRS</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
            <value>
                <fullName>Spark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{YY}-{0000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OriginalName__c.field-meta.xml
<CustomField>
    <fullName>OriginalName__c</fullName>
    <label>Original Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/assignPermissionInSharepointFolderTest.cls
@isTest
private class assignPermissionInSharepointFolderTest {



    @isTest static void testPermissionAssignment() {
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.closeDate = Date.today();
        objOpportunity.Name = 'Test Opportunity';
        //objOpportunity.OriginalName__c = 'Test Opportunity';
        objOpportunity.stageName = 'Draft';
        insert objOpportunity;
        
        objOpportunity = [SELECT  Id,CreatedById, CreatedDate,RecordType.Name,Office__c,Opportunity_Number__c,OriginalName__c FROM Opportunity];
        
        /*Test.StartTest();
            //Database.executeBatch(obj,25);
            Test.setMock(HttpCalloutMock.class, new MockHttpSharePointResponseGenerator());  
            
            assignPermissionInSharepointFolder bclass = new assignPermissionInSharepointFolder();  
            Database.executeBatch(bclass ,25);  
            Database.BatchableContext bc;
            
              MyIterable  itrbl = (MyIterable)bclass.start();  //start() returns an iterable, in my case, a custom iterable. Note the casting
              MyIterator  itrator = (MyIterator) itrbl.iterator();  // continue simulation of start() by constructing the iterator
              List<Opportunity> aScopeList = new List<Opportunity> ();      // create scope for execute() by iterating against the result of the mocked callout
              while (itrator.hasNext()) {
                 aScopeList.add(itrator.next());
              }   
            
            bClass.execute(bc,aScopeList);
            bClass.finish(bc);
            
            
         Test.stopTest();*/
         
        Test.startTest();
        Database.BatchableContext bc;
            Test.setMock(HttpCalloutMock.class, new MockHttpSharePointResponseGenerator());
            new assignPermissionInSharepointFolder().start(bc);
            new assignPermissionInSharepointFolder().execute(bc,new List<Opportunity>{objOpportunity});
            new assignPermissionInSharepointFolder().finish(bc);
        Test.stopTest();
    
    }
}