force-app/main/default/objects/Opportunity/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <inlineHelpText>Which Midwest Group office is this for?</inlineHelpText>
    <label>Midwest Group Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Midwest Machinery STL</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery KC</fullName>
            </value>
            <value>
                <fullName>Midwest Machinery OK</fullName>
            </value>
            <value>
                <fullName>Engineered Products</fullName>
            </value>
            <value>
                <fullName>MaRRS</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
            <value>
                <fullName>Spark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{YY}-{0000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OriginalName__c.field-meta.xml
<CustomField>
    <fullName>OriginalName__c</fullName>
    <label>Original Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saint Louis</fullName>
            </value>
            <value>
                <fullName>Oklahoma</fullName>
            </value>
            <value>
                <fullName>Kansas City</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/sharePointPageUrl.cls
global class sharePointPageUrl {
public Static Boolean DenverUser;   
public static final string DENVER_CITY = 'Denver'; 
Public static User currentUser ;
 public static Boolean isDenverUser(String groupName) {
     try {
            DenverUser = UtilitySharePointToSFIntegration.isCurrentUserExistInGroup(groupName);
        } catch(Exception ex) {
            
            string message = 'Somthing went wrong while determining the user Group Error details : ';
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, message+ex));
        }
     return DenverUser;
 }

     public static Boolean isCurrentUserFromEngineeredProducts(User owner) {
        try { 
                if(owner.Office_Location__c.equalsIgnoreCase(DENVER_CITY)) {
                    return true;
                } else {
                    return false;
                }
        } catch(Exception ex) {
            return false;
        }
        
    }
 
  webservice static String fetchSharePointPageUrl(String opportunityId) {
    Opportunity oppRecord = [SELECT Id,
                                    OriginalName__c,
                                    Opportunity_Number__c,
                                    CreatedById,
                                    CreatedDate,
                                    RecordType.Name,Office__c
                            FROM Opportunity 
                            WHERE Id =: opportunityId];
    User oppOwner = [SELECT Office_Location__c FROM User WHERE Id = :oppRecord.CreatedById];
    String officeName = UtilitySharePointToSFIntegration.assigneSharepointRootFolder(oppRecord);
    String url;
    String folderName = oppRecord.Opportunity_Number__c +' '+oppRecord.OriginalName__c;
    
    String folderURL = 'https://midwestmach.sharepoint.com/';
    if (isCurrentUserFromEngineeredProducts(oppOwner)) {
        folderURL = folderURL + 'Engineered Products/';
    } else {
        folderURL = folderURL + 'Salesforce/';
    }
    
    folderURL = folderURL + 'Forms/AllItems.aspx?id=/';
    
    String opportunityFolderPath;
    if (isCurrentUserFromEngineeredProducts(oppOwner)) {
        opportunityFolderPath = 'Engineered Products/Salesforce/';
    } else {
           opportunityFolderPath = 'Salesforce/Salesforce/';
    }
    opportunityFolderPath = opportunityFolderPath + oppRecord.CreatedDate.Year();
    if(officeName != null && !isCurrentUserFromEngineeredProducts(oppOwner)) {
            opportunityFolderPath = opportunityFolderPath + '/' + officeName;
    }
    opportunityFolderPath = opportunityFolderPath + '/' + folderName;

    system.debug('encoded url==>>'+EncodingUtil.urlEncode(opportunityFolderPath, 'UTF-8'));
    
    opportunityFolderPath = EncodingUtil.urlEncode(opportunityFolderPath, 'UTF-8');
    folderURL = folderURL + opportunityFolderPath ;
    system.debug('folderURL==>'+folderURL);
    return folderURL;
  
  }

    webservice static void createFolderInSharepoint(String opportunityId) {
        Opportunity opp = [SELECT Id,
                                  Name 
                            FROM Opportunity 
                            WHERE Id =: opportunityId];

        opp.OriginalName__c = opp.Name.replaceAll('[^a-zA-Z0-9\\s+]', ' ');
        update opp;

        Database.executeBatch(new createfolderForOpportunity(opportunityId));

    }

}