force-app/main/default/objects/Opportunity/fields/Sync_Quote__c.field-meta.xml
<CustomField>
    <fullName>Sync_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sync Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.OpportunityId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Base_Bid_Total_Quote__c.field-meta.xml
<CustomField>
    <fullName>Total_Base_Bid_Total_Quote__c</fullName>
    <inlineHelpText>This is the total base bid for the quote currently synced with this opportunity.</inlineHelpText>
    <label>Base Bid Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Extended_Cost_Quote__c.field-meta.xml
<CustomField>
    <fullName>Total_Extended_Cost_Quote__c</fullName>
    <label>Total Extended Cost (Quote)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Project_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin__c</fullName>
    <label>Total Project Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Base_Bid_Total__c.field-meta.xml
<CustomField>
    <fullName>Total_Base_Bid_Total__c</fullName>
    <label>Total Base Bid Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Extended_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Extended_Cost__c</fullName>
    <label>Total Extended Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Project_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin__c</fullName>
    <label>Total Project Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SyncQuoteBackToOpportunityController.cls
public with sharing class SyncQuoteBackToOpportunityController{
    
    public String quoteId{get;set;}
    public Quote quoteRecord{get;set;}
    
    public SyncQuoteBackToOpportunityController(Apexpages.StandardController stdCont){
        quoteId = stdCont.getId();
        quoteRecord = [Select Id,OpportunityId,Total_Base_Bid_Total__c,Total_Extended_Cost__c,Total_Project_Margin__c
                        FROM Quote
                        WHERE Id =: quoteId];
    }
    
    public PageReference syncBackToOpportunity(){
        
        List<Opportunity> lstOpportunity = [Select Id,Total_Base_Bid_Total_Quote__c,Total_Extended_Cost_Quote__c,Sync_Quote__c,Total_Project_Margin__c 
                                            From Opportunity
                                            WHERE Id =: quoteRecord.opportunityId];
                                            
        if(!lstOpportunity.isEmpty()){
            lstOpportunity[0].Total_Base_Bid_Total_Quote__c = quoteRecord.Total_Base_Bid_Total__c;
            lstOpportunity[0].Total_Extended_Cost_Quote__c = quoteRecord.Total_Extended_Cost__c;
            lstOpportunity[0].Total_Project_Margin__c = quoteRecord.Total_Project_Margin__c;
            lstOpportunity[0].Sync_Quote__c = quoteRecord.Id;
            
            update lstOpportunity[0];
        }
        
        PageReference pr = new PageReference('/'+quoteRecord.Id);
        pr.setRedirect(true);
        return pr;
        
    }
    
}