force-app/main/default/objects/Opportunity/fields/Sync_Quote__c.field-meta.xml
<CustomField>
    <fullName>Sync_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sync Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.OpportunityId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Base_Bid_Total_Quote__c.field-meta.xml
<CustomField>
    <fullName>Total_Base_Bid_Total_Quote__c</fullName>
    <inlineHelpText>This is the total base bid for the quote currently synced with this opportunity.</inlineHelpText>
    <label>Base Bid Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Extended_Cost_Quote__c.field-meta.xml
<CustomField>
    <fullName>Total_Extended_Cost_Quote__c</fullName>
    <label>Total Extended Cost (Quote)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Project_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin__c</fullName>
    <label>Total Project Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Is_Active_Project_Financials__c.field-meta.xml
<CustomField>
    <fullName>Is_Active_Project_Financials__c</fullName>
    <formula>IF(Id = Opportunity.Active_Financial_Quote__c , true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active Project Financials</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Is_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Locked?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Base_Bid_Total__c.field-meta.xml
<CustomField>
    <fullName>Total_Base_Bid_Total__c</fullName>
    <label>Total Base Bid Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Extended_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Extended_Cost__c</fullName>
    <label>Total Extended Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Project_Margin__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin__c</fullName>
    <label>Total Project Margin ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Project_Margin_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Total_Project_Margin_Percentage__c</fullName>
    <label>Total Project Margin (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/QuoteRelatedListController.cls
public with sharing class QuoteRelatedListController{
    
    public List<Quote> lstQuote{get;set;}
    public String syncQuoteId{get;set;}
    public String oppId{get;set;}
    public Id deleteQuoteId{get;set;}
    
    public QuoteRelatedListController(Apexpages.standardController stdController){
        oppId = stdController.getId();
        
        lstQuote = [Select Id, Name, QuoteNumber, Is_Locked__c, Total_Base_Bid_Total__c, Total_Project_Margin__c,
                    Total_Project_Margin_Percentage__c 
                    From Quote
                    WHERE opportunityId =: oppId
                    ORDER BY createdDate DESC];
       
    }
    
    public void deleteQuote(){
        Quote toBeDeleteQuote = [Select Id, Is_Active_Project_Financials__c From Quote Where Id =: deleteQuoteId];
        Id profileId = UserInfo.getProfileId();
        String profileName =[Select Id, Name from Profile where Id=:profileId].Name;
        system.debug('Profile Name'+profileName);
        if(profileName != 'System Administrator' && toBeDeleteQuote.Is_Active_Project_Financials__c == true) {
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'You cannot delete the Active Project Financials Quote'));
        } else {
            delete toBeDeleteQuote;
        }
    }
    
    public pageReference newQuote(){
        PageReference pr = new PageReference('/apex/NewQuote?retURL='+ oppId + '&cancelURL=' + oppId + '&oppId=' + oppId);
        return pr;
    }
    
    //public void makeQuotePrimaryAndSync(){}
    
    public void syncBackToOpportunity(){
        system.debug('##--'+syncQuoteId);
        if(syncQuoteId != null && syncQuoteId != ''){
            system.debug('##--'+syncQuoteId);
            Quote quoteRecord = [Select Id,OpportunityId,Total_Base_Bid_Total__c,Total_Extended_Cost__c,Total_Project_Margin__c
                                    FROM Quote
                                    WHERE Id =: syncQuoteId];
            
            List<Opportunity> lstOpportunity = [Select Id,Total_Base_Bid_Total_Quote__c,Total_Extended_Cost_Quote__c,Sync_Quote__c,Total_Project_Margin__c 
                                            From Opportunity
                                            WHERE Id =: quoteRecord.opportunityId];
                                            
            if(!lstOpportunity.isEmpty()){
                lstOpportunity[0].Total_Base_Bid_Total_Quote__c = quoteRecord.Total_Base_Bid_Total__c;
                lstOpportunity[0].Total_Extended_Cost_Quote__c = quoteRecord.Total_Extended_Cost__c;
                lstOpportunity[0].Total_Project_Margin__c = quoteRecord.Total_Project_Margin__c;
                lstOpportunity[0].Sync_Quote__c = syncQuoteId;
                
                update lstOpportunity[0];
                                                
            }
            
            
        }
        
    }
    
}