force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Product Groups</relationshipLabel>
    <relationshipName>Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/Product_Select__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Select__c/fields/Completed_Startup_Date__c.field-meta.xml
<CustomField>
    <fullName>Completed_Startup_Date__c</fullName>
    <label>Completed Startup</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Hide_Line_On_Email__c.field-meta.xml
<CustomField>
    <fullName>Hide_Line_On_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Line On Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>ProductSelects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Schedule_Startup_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Startup_Date__c</fullName>
    <label>Schedule Startup</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Warranty_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Warranty_End_Date__c</fullName>
    <label>Warranty End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Warranty_Parts_Covered__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Parts_Covered__c</fullName>
    <label>Parts Covered</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Warranty_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Start_Date__c</fullName>
    <label>Warranty Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Warranty_Term__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Term__c</fullName>
    <label>Warranty</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/fields/Warranty_Type__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Type__c</fullName>
    <label>Warranty Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Labor &amp; Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SearchProductsController.cls
Public With Sharing Class SearchProductsController {
    public Map<Id,Project__c> quoteLineToProduct {get;set;}
    public SearchProductsController() {
        searchProducts();
    }
    public string SerialNumber {
        get
        {
            if(SerialNumber == null)
                SerialNumber = '';
            return SerialNumber;
        }
        set;
    }
    
    public List<Product_Select__c> quoteLineItems {
        get
        {
            if(quoteLineItems == null)
                quoteLineItems = new List<Product_Select__c>();
            return quoteLineItems;
        }
        set;
    }
    
    public void searchProducts () {
        
        if (quoteLineItems != null) {
            quoteLineItems.clear();
        }
        quoteLineToProduct = new Map<Id,Project__c>();
        System.Debug('Initializing search, keyword is : ' + SerialNumber);   
        if(SerialNumber == '') {
            return;
        }    
        String finalSearchValue = '%' + SerialNumber + '%';
        List<Product_Select__c> quoteLines = new List<Product_Select__c>();
        
        // add all the required fields
        String QL_Query = 'SELECT Id,Name,Warranty_Start_Date__c,Warranty_End_Date__c,Warranty_Type__c';
        QL_Query  += ',Product_Group__r.Name,Tag__c,Hide_Line_On_Email__c,Product_Code__c,Warranty_Parts_Covered__c';
        QL_Query  += ',Serial_Number__c,Schedule_Startup_Date__c,Completed_Startup_Date__c,Warranty_Term__c,Quote__r.OpportunityId ';
        
        // add conditions
        QL_Query  += 'FROM Product_Select__c WHERE ';
        if(SerialNumber != '' && SerialNumber != null && 
           String.isNotBlank(SerialNumber) && String.isNotEmpty(SerialNumber)) {
            QL_Query  += 'Serial_Number__c like :finalSearchValue ';
            QL_Query  += 'OR Tracking_Number__c like :finalSearchValue ';
        } else {
            QL_Query  += 'Warranty_End_Date__c != null  Order By Warranty_End_Date__c ASC';
        }
        QL_Query  += ' LIMIT 1000';

        quoteLines  = database.query(QL_Query);
        quoteLineToProduct = fetchProjectsForQL(quoteLines);
        quoteLineItems = quoteLines;
    }
    
    public Map<Id,Project__c> fetchProjectsForQL(List<Product_Select__c> quoteLines) {
        Map<Id,Project__c> quoteLineToProduct = new Map<Id,Project__c>();
        Transient Map<Id,Project__c> OpportunityIdToProject = new Map<Id,Project__c>();
        Transient List<Project__c> projects = new List<Project__c>();
        Transient Project__c Blankproj = new Project__c (Name='Not Found');
        Transient set<Id> OpportunityIds = new set<Id>();

        for(Product_Select__c ql : quoteLines) {
            OpportunityIds.add(ql.Quote__r.OpportunityId);
            quoteLineToProduct.put(ql.Id,Blankproj);
        }
        projects = [SELECT Id,Opportunity__c,Name From Project__c WHERE Opportunity__c IN :OpportunityIds];
        if(projects.size() > 0) {
            for(Project__c prj : projects) {
                OpportunityIdToProject.put(prj.Opportunity__c, prj);
            }
    
            for(Product_Select__c ql : quoteLines) {
                if(OpportunityIdToProject.containsKey(ql.Quote__r.OpportunityId)) {
                    Project__c prjectForQL = OpportunityIdToProject.get(ql.Quote__r.OpportunityId);
                    quoteLineToProduct.put(ql.Id,prjectForQL);
                }
                
            }
        }

        return quoteLineToProduct;
    }
}