force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Select__c/Product_Select__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Select__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SubGroup.cls
public with sharing class SubGroup {

    public Product_Group__c subGroup {get;set;}
    public List<Product_Select__c> lstQuoteLineItems {get;set;}
    public List<OrderLineItem> lstOrderLineItems {get;set;}

    public SubGroup() {
        subGroup = new Product_Group__c();
        subGroup.Name = '';
        lstQuoteLineItems = new List<Product_Select__c>();
        lstOrderLineItems = new List<OrderLineItem>();
    }
    
    public SubGroup(Product_Group__c subGroup){
        this.subGroup = subGroup;
        lstQuoteLineItems = new List<Product_Select__c>();
        lstOrderLineItems = new List<OrderLineItem>();
    }

}