force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Parent_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipLabel>Product Groups (Parent Product Group)</relationshipLabel>
    <relationshipName>ProductGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Select__c/Product_Select__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Select__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SparkQuotePdfController.cls
public with sharing class SparkQuotePdfController {

    public List<GroupWrapper> lstGroup {get;set;}

    public SparkQuotePdfController(ApexPages.StandardController cont) {
        
        lstGroup = new List<GroupWrapper>();

        Map<Id, Product_Group__c> mapSubGroup = CartQueryHelper.getSubGroupWithQuoteLineItems(cont.getId());
        Map<Id, Product_Group__c> mapParentGroup = CartQueryHelper.getParentGroups(cont.getId());
                
        Id parentGroupId = null;
        
        GroupWrapper objGroupWrapper;
        Map<Id, GroupWrapper> mapParentGroupWrapper = new Map<Id, GroupWrapper>();
        
        for(Product_Group__c grp : mapParentGroup.values()) {
            objGroupWrapper = new GroupWrapper(grp);
            for(Product_Group__c subGroup : grp.ProductGroups__r) {
                SubGroup objSubGroup = new SubGroup(subGroup);
                for(Product_Select__c lineItem : mapSubGroup.get(subGroup.Id).Quote_Line_Items__r) {
                    objSubGroup.lstQuoteLineItems.add(lineItem);
                }
                objGroupWrapper.lstSubGroups.add(objSubGroup);
            }
            lstGroup.add(objGroupWrapper);
        }
    }
}