force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Submitted Expense Line</label>
    <nameField>
        <displayFormat>Ex-{00000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submitted Expense Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Description_Or_Notes_Related_To_Expense__c.field-meta.xml
<CustomField>
    <fullName>Description_Or_Notes_Related_To_Expense__c</fullName>
    <label>Description Or Notes Related To Expense</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Amount__c</fullName>
    <label>Expense Amount ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Type__c.field-meta.xml
<CustomField>
    <fullName>Expense_Type__c</fullName>
    <label>Expense Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Building Repair/Maintenance</fullName>
            </value>
            <value>
                <fullName>Construction Vehicles expense/fuel</fullName>
            </value>
            <value>
                <fullName>Donations</fullName>
            </value>
            <value>
                <fullName>Education/Training</fullName>
            </value>
            <value>
                <fullName>Entertainment w/ Customers</fullName>
            </value>
            <value>
                <fullName>Entertainment w/Employee</fullName>
            </value>
            <value>
                <fullName>Entertainment w/Vendors</fullName>
            </value>
            <value>
                <fullName>Fuel</fullName>
            </value>
            <value>
                <fullName>Job-Related Materials/Expenses</fullName>
            </value>
            <value>
                <fullName>Marketing/Advertising</fullName>
            </value>
            <value>
                <fullName>Meals w/customers</fullName>
            </value>
            <value>
                <fullName>Meal w/Employees</fullName>
            </value>
            <value>
                <fullName>Meal w/Vendor</fullName>
            </value>
            <value>
                <fullName>Mileage - Sales Executives</fullName>
            </value>
            <value>
                <fullName>Office/Break Room Supplies</fullName>
            </value>
            <value>
                <fullName>Office Equipment/Computers</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Personal Car Mileage</fullName>
            </value>
            <value>
                <fullName>Postage/Shipping</fullName>
            </value>
            <value>
                <fullName>Professional Subscription/Dues</fullName>
            </value>
            <value>
                <fullName>Promotional shows/Products</fullName>
            </value>
            <value>
                <fullName>Public Transportation</fullName>
            </value>
            <value>
                <fullName>Seminar/Course fees/Conference</fullName>
            </value>
            <value>
                <fullName>Tolls</fullName>
            </value>
            <value>
                <fullName>Travel - Airfare</fullName>
            </value>
            <value>
                <fullName>Travel - Car Rental</fullName>
            </value>
            <value>
                <fullName>Travel - Hotel</fullName>
            </value>
            <value>
                <fullName>Travel - Meal</fullName>
            </value>
            <value>
                <fullName>Travel - Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Uber/Taxi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Log_A_Call__c.field-meta.xml
<CustomField>
    <fullName>Log_A_Call__c</fullName>
    <label>Log A Call</label>
    <referenceTo>LogACall__c</referenceTo>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company Expense</fullName>
            </value>
            <value>
                <fullName>Personal Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Reason_For_Personal_Expense__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Personal_Expense__c</fullName>
    <label>Reason For Personal Expense</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Split_Expense_Across_Offices__c.field-meta.xml
<CustomField>
    <fullName>Split_Expense_Across_Offices__c</fullName>
    <label>Split Expense Across Offices</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Saint Louis</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>Oklahoma</fullName>
            </value>
            <value>
                <fullName>Kansas City</fullName>
            </value>
            <value>
                <fullName>MaRRS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Vendor_Or_Venue__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Or_Venue__c</fullName>
    <label>Vendor Or Venue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogACall__c/LogACall__c.object-meta.xml
<CustomObject>
    <label>Log A Call</label>
    <nameField>
        <displayFormat>Call-{00000}</displayFormat>
        <label>Log A Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogACall__c/fields/Account_Names__c.field-meta.xml
<CustomField>
    <fullName>Account_Names__c</fullName>
    <label>Account Names</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LogCalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments or Notes From Event</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>LogCalls</relationshipLabel>
    <relationshipName>LogCalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Contact_Names__c.field-meta.xml
<CustomField>
    <fullName>Contact_Names__c</fullName>
    <label>Contact Names</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Amount__c</fullName>
    <description>Total of expense Amount</description>
    <label>Expense Amount</label>
    <summarizedField>Expense__c.Expense_Amount__c</summarizedField>
    <summaryForeignKey>Expense__c.Log_A_Call__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Mileage_Traveled__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Traveled__c</fullName>
    <label>Mileage Traveled</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Mileage_Type__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Type__c</fullName>
    <label>Mileage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Car Allowance</fullName>
                <default>true</default>
                <label>Car Allowance</label>
            </value>
            <value>
                <fullName>No Car Allowance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>LogCalls</relationshipLabel>
    <relationshipName>LogCalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Existing Contact</fullName>
            </value>
            <value>
                <fullName>New Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Type_of_Call__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Call__c</fullName>
    <label>Type of Call</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client Office Visit</fullName>
            </value>
            <value>
                <fullName>End User Visit</fullName>
            </value>
            <value>
                <fullName>Entertain (Hpy Hr, Glf, Gms)</fullName>
            </value>
            <value>
                <fullName>Expense Only</fullName>
            </value>
            <value>
                <fullName>Factory Visit (Travel)</fullName>
            </value>
            <value>
                <fullName>Industry Event (Ashrae etc.)</fullName>
            </value>
            <value>
                <fullName>Meal</fullName>
            </value>
            <value>
                <fullName>Site Visit (Project Related)</fullName>
            </value>
            <value>
                <fullName>Training (L-N-L, Seminar)</fullName>
            </value>
            <value>
                <fullName>Factory Visit (Local)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/LogCallExtend__c.object-meta.xml
<CustomObject>
    <label>Log Call Extend</label>
    <nameField>
        <displayFormat>CallExtend-{00000}</displayFormat>
        <label>LogCallExtend Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Call Extend</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogCallExtend__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Calls</relationshipLabel>
    <relationshipName>LogCallExtends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/fields/Account_Names__c.field-meta.xml
<CustomField>
    <fullName>Account_Names__c</fullName>
    <formula>LogACall__r.Account_Names__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accounts</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <formula>LogACall__r.Comments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Comments or Notes From Event</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Calls</relationshipLabel>
    <relationshipName>LogCallExtends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/fields/Contact_Names__c.field-meta.xml
<CustomField>
    <fullName>Contact_Names__c</fullName>
    <formula>LogACall__r.Contact_Names__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contacts</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <formula>LogACall__r.Event_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/fields/LogACall__c.field-meta.xml
<CustomField>
    <fullName>LogACall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Log A Call</label>
    <referenceTo>LogACall__c</referenceTo>
    <relationshipLabel>LogCallExtends</relationshipLabel>
    <relationshipName>LogCallExtends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/fields/Type_of_Call__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Call__c</fullName>
    <formula>TEXT(LogACall__r.Type_of_Call__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type of Call</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LogCallControllerTest.cls
/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 06-11-2024
 * @last modified by  : Nilesh Badrakiya
**/
@isTest
public with sharing class LogCallControllerTest {
    @testSetup static void setup()
    {
        Account account = new Account();
        account.Name = 'Test Acct';
        account.AcctSeed__Accounting_Type__c = 'Customer';
        insert account;

        Contact contact = new Contact();
        contact.AccountId = account.Id;
        contact.FirstName = 'TestCon';
        contact.LastName = 'LastCon';
        insert contact;

        Opportunity testobjOppo = new Opportunity();
        testobjOppo.Name = 'Test opportunity';
        testobjOppo.AccountId = account.Id;
        testobjOppo.StageName = 'TARGET_NEGOTIATING';
        testobjOppo.Project_Manager__c = UserInfo.getUserId();
        testobjOppo.closeDate = Date.today();
        insert testobjOppo;

        LogACall__c logACall = new LogACall__c();
        logACall.Type_of_Call__c = 'Meal';
        logACall.Mileage_Type__c ='Car Allowance';
        logACall.Mileage_Traveled__c = 35;
        logACall.Assigned_To__c = UserInfo.getUserId();
        logACall.CreatedDate = system.now().addMonths(-1);
        logACall.Event_Date__c = Date.today();
        logACall.Opportunity__c =testobjOppo.Id;
        insert logACall;
        
        Expense__c expense = new Expense__c();
        expense.Log_A_Call__c = logACall.Id;
        expense.Vendor_Or_Venue__c = 'Test of expense';
        expense.Expense_Type__c = 'Fuel';
        expense.Expense_Amount__c = 150;
        expense.Payment_Type__c = 'Company Expense';
        expense.Expense_Date__c = Date.today();
        expense.Description_Or_Notes_Related_To_Expense__c = 'test expense record';
        expense.Split_Expense_Across_Offices__c = 'Saint Louis';
        insert expense;
   
        Task task = new Task();
        task.ActivityDate = Date.today();
        task.Subject = 'Send Letter';
        task.Contact__c = contact.Id;
        task.WhatId = testobjOppo.Id;
        insert task;

    }
 
    @isTest static void testloadLogACall(){
       
        LogCallController.loadLogACall(UserInfo.getUserId(), 'Opportunity');
        LogCallController.loadLogACall(UserInfo.getUserId(), 'Contact');
        LogCallController.loadLogACall(UserInfo.getUserId(), 'Account');
        LogCallController.getCurrentUserOfficeLocation();
    }

    @isTest static void testsaveLogACall(){

        Account account = new Account();
        account.Name = 'Test Acct';
        account.AcctSeed__Accounting_Type__c = 'Customer';
        insert account;

        Contact contact = new Contact();
        contact.AccountId = account.Id;
        contact.FirstName = 'TestCon';
        contact.LastName = 'LastCon';
        insert contact;

        Opportunity testobjOppo = new Opportunity();
        testobjOppo.Name = 'Test opportunity';
        testobjOppo.AccountId = account.Id;
        testobjOppo.StageName = 'TARGET_NEGOTIATING';
        testobjOppo.Project_Manager__c = UserInfo.getUserId();
        testobjOppo.closeDate = Date.today();
        insert testobjOppo;

        LogACall__c logACall = new LogACall__c();
        logACall.Type_of_Call__c = 'Meal';
        logACall.Mileage_Type__c ='Car Allowance';
        logACall.Mileage_Traveled__c = 35;
        logACall.Assigned_To__c = UserInfo.getUserId();
        logACall.CreatedDate = system.now().addMonths(-1);
        logACall.Event_Date__c = Date.today();
        logACall.Relationship__c ='Existing Contact';
        logACall.Opportunity__c =testobjOppo.Id;
        logACall.Comments__c = 'test comment';
        logACall.Contact_Names__c = 'TestCon LastCon';
        logACall.Account_Names__c = 'Test Acct';
        insert logACall;
        
        Expense__c expense = new Expense__c();
        expense.Log_A_Call__c = logACall.Id;
        expense.Vendor_Or_Venue__c = 'Test of expense';
        expense.Expense_Type__c = 'Fuel';
        expense.Expense_Amount__c = 150;
        expense.Payment_Type__c = 'Company Expense';
        expense.Reason_For_Personal_Expense__c = 'Test reson for Expense';
        expense.Split_Expense_Across_Offices__c = 'Saint Louis';
        expense.Expense_Date__c = Date.today();
        insert expense;
   
        Task task = new Task();
        task.ActivityDate = Date.today();
        task.Subject = 'Send Letter';
        task.Contact__c = contact.Id;
        task.WhatId = testobjOppo.Id;
        insert task;

        LogCallExtend__c logACallExtendContact = new LogCallExtend__c();
        logACallExtendContact.Contact__c = contact.Id;
        logACallExtendContact.logACall__c = logACall.Id;
        insert logACallExtendContact;

        LogCallExtend__c logACallExtendAccount = new LogCallExtend__c();
        logACallExtendAccount.Account__c = account.Id;
        logACallExtendAccount.logACall__c = logACall.Id;
        insert logACallExtendAccount;

        FeedItem post = new FeedItem();
        post.ParentId = UserInfo.getUserId();
        post.Body = 'Test post a chatter record';
        insert post;
        system.debug('Test chatter record insert :- '+post);

        Test.startTest();
        try{
            String loadedLogACall = LogCallController.loadLogACall(UserInfo.getUserId(), 'Contact');
            system.debug('Loaded log a call: '+loadedLogACall);

            LogCallController.LogACallDetailWrapper strJson = new LogCallController.LogACallDetailWrapper();
            strJson = (LogCallController.LogACallDetailWrapper) 
                      JSON.deserialize(loadedLogACall, LogCallController.LogACallDetailWrapper.class);

            LogCallController.logACallWrapper logACallWrapperObj = new  LogCallController.logACallWrapper();

            if(strJson != null && strJson.logACall != null) {
                system.debug('fetch contact and account data'+strJson.logACall.contacts);
                system.debug('fetch account data'+strJson.logACall.accounts);
                
                logACallWrapperObj = (LogCallController.logACallWrapper) 
                                     JSON.deserialize(JSON.serialize(strJson.logACall), LogCallController.logACallWrapper.class);
            }
     
            //Task Records
            List<LogCallController.TaskWrapper> lstTasks = new List<LogCallController.TaskWrapper>();
            List<LogCallController.TaskWrapper> lstTaskWrapper = (List<LogCallController.TaskWrapper>) JSON.deserialize(
                JSON.serialize(strJson.lstTasks), List<LogCallController.TaskWrapper>.class);

            if(strJson != null && strJson.lstTasks != null) {
                system.debug('task to insert : '+strJson.lstTasks);
                for(Integer i=0; i < lstTaskWrapper.size(); i++) {

                    lstTasks.add(lstTaskWrapper[i]);
                }
            }
            
            //Expense Record
            List<LogCallController.ExpenseWrapper> lstExpenses = new List<LogCallController.ExpenseWrapper>();
            List<LogCallController.ExpenseWrapper> lstExpWrapper = (List<LogCallController.ExpenseWrapper>) JSON.deserialize(
                                    JSON.serialize(strJson.lstExpenses), List<LogCallController.ExpenseWrapper>.class);

            if(strJson != null && strJson.lstExpenses != null) {
                for(Integer i=0; i < lstExpWrapper.size(); i++) {
                    
                    lstExpenses.add(lstExpWrapper[i]);
                }
            }
            // chatter expense 
            List<LogCallController.ChatterWrapper> lstChatter = new List<LogCallController.ChatterWrapper>();
            List<LogCallController.ChatterWrapper> lstchatWrapper = (List<LogCallController.ChatterWrapper>) JSON.deserialize(
                                    JSON.serialize(strJson.lstChatter), List<LogCallController.ChatterWrapper>.class);

            if(strJson != null && strJson.lstChatter != null) {
                for(Integer i=0; i < lstchatWrapper.size(); i++) {
                    
                    lstChatter.add(lstchatWrapper[i]);
                }
            }
            String strExpenseJSON;
            String strTasksJSON;
            if(logACallWrapperObj.typeOfCall != 'Expense Only') {
                logACallWrapperObj.contacts = new List<String>{contact.id};
                logACallWrapperObj.accounts = new List<String>{account.id};
    
                List<LogCallController.TaskWrapper> lstTasksToInsert = new List<LogCallController.TaskWrapper>();
                strTasksJSON = JSON.serialize(lstTasksToInsert);
            }

            
            LogCallController.saveLogACall(JSON.serialize(logACallWrapperObj), JSON.serialize(lstExpenses), strTasksJSON ,JSON.serialize(lstChatter));
            
        }
        catch(exception e){
        }     
        Test.stopTest();
    }

}