force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Submitted Expense Line</label>
    <nameField>
        <displayFormat>Ex-{00000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submitted Expense Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Amount__c</fullName>
    <label>Expense Amount ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Type__c.field-meta.xml
<CustomField>
    <fullName>Expense_Type__c</fullName>
    <label>Expense Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Building Repair/Maintenance</fullName>
            </value>
            <value>
                <fullName>Construction Vehicles expense/fuel</fullName>
            </value>
            <value>
                <fullName>Donations</fullName>
            </value>
            <value>
                <fullName>Education/Training</fullName>
            </value>
            <value>
                <fullName>Entertainment w/ Customers</fullName>
            </value>
            <value>
                <fullName>Entertainment w/Employee</fullName>
            </value>
            <value>
                <fullName>Entertainment w/Vendors</fullName>
            </value>
            <value>
                <fullName>Fuel</fullName>
            </value>
            <value>
                <fullName>Job-Related Materials/Expenses</fullName>
            </value>
            <value>
                <fullName>Marketing/Advertising</fullName>
            </value>
            <value>
                <fullName>Meals w/customers</fullName>
            </value>
            <value>
                <fullName>Meal w/Employees</fullName>
            </value>
            <value>
                <fullName>Meal w/Vendor</fullName>
            </value>
            <value>
                <fullName>Mileage - Sales Executives</fullName>
            </value>
            <value>
                <fullName>Office/Break Room Supplies</fullName>
            </value>
            <value>
                <fullName>Office Equipment/Computers</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Personal Car Mileage</fullName>
            </value>
            <value>
                <fullName>Postage/Shipping</fullName>
            </value>
            <value>
                <fullName>Professional Subscription/Dues</fullName>
            </value>
            <value>
                <fullName>Promotional shows/Products</fullName>
            </value>
            <value>
                <fullName>Public Transportation</fullName>
            </value>
            <value>
                <fullName>Seminar/Course fees/Conference</fullName>
            </value>
            <value>
                <fullName>Tolls</fullName>
            </value>
            <value>
                <fullName>Travel - Airfare</fullName>
            </value>
            <value>
                <fullName>Travel - Car Rental</fullName>
            </value>
            <value>
                <fullName>Travel - Hotel</fullName>
            </value>
            <value>
                <fullName>Travel - Meal</fullName>
            </value>
            <value>
                <fullName>Travel - Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Uber/Taxi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Log_A_Call__c.field-meta.xml
<CustomField>
    <fullName>Log_A_Call__c</fullName>
    <label>Log A Call</label>
    <referenceTo>LogACall__c</referenceTo>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company Expense</fullName>
            </value>
            <value>
                <fullName>Personal Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Vendor_Or_Venue__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Or_Venue__c</fullName>
    <label>Vendor Or Venue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogACall__c/LogACall__c.object-meta.xml
<CustomObject>
    <label>Log A Call</label>
    <nameField>
        <displayFormat>Call-{00000}</displayFormat>
        <label>Log A Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogACall__c/fields/Account_Names__c.field-meta.xml
<CustomField>
    <fullName>Account_Names__c</fullName>
    <label>Account Names</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Accounts__c.field-meta.xml
<CustomField>
    <fullName>Accounts__c</fullName>
    <label>Accounts</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LogCalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments or Notes From Event</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>LogCalls</relationshipLabel>
    <relationshipName>LogCalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Contact_Names__c.field-meta.xml
<CustomField>
    <fullName>Contact_Names__c</fullName>
    <label>Contact Names</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Contacts__c.field-meta.xml
<CustomField>
    <fullName>Contacts__c</fullName>
    <label>Contacts</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Amount__c</fullName>
    <description>Total of expense Amount</description>
    <label>Expense Amount</label>
    <summarizedField>Expense__c.Expense_Amount__c</summarizedField>
    <summaryForeignKey>Expense__c.Log_A_Call__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Mileage_Traveled__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Traveled__c</fullName>
    <label>Mileage Traveled</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Mileage_Type__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Type__c</fullName>
    <label>Mileage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Car Allowance</fullName>
                <default>true</default>
                <label>Car Allowance</label>
            </value>
            <value>
                <fullName>No Car Allowance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>LogCalls</relationshipLabel>
    <relationshipName>LogCalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Existing Contact</fullName>
            </value>
            <value>
                <fullName>New Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogACall__c/fields/Type_of_Call__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Call__c</fullName>
    <label>Type of Call</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client Office Visit</fullName>
            </value>
            <value>
                <fullName>End User Visit</fullName>
            </value>
            <value>
                <fullName>Entertain (Hpy Hr, Glf, Gms)</fullName>
            </value>
            <value>
                <fullName>Expense Only</fullName>
            </value>
            <value>
                <fullName>Factory Visit (Travel)</fullName>
            </value>
            <value>
                <fullName>Industry Event (Ashrae etc.)</fullName>
            </value>
            <value>
                <fullName>Meal</fullName>
            </value>
            <value>
                <fullName>Site Visit (Project Related)</fullName>
            </value>
            <value>
                <fullName>Training (L-N-L, Seminar)</fullName>
            </value>
            <value>
                <fullName>Factory Visit (Local)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/LogCallExtend__c.object-meta.xml
<CustomObject>
    <label>Log Call Extend</label>
    <nameField>
        <displayFormat>CallExtend-{00000}</displayFormat>
        <label>LogCallExtend Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Call Extend</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogCallExtend__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Calls</relationshipLabel>
    <relationshipName>LogCallExtends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/fields/Account_Names__c.field-meta.xml
<CustomField>
    <fullName>Account_Names__c</fullName>
    <formula>LogACall__r.Account_Names__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accounts</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <formula>LogACall__r.Comments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Comments or Notes From Event</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Calls</relationshipLabel>
    <relationshipName>LogCallExtends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/fields/Contact_Names__c.field-meta.xml
<CustomField>
    <fullName>Contact_Names__c</fullName>
    <formula>LogACall__r.Contact_Names__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contacts</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <formula>LogACall__r.Event_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/fields/LogACall__c.field-meta.xml
<CustomField>
    <fullName>LogACall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Log A Call</label>
    <referenceTo>LogACall__c</referenceTo>
    <relationshipLabel>LogCallExtends</relationshipLabel>
    <relationshipName>LogCallExtends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LogCallExtend__c/fields/Type_of_Call__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Call__c</fullName>
    <formula>TEXT(LogACall__r.Type_of_Call__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type of Call</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saint Louis</fullName>
            </value>
            <value>
                <fullName>Oklahoma</fullName>
            </value>
            <value>
                <fullName>Kansas City</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>Midwest Industrial Builders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LogCallController.cls
/**
 * @description       : 
 * @author            : Nilesh Badrakiya
 * @group             : 
 * @last modified on  : 06-13-2024
 * @last modified by  : Nilesh Badrakiya
**/
public with sharing class LogCallController {
    public class applicationException extends Exception {}
   
    public LogCallController() {

    }

    // for Getting current user office location
    // And permission set name for MaRRs user default office is set as MaRRs
    @AuraEnabled
    public static string getCurrentUserOfficeLocation(){
        Set<Id> setMarrsPermissonUser = new Set<Id>();
           List<PermissionSetAssignment> lstPermissionUser = [SELECT Id, PermissionSet.Name, AssigneeId, Assignee.Name
                                                              FROM PermissionSetAssignment 
                                                              WHERE PermissionSet.Name = 'MaRRs'];
        for(PermissionSetAssignment permissionUser : lstPermissionUser){
            setMarrsPermissonUser.add(permissionUser.AssigneeId);
        }
        
        List<User> lstUser = [SELECT Id, Office_Location__c FROM User WHERE Id =: UserInfo.getUserId()];
        if(lstUser.size() > 0){
            User user = lstUser[0];
            if(setMarrsPermissonUser.contains(user.id)){
                system.debug('inside if user Marrs' +user.id);
                return 'MaRRS';
            }
            else if(lstUser != null && lstUser.size() > 0){
                User currentUser = lstUser.get(0);
                return currentUser.Office_Location__c;
            }
        }
        return '';
    }

    @AuraEnabled
    public static string loadLogACall(String recordId, String objectName) {

        LogACallDetailWrapper logACall = new LogACallDetailWrapper();
        system.debug(' record id loadlogcall : ' + recordId);
        if(objectName == 'Opportunity') {
            logACall.logACall.opportunityId = recordId;
            logACall.lstTasks[0].relatedTo = recordId;
            

        //loadlogACall with Contactid, Name, Accountid, AccountNm task-contact field auto-populate on contact page 
        } else if(objectName == 'Contact') {
            logACall.logACall.contacts.add(recordId);
           
            List<Contact> lstContacts = [SELECT Id,Name, AccountId, Account.Name FROM Contact WHERE Id =: recordId];
             system.debug('contact list before load :' + lstContacts);
            if(!lstContacts.isEmpty()) {
                logACall.logACall.contactNames.add(lstContacts[0].Name);
                logACall.lstTasks[0].contact = recordId; //auto- pouplate only on contact page.

                if(lstContacts[0].AccountId != null) {
                    logACall.logACall.accounts.add(lstContacts[0].AccountId);
                    logACall.logACall.accountNames.add(lstContacts[0].Account.Name); 
                } 
            }
        }
        else if(objectName == 'Account'){
            logACall.logACall.accounts.add(recordId);
            
            List<Account> lstAccounts = [SELECT Id, Account.Name 
                                         FROM Account WHERE id =: recordId];

                system.debug('Account list before load :' + lstAccounts);
                if(!lstAccounts.isEmpty()){
                    logACall.logACall.accountNames.add(lstAccounts[0].Name);
                }
        }
        system.debug('LogACallDetailWrapper' + logACall);
        return JSON.serialize(logACall);
    }

    @AuraEnabled
    public static string saveLogACall(String logACall, String strExpenses, String strTasks, String strChatter) {
        system.debug('LogACall=>'+logACall);
        system.debug('Expenses=>'+strExpenses);
        system.debug('Tasks=>'+strTasks);
        system.debug('Chatter=>'+strChatter);

        try {
            
            LogACallWrapper objLogACall = (LogACallWrapper) JSON.deserialize(logACall, LogACallWrapper.class);

            LogACall__c newLogACall = new logACall__c();

            newLogACall.Type_of_Call__c = objLogACall.typeOfCall;
            newLogACall.Event_Date__c = objLogACall.eventDate;
            newLogACall.Mileage_Type__c = objLogACall.mileageType;
            newLogACall.Mileage_Traveled__c = objLogACall.mileageTraveled;
            newLogACall.Opportunity__c = objLogACall.opportunityId;
            newLogACall.Assigned_To__c = UserInfo.getUserId();

            if(newLogACall.Type_of_Call__c != 'Expense Only') {
                newLogACall.Relationship__c = objLogACall.relationship;    
                newLogACall.Comments__c = objLogACall.comments;

                if(!objLogACall.contacts.isEmpty()) {
                    newLogACall.Contacts__c = String.join(objLogACall.contacts, ', ');
                   //newLogACall.Contact_Names__c = String.join(objLogACall.contactNames, ',');

                    List<String> lstContactNames = new List<String>();
                    for(Contact contact : [SELECT Name FROM Contact WHERE Id IN : objLogACall.contacts]){
                        lstContactNames.add(contact.Name);
                    }
                    newLogACall.Contact_Names__c = String.Join(lstContactNames, ', ');

                    system.debug('contact name selected by users'+ newLogACall.Contacts__c + ',' + newLogACall.Contact_Names__c);
                }
            }
                if(!objLogACall.accounts.isEmpty()) {
                    newLogACall.Accounts__c = String.join(objLogACall.accounts, ', ');

                    List<String> lstAccountNames = new List<string>();
                    for(Account account : [SELECT Name FROM Account WHERE Id IN : objLogACall.accounts]){
                        lstAccountNames.add(account.Name);
                    }
                    newLogACall.Account_Names__c = string.join(lstAccountNames, ', ');
                }
            
            insert newLogACall; 
                 
            //Related records for LogACall ||Account || Contact
            List<LogCallExtend__c> lstLogCallExt = new List<LogCallExtend__c>();
                    for(String contactId : objLogACall.contacts){
                        LogCallExtend__c extCon = new LogCallExtend__c();
                        extCon.Contact__c = contactId;
                        extCon.logACall__c = newLogACall.Id;
                        lstLogCallExt.add(extCon);
                       
                    }
                    for(String AccountId : objLogACall.accounts){
                        LogCallExtend__c extAcc = new LogCallExtend__c();
                        extAcc.Account__c = AccountId;
                        extAcc.logACall__c = newLogACall.Id;
                        lstLogCallExt.add(extAcc);
                        
                    }
                    insert lstLogCallExt;
            

            if(newLogACall.Type_of_Call__c != 'Expense Only') {
                List<Task> lstTasksToInsert = new List<Task>();
                List<TaskWrapper> lstTasksWrapper = (List<TaskWrapper>) JSON.deserialize(strTasks, List<TaskWrapper>.class);
                 
                for(TaskWrapper taskWrapper : lstTasksWrapper) {
                    // for(String userId : taskWrapper.assignedToIds) {}
                    Task newTask = new Task();
                    if(objLogACall.opportunityId != null) {
                        newTask.WhatId = objLogACall.opportunityId;
                    }
                    newTask.ActivityDate = taskWrapper.dueDate;
                    newTask.Subject = taskWrapper.subject;
                    if(taskWrapper.relatedTo != ''){
                        newTask.WhatId = taskWrapper.relatedTo;
                    }
                    if(taskWrapper.contact != ''){
                        newTask.Contact__c = taskWrapper.contact;
                    }
                    lstTasksToInsert.add(newTask);
                }

                if(!lstTasksToInsert.isEmpty()) {
                    insert lstTasksToInsert;
                }
            }
            
            List<Expense__c> lstExpensesToInsert = new List<Expense__c>();
            List<ExpenseWrapper> lstExpensesWrapper = (List<ExpenseWrapper>) JSON.deserialize(strExpenses, List<ExpenseWrapper>.class);

            Boolean hasEmptyElement = false;
            for(ExpenseWrapper expenseWrapper : lstExpensesWrapper) {
                Expense__c newExpense = new Expense__c();
                newExpense.Log_A_Call__c = newLogACall.Id;
                newExpense.Vendor_Or_Venue__c = expenseWrapper.vendorOrVenue;
                newExpense.Expense_Type__c = expenseWrapper.expenseType;
                newExpense.Expense_Amount__c = expenseWrapper.expenseAmount;
                newExpense.Payment_Type__c = expenseWrapper.paymentType;
                newExpense.Project__c = expenseWrapper.project;

                //expense date = event date if not then save expense date
                if(newLogACall.Event_Date__c != expenseWrapper.expenseDate) 
                {
                    newExpense.Expense_Date__c = expenseWrapper.expenseDate;
                   
                }else{
                    newExpense.Expense_Date__c = newLogACall.Event_Date__c;
                    
                }

                if(newExpense.Payment_Type__c == 'Personal Expense') {
                    newExpense.Reason_For_Personal_Expense__c = expenseWrapper.reason;
                }
                newExpense.Description_Or_Notes_Related_To_Expense__c = expenseWrapper.description;
                
                // To check whether the split expense is blank or not, If blank it throws error
                 for (String str : expenseWrapper.splitExpenses) {
                     if (String.isBlank(str)) {
                        hasEmptyElement = true;
                         break;
                     }
                 }
                 if(hasEmptyElement){
                    break;
                 }else{
                    newExpense.Split_Expense_Across_Offices__c = String.join(expenseWrapper.splitExpenses, ', ');
                        lstExpensesToInsert.add(newExpense);
                 }
            }
            
            if(hasEmptyElement == true) {
                system.debug('error thrown');
                throw new applicationException('Split expenses cannot be empty.');   
            }else{
                if(!lstExpensesToInsert.isEmpty()) {
                    insert lstExpensesToInsert;   
                }
                
                List<FeedItem> lstChatterToInsert = new List<FeedItem>();
                List<ChatterWrapper> lstChatterWrapper = (List<ChatterWrapper>) JSON.deserialize(strChatter, List<ChatterWrapper>.class);
    
                for(ChatterWrapper chatterWrapper : lstChatterWrapper) {
                    if(chatterWrapper.postFeedCheckBox  == true && newLogACall.Comments__c != ''){
                        FeedItem feed = new FeedItem();
                        feed.ParentId = chatterWrapper.chatterParentId;     
                        feed.Body = objLogACall.comments;
                        //insert feed;
                        system.debug('chatter post message :- ' +feed);
                        lstChatterToInsert.add(feed);
                    }
                    if(!lstChatterToInsert.isEmpty()){
                        insert lstChatterToInsert;
                        system.debug('chatter record insert :- ' +lstChatterToInsert);
                    }
                }

                if(newLogACall.Opportunity__c != null) {
                    return loadLogACall(newLogACall.Opportunity__c, 'Opportunity');
                }
            }
            return null;
        } catch (Exception e) {
            system.debug('Inside catch :- ' +e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    public with sharing class LogACallDetailWrapper {
        @AuraEnabled public logACallWrapper logACall {get;set;}
        @AuraEnabled public List<TaskWrapper> lstTasks {get;set;}
        @AuraEnabled public List<ExpenseWrapper> lstExpenses {get;set;}
        @AuraEnabled public List<ChatterWrapper> lstChatter {get;set;}
       // @AuraEnabled public UserWrapper lstUser {get;set;}

        public LogACallDetailWrapper() {
            
            logACall = new logACallWrapper();

            lstTasks = new List<TaskWrapper>();
            lstTasks.add(new TaskWrapper());
            
            lstExpenses = new List<ExpenseWrapper>();
            lstExpenses.add(new ExpenseWrapper());

            lstChatter = new  List<ChatterWrapper>();
            lstChatter.add(new ChatterWrapper());

           // lstUser = new UserWrapper();
        }

    }


    public with sharing class logACallWrapper {
        @AuraEnabled public String typeOfCall {get; set;}
        @AuraEnabled public Date eventDate {get; set;}
        @AuraEnabled public List<String> contacts {get; set;}
        @AuraEnabled public List<String> contactNames {get; set;}
        @AuraEnabled public List<String> accounts {get; set;}
        @AuraEnabled public List<String> accountNames {get; set;}
        @AuraEnabled public String relationship {get; set;}
        @AuraEnabled public String opportunityId {get; set;}
        @AuraEnabled public String comments {get; set;} //used in logAcall comment field and chatter body.
        @AuraEnabled public String mileageType {get; set;}
        @AuraEnabled public Integer mileageTraveled {get; set;}

        public logACallWrapper() {
            
            this.eventDate = Date.today();
            this.mileageType = 'Car Allowance';

            this.contacts = new List<String>();
            this.contactNames = new List<String>();
            
            this.accounts = new List<String>();
            this.accountNames = new List<String>();
        }
    }

    public with sharing class TaskWrapper {
        @AuraEnabled public String subject {get; set;}
        @AuraEnabled public Date dueDate {get; set;}
        @AuraEnabled public List<String> assignedToIds {get; set;}
        @AuraEnabled public String contact {get; set;}
        @AuraEnabled public String relatedTo {get; set;}

        public TaskWrapper() {
            this.assignedToIds = new List<String>();
        }
    }

    public with sharing class ExpenseWrapper {
        @AuraEnabled public String vendorOrVenue {get; set;}
        @AuraEnabled public String expenseType {get; set;}
        @AuraEnabled public Decimal expenseAmount {get; set;}
        @AuraEnabled public String paymentType {get; set;}
        @AuraEnabled public String reason {get; set;}
        @AuraEnabled public String description {get; set;}
        @AuraEnabled public List<String> splitExpenses {get; set;}
        @AuraEnabled public Date expenseDate {get;set;}
        @AuraEnabled public String project {get; set;}

        public ExpenseWrapper() {
            this.splitExpenses = new List<String>();
            this.paymentType = 'Company Expense';
            this.expenseDate = Date.today();
        }
    }
    public with sharing class ChatterWrapper {
        @AuraEnabled  public string chatterParentId{get;set;}
        @AuraEnabled  public Boolean postFeedCheckBox{ get; set;}
    }
}